'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier, type WorkflowRole, grantSatisfies } from '@/core/auth/types';

function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
function req(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();if(!v)throw appError(`${k.replaceAll('_',' ')} is required.`);return v;}
function opt(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();return v||null;}
const priorities=['low','normal','high','urgent'];
async function access(role?:WorkflowRole){const p=await getSessionProfile();if(!p||!p.user.is_active)throw appError('Authentication required.');if(isAdminTier(p))return p;if(p.user.section_code!=='admin'&&!p.access.some(a=>a.section_code==='admin'))throw appError('Admin access required.');if(role&&!p.access.some(a=>a.section_code==='admin'&&grantSatisfies(a.workflow_role,role)))throw appError(`Admin ${role} access is required.`);return p;}
async function audit(actor:string,id:string,action:string,detail:Record<string,unknown>){const db=createClient();const {error}=await db.from('audit_log').insert({actor_id:actor,entity_table:'internal_requests',entity_id:id,action,detail});if(error)throw appError(error.message);}
function items(fd:FormData){const raw=String(fd.get('items_json')??'[]');let parsed:any[];try{parsed=JSON.parse(raw)}catch{throw appError('Invalid request items.');}if(!Array.isArray(parsed)||parsed.length===0)throw appError('Add at least one request item.');return parsed.map((x:any)=>{const description=String(x.description??'').trim();const quantity=Number(x.quantity);if(!description||!Number.isFinite(quantity)||quantity<=0)throw appError('Each request item needs a description and positive quantity.');return {supply_id:x.supply_id||null,item_description:description,quantity,unit:String(x.unit||'piece'),notes:x.notes?String(x.notes):null};});}
async function requestNo(db:any){const stamp=new Date();const prefix=`IR-${stamp.getUTCFullYear()}${String(stamp.getUTCMonth()+1).padStart(2,'0')}`;const {count}=await db.from('internal_requests').select('id',{count:'exact',head:true}).like('request_no',`${prefix}-%`);return `${prefix}-${String((count??0)+1).padStart(4,'0')}`;}

export async function createInternalRequestAction(fd:FormData){const p=await access('preparer');const db=createClient();const priority=req(fd,'priority');if(!priorities.includes(priority))throw appError('Invalid priority.');const employeeId=opt(fd,'requester_employee_id');if(employeeId){const {data:e}=await db.from('employees').select('id').eq('id',employeeId).maybeSingle();if(!e)throw appError('Requester employee not found.');}const no=await requestNo(db);const payload={...biz(p),request_no:no,category_id:opt(fd,'category_id'),requester_employee_id:employeeId,requester_user_id:p.user.id,department:opt(fd,'department'),title:req(fd,'title'),description:opt(fd,'description'),priority,needed_by:opt(fd,'needed_by'),status:'draft',prepared_by:p.user.id};const {data,error}=await db.from('internal_requests').insert(payload).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create request.');const list=items(fd).map(i=>({...biz(p),...i,request_id:data.id}));const {error:ie}=await db.from('internal_request_items').insert(list);if(ie){await db.from('internal_requests').delete().eq('id',data.id);throw appError(ie.message);}await audit(p.user.id,data.id,'created',{request_no:no,title:payload.title});revalidatePath('/admin/requests');return {ok:true};}
export async function updateInternalRequestAction(fd:FormData){const p=await access('preparer');const db=createClient();const id=req(fd,'request_id');const {data:r}=await db.from('internal_requests').select('status').eq('id',id).maybeSingle();if(!r||r.status!=='draft')throw appError('Only draft requests can be edited.');const priority=req(fd,'priority');if(!priorities.includes(priority))throw appError('Invalid priority.');const {error}=await db.from('internal_requests').update({category_id:opt(fd,'category_id'),requester_employee_id:opt(fd,'requester_employee_id'),department:opt(fd,'department'),title:req(fd,'title'),description:opt(fd,'description'),priority,needed_by:opt(fd,'needed_by')}).eq('id',id);if(error)throw appError(error.message);await db.from('internal_request_items').delete().eq('request_id',id);const {error:ie}=await db.from('internal_request_items').insert(items(fd).map(i=>({...biz(p),...i,request_id:id})));if(ie)throw appError(ie.message);await audit(p.user.id,id,'edited',{});revalidatePath('/admin/requests');return {ok:true};}
export async function submitInternalRequestAction(fd:FormData){const p=await access('preparer');const db=createClient();const id=req(fd,'request_id');const {data,error}=await db.from('internal_requests').update({status:'prepared',prepared_by:p.user.id,prepared_at:new Date().toISOString()}).eq('id',id).eq('status','draft').select('id').single();if(error||!data)throw appError(error?.message||'Request is not in draft status.');await audit(p.user.id,id,'submitted',{to_status:'prepared'});revalidatePath('/admin/requests');return {ok:true};}
export async function reviewInternalRequestAction(fd:FormData){const p=await access('reviewer');const db=createClient();const id=req(fd,'request_id');const decision=req(fd,'decision');if(!['reviewed','rejected'].includes(decision))throw appError('Invalid review decision.');const {data,error}=await db.from('internal_requests').update({status:decision,reviewed_by:p.user.id,reviewed_at:new Date().toISOString(),rejection_reason:decision==='rejected'?opt(fd,'reason'):null}).eq('id',id).eq('status','prepared').select('id').single();if(error||!data)throw appError(error?.message||'Request is no longer pending review.');await audit(p.user.id,id,decision,{reason:opt(fd,'reason')});revalidatePath('/admin/requests');return {ok:true};}
export async function approveInternalRequestAction(fd:FormData){const p=await access('approver');const db=createClient();const id=req(fd,'request_id');const {data,error}=await db.from('internal_requests').update({status:'approved',approved_by:p.user.id,approved_at:new Date().toISOString(),rejection_reason:null}).eq('id',id).eq('status','reviewed').select('id').single();if(error||!data)throw appError(error?.message||'Request is no longer pending approval.');await audit(p.user.id,id,'approved',{});revalidatePath('/admin/requests');return {ok:true};}
export async function rejectInternalRequestAction(fd:FormData){const p=await access('approver');const db=createClient();const id=req(fd,'request_id');const reason=req(fd,'reason');const {data,error}=await db.from('internal_requests').update({status:'rejected',approved_by:p.user.id,approved_at:new Date().toISOString(),rejection_reason:reason}).eq('id',id).eq('status','reviewed').select('id').single();if(error||!data)throw appError(error?.message||'Request is no longer pending approval.');await audit(p.user.id,id,'rejected',{reason});revalidatePath('/admin/requests');return {ok:true};}
export async function cancelInternalRequestAction(fd:FormData){const p=await access();const db=createClient();const id=req(fd,'request_id');const {data,error}=await db.from('internal_requests').update({status:'cancelled'}).eq('id',id).in('status',['draft','prepared']).eq('requester_user_id',p.user.id).select('id').single();if(error||!data)throw appError(error?.message||'Only your draft/prepared requests can be cancelled.');await audit(p.user.id,id,'cancelled',{});revalidatePath('/admin/requests');return {ok:true};}
export async function fulfillInternalRequestAction(fd:FormData){const p=await access();const db=createClient();const id=req(fd,'request_id');const {data:r}=await db.from('internal_requests').select('id,status').eq('id',id).maybeSingle();if(!r||r.status!=='approved')throw appError('Only approved requests can be fulfilled.');const {data:rows,error:re}=await db.from('internal_request_items').select('id,supply_id,item_description,quantity,unit').eq('request_id',id);if(re)throw appError(re.message);for(const item of rows??[]){if(!item.supply_id)continue;const {data:s}=await db.from('supplies').select('id,stock_on_hand,name').eq('id',item.supply_id).maybeSingle();if(!s)throw appError(`Supply item not found: ${item.item_description}`);const current=Number(s.stock_on_hand),n=Number(item.quantity);if(current<n)throw appError(`Insufficient stock for ${s.name}. Available: ${current}, requested: ${n}.`);const next=current-n;const {error:ue}=await db.from('supplies').update({stock_on_hand:next}).eq('id',s.id);if(ue)throw appError(ue.message);const {error:te}=await db.from('supply_transactions').insert({...biz(p),supply_id:s.id,transaction_type:'issue',quantity:n,balance_after:next,reference_type:'internal_request',reference_id:id,notes:`Issued for internal request ${id}`,performed_by:p.user.id});if(te)throw appError(te.message);}const {data,error}=await db.from('internal_requests').update({status:'fulfilled',fulfilled_by:p.user.id,fulfilled_at:new Date().toISOString()}).eq('id',id).eq('status','approved').select('id').single();if(error||!data)throw appError(error?.message||'Request could not be fulfilled.');await audit(p.user.id,id,'fulfilled',{});revalidatePath('/admin/requests');revalidatePath('/admin/supplies');return {ok:true};}
