'use client';
import { errorText } from '@/core/errors/appError';
import { useMemo,useState } from 'react';
import { useDialog } from '@/core/ui/Dialog';
import { ActionBar,PopupAction } from '@/core/ui/PopupAction';
import type { SessionProfile } from '@/core/auth/types';
import { approveInternalRequestAction,cancelInternalRequestAction,createInternalRequestAction,fulfillInternalRequestAction,rejectInternalRequestAction,reviewInternalRequestAction,submitInternalRequestAction } from './actions';
type Cat={id:string;name:string};
type Emp={id:string;employee_no:string;first_name:string;last_name:string;preferred_name?:string|null;employment_status:string};
type Supply={id:string;item_code:string;name:string;unit:string;stock_on_hand:number;active:boolean};
type Item={id:string;supply_id?:string|null;item_description:string;quantity:number;unit:string;notes?:string|null};
type Req={id:string;requester_user_id:string;request_no:string;title:string;description?:string|null;department?:string|null;priority:string;needed_by?:string|null;status:string;rejection_reason?:string|null;category?:{name:string};requester_employee?:{employee_no:string;first_name:string;last_name:string;preferred_name?:string|null};items:Item[];created_at:string};
const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function RequestsManagement({profile,categories,requests,employees,supplies}:{profile:SessionProfile;categories:Cat[];requests:Req[];employees:Emp[];supplies:Supply[]}){
 const dialog=useDialog();
 const [q,setQ]=useState(''),[status,setStatus]=useState('all'),[modal,setModal]=useState<'new'|'view'|null>(null),[selected,setSelected]=useState<Req|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[items,setItems]=useState([{description:'',quantity:'1',unit:'piece',supply_id:''}]);
 const isSuper=profile.user.role==='super_admin'||profile.user.role==='business_admin', roles=new Set(profile.access.filter(a=>a.section_code==='admin').map(a=>a.workflow_role));
 const filtered=useMemo(()=>requests.filter(r=>{const hay=`${r.request_no} ${r.title} ${r.description??''} ${r.department??''} ${r.requester_employee?.first_name??''} ${r.requester_employee?.last_name??''}`.toLowerCase();return(!q||hay.includes(q.toLowerCase()))&&(status==='all'||r.status===status)}),[requests,q,status]);
 async function run(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();setModal(null);setSelected(null)}catch(e){setError(e instanceof Error?errorText(e):'Operation failed.')}finally{setBusy(false)}}
 const can=(r:string)=>isSuper||roles.has(r as any);
 function addItem(){setItems(x=>[...x,{description:'',quantity:'1',unit:'piece',supply_id:''}])}
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-semibold">Internal Requests</h1><p className="text-sm text-slate-500">Submit, review, approve and fulfill internal company requests.</p></div></div>
 <ActionBar>{can('preparer')&&<PopupAction label="+ New request" title="New Internal Request" notice={error} wide onOpen={()=>setItems([{description:'',quantity:'1',unit:'piece',supply_id:''}])}>{(close)=><form action={fd=>{fd.set('items_json',JSON.stringify(items));return run(async()=>{await createInternalRequestAction(fd);close()})}} className="space-y-4"><div className="grid sm:grid-cols-2 gap-3"><Select name="category_id" label="Category" options={categories.map(c=>[c.id,c.name])}/><Select name="requester_employee_id" label="Requester Employee" options={employees.map(e=>[e.id,`${e.employee_no} · ${e.preferred_name||e.first_name} ${e.last_name}`])}/><Field name="department" label="Department"/><Select name="priority" label="Priority" options={['low','normal','high','urgent'].map(x=>[x,label(x)])}/><Field name="title" label="Title"/><Field name="needed_by" label="Needed By" type="date"/></div><Field name="description" label="Description"/>
 <div><div className="flex justify-between mb-2"><h3 className="font-medium">Request items</h3><button type="button" onClick={addItem} className="text-sm underline">Add item</button></div><div className="space-y-2">{items.map((it,i)=><div key={i} className="grid sm:grid-cols-[1fr_180px_90px_70px] gap-2"><input value={it.description} onChange={e=>setItems(a=>a.map((x,j)=>j===i?{...x,description:e.target.value}:x))} placeholder="Item / service" className="border rounded px-2 py-2 text-sm"/><select value={it.supply_id} onChange={e=>{const s=supplies.find(x=>x.id===e.target.value);setItems(a=>a.map((x,j)=>j===i?{...x,supply_id:e.target.value,description:s?.name||x.description,unit:s?.unit||x.unit}:x))}} className="border rounded px-2 py-2 text-sm"><option value="">No stock item</option>{supplies.map(s=><option key={s.id} value={s.id}>{s.item_code} · {s.name} ({s.stock_on_hand})</option>)}</select><input type="number" min="0.001" step="0.001" value={it.quantity} onChange={e=>setItems(a=>a.map((x,j)=>j===i?{...x,quantity:e.target.value}:x))} className="border rounded px-2 py-2 text-sm"/><button type="button" onClick={()=>setItems(a=>a.length===1?a:a.filter((_,j)=>j!==i))} className="text-red-600 text-sm">Remove</button></div>)}</div></div><Submit busy={busy}/></form>}</PopupAction>}</ActionBar>
 <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{['draft','prepared','reviewed','approved','fulfilled'].map(s=><div key={s} className="bg-white rounded-lg border p-4"><div className="text-xs text-slate-500">{label(s)}</div><div className="text-xl font-semibold mt-1">{requests.filter(r=>r.status===s).length}</div></div>)}</div>
 <div className="bg-white rounded-lg border p-4 flex gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search request no., title, requester..." className="border rounded px-3 py-2 text-sm flex-1"/><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded px-3 py-2 text-sm"><option value="all">All statuses</option>{['draft','prepared','reviewed','approved','rejected','fulfilled','cancelled'].map(s=><option key={s}>{s}</option>)}</select></div>
 {error&&<div className="bg-red-50 border border-red-200 text-red-700 rounded p-3 text-sm">{error}</div>}
 <div className="bg-white rounded-lg border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Request</th><th className="p-3 text-left">Requester</th><th className="p-3 text-left">Priority</th><th className="p-3 text-left">Needed by</th><th className="p-3 text-left">Status</th><th className="p-3"></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="p-3"><div className="font-medium">{r.title}</div><div className="text-xs text-slate-500">{r.request_no} · {r.category?.name||'Uncategorized'}</div></td><td className="p-3">{r.requester_employee?.preferred_name||r.requester_employee?.first_name||'—'}</td><td className="p-3"><span className={r.priority==='urgent'?'text-red-700 font-semibold':r.priority==='high'?'text-amber-700':''}>{label(r.priority)}</span></td><td className="p-3">{r.needed_by||'—'}</td><td className="p-3"><span className="px-2 py-1 rounded bg-slate-100 text-xs">{label(r.status)}</span></td><td className="p-3 text-right"><button onClick={()=>{setSelected(r);setModal('view')}} className="px-2 py-1 rounded bg-slate-100 text-xs">View</button></td></tr>)}{filtered.length===0&&<tr><td colSpan={6} className="p-8 text-center text-slate-400">No internal requests found.</td></tr>}</tbody></table></div>
  {modal==='view'&&selected&&<Modal title={`${selected.request_no} · ${selected.title}`} close={()=>setModal(null)}><div className="space-y-4 text-sm"><div className="grid sm:grid-cols-2 gap-3"><Info label="Status" value={label(selected.status)}/><Info label="Priority" value={label(selected.priority)}/><Info label="Requester" value={selected.requester_employee?.preferred_name||selected.requester_employee?.first_name||'—'}/><Info label="Needed by" value={selected.needed_by||'—'}/></div>{selected.description&&<div><div className="text-xs text-slate-500">Description</div><p>{selected.description}</p></div>}<div><div className="font-medium mb-2">Items</div><div className="divide-y border rounded">{selected.items.map(i=><div key={i.id} className="p-2 flex justify-between"><span>{i.item_description}{i.supply_id&&' · stock item'}</span><span>{i.quantity} {i.unit}</span></div>)}</div></div>{selected.rejection_reason&&<div className="bg-red-50 text-red-700 rounded p-3">Reason: {selected.rejection_reason}</div>}<div className="flex flex-wrap gap-2">{can('preparer')&&selected.status==='draft'&&<ActionButton text="Submit for Review" busy={busy} onClick={()=>run(()=>submitInternalRequestAction(fd(selected.id)))}/>} {can('reviewer')&&selected.status==='prepared'&&<><ActionButton text="Review" busy={busy} onClick={()=>run(()=>reviewInternalRequestAction(fd(selected.id,'reviewed')))}/><ActionButton text="Reject Review" busy={busy} onClick={()=>{dialog.prompt('Reason for rejection?').then(reason=>{if(reason)run(()=>reviewInternalRequestAction(fd(selected.id,'rejected',reason)))})}}/></>} {can('approver')&&selected.status==='reviewed'&&<><ActionButton text="Approve" busy={busy} onClick={()=>run(()=>approveInternalRequestAction(fd(selected.id)))}/><ActionButton text="Reject" busy={busy} onClick={()=>{dialog.prompt('Reason for rejection?').then(reason=>{if(reason)run(()=>rejectInternalRequestAction(fd(selected.id,undefined,reason)))})}}/></>} {selected.status==='approved'&&(isSuper||profile.user.role==='admin'||roles.has('preparer'))&&<ActionButton text="Fulfill" busy={busy} onClick={()=>run(()=>fulfillInternalRequestAction(fd(selected.id)))}/>} {selected.requester_user_id===profile.user.id&&['draft','prepared'].includes(selected.status)&&<ActionButton text="Cancel" busy={busy} onClick={()=>run(()=>cancelInternalRequestAction(fd(selected.id)))}/>}</div></div></Modal>}
 </div>
}
function fd(id:string,decision?:string,reason?:string){const f=new FormData();f.set('request_id',id);if(decision)f.set('decision',decision);if(reason)f.set('reason',reason);return f}
function Field({name,label:lab,type='text'}:{name:string;label:string;type?:string}){return <label className="block text-sm space-y-1"><span className="text-slate-600">{lab}</span><input name={name} type={type} className="w-full border rounded px-3 py-2"/></label>}
function Select({name,label:lab,options}:{name:string;label:string;options:string[][]}){return <label className="block text-sm space-y-1"><span className="text-slate-600">{lab}</span><select name={name} className="w-full border rounded px-3 py-2"><option value="">— Select —</option>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
function Info({label:lab,value}:{label:string;value:string}){return <div><div className="text-xs text-slate-500">{lab}</div><div className="font-medium">{value}</div></div>}
function Submit({busy}:{busy:boolean}){return <button disabled={busy} className="w-full bg-slate-900 text-white rounded px-3 py-2 text-sm">{busy?'Saving...':'Create Request'}</button>}
function ActionButton({text,busy,onClick}:{text:string;busy:boolean;onClick:()=>void}){return <button type="button" disabled={busy} onClick={onClick} className="px-3 py-2 rounded bg-slate-900 text-white text-sm disabled:opacity-50">{text}</button>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="bg-white rounded-xl shadow-xl w-full max-w-3xl max-h-[90vh] overflow-auto"><div className="p-4 border-b flex justify-between"><h2 className="font-semibold">{title}</h2><button onClick={close}>✕</button></div><div className="p-4">{children}</div></div></div>}
