'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';
function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
function req(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();if(!v)throw appError(`${k.replaceAll('_',' ')} is required.`);return v}
function opt(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();return v||null}
async function finance(){const p=await getSessionProfile();if(!p?.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.role!=='finance'&&!p.access.some(a=>a.section_code==='finance'))throw appError('Finance access required.');return p}
async function audit(actor:string,id:string,table:string,action:string,detail:Record<string,unknown>){const {error}=await createClient().from('audit_log').insert({actor_id:actor,entity_table:table,entity_id:id,action,detail});if(error)throw appError(error.message)}
export async function createAccountAction(fd:FormData){const p=await finance(),db=createClient();const {data,error}=await db.from('finance_chart_of_accounts').insert({...biz(p),account_code:req(fd,'account_code'),account_name:req(fd,'account_name'),account_type:req(fd,'account_type'),description:opt(fd,'description'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create account.');await audit(p.user.id,data.id,'finance_chart_of_accounts','account_created',{});revalidatePath('/finance/accounting')}
export async function createJournalAction(fd:FormData){const p=await finance(),db=createClient();const {data,error}=await db.from('finance_journal_entries').insert({...biz(p),journal_number:req(fd,'journal_number'),entry_date:req(fd,'entry_date'),description:req(fd,'description'),source_module:opt(fd,'source_module'),source_record_id:opt(fd,'source_record_id'),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create journal.');await audit(p.user.id,data.id,'finance_journal_entries','journal_created',{});revalidatePath('/finance/accounting')}
export async function addJournalLineAction(journalId:string,fd:FormData){const p=await finance(),db=createClient();const debit=Number(fd.get('debit')||0),credit=Number(fd.get('credit')||0);if((debit<=0&&credit<=0)||(debit>0&&credit>0))throw appError('Enter either a debit or credit amount.');const {data,error}=await db.from('finance_journal_lines').insert({...biz(p),journal_entry_id:journalId,account_id:req(fd,'account_id'),line_description:opt(fd,'line_description'),debit,credit,department:opt(fd,'department')}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to add journal line.');await db.rpc('recalculate_finance_journal_totals',{p_journal_id:journalId});await audit(p.user.id,data.id,'finance_journal_lines','journal_line_created',{journal_id:journalId});revalidatePath('/finance/accounting')}
async function transition(id:string,status:string,from:string,actorField:string,action:string){const p=await finance(),db=createClient();const patch:any={status,updated_at:new Date().toISOString()};if(actorField){patch[actorField]=p.user.id;patch[actorField.replace('_by','_at')]=new Date().toISOString()}const {error}=await db.from('finance_journal_entries').update(patch).eq('id',id).eq('status',from);if(error)throw appError(error.message);await audit(p.user.id,id,'finance_journal_entries',action,{});revalidatePath('/finance/accounting');revalidatePath('/approvals')}
export async function prepareJournalAction(id:string){return transition(id,'prepared','draft','prepared_by','prepared')}
export async function reviewJournalAction(id:string,accept:boolean){return transition(id,accept?'reviewed':'draft','prepared','reviewed_by',accept?'reviewed':'returned')}
export async function approveJournalAction(id:string){return transition(id,'approved','reviewed','approved_by','approved')}
export async function postJournalAction(id:string){const p=await finance(),db=createClient();const {error}=await db.rpc('post_finance_journal',{p_journal_id:id,p_actor:p.user.id});if(error)throw appError(error.message);await audit(p.user.id,id,'finance_journal_entries','posted',{});revalidatePath('/finance/accounting');revalidatePath('/dashboard');revalidatePath('/approvals')}
export async function closePeriodAction(id:string){const p=await finance(),db=createClient();const {data,error}=await db.from('finance_accounting_periods').update({status:'closed',closed_by:p.user.id,closed_at:new Date().toISOString()}).eq('id',id).eq('status','open').select('id').single();if(error||!data)throw appError(error?.message||'Unable to close period.');await audit(p.user.id,id,'finance_accounting_periods','period_closed',{});revalidatePath('/finance/accounting')}
