'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';
function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
function req(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();if(!v)throw appError(`${k.replaceAll('_',' ')} is required.`);return v}
function opt(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();return v||null}
async function finance(){const p=await getSessionProfile();if(!p?.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.role!=='finance'&&!p.access.some(a=>a.section_code==='finance'))throw appError('Finance access required.');return p}
async function audit(actor:string,id:string,table:string,action:string,detail:Record<string,unknown>){const {error}=await createClient().from('audit_log').insert({actor_id:actor,entity_table:table,entity_id:id,action,detail});if(error)throw appError(error.message)}
export async function createSupplierInvoiceAction(fd:FormData){const p=await finance(),db=createClient();const lines=JSON.parse(String(fd.get('lines')||'[]')) as Array<{description:string;quantity:number;unit:string;unit_cost:number;purchase_order_item_id?:string}>;if(!lines.length)throw appError('Add at least one invoice line.');
// Build 55: lines linked to PO lines feed the item's purchase price history, so check them here as well as in the DB (guard_invoice_item_po_link): the invoice must name the PO, the linked lines must be on that PO, and the invoice supplier must be the PO's supplier.
if(lines.some(l=>l.purchase_order_item_id)){const poId=opt(fd,'purchase_order_id');if(!poId)throw appError('Select the purchase order these invoice lines belong to.');const {data:po,error:poe}=await db.from('purchase_orders').select('id,supplier_id').eq('id',poId).single();if(poe||!po)throw appError('Purchase order not found.');if(po.supplier_id!==req(fd,'supplier_id'))throw appError('The invoice supplier does not match the purchase order supplier.');const {data:poLines}=await db.from('purchase_order_items').select('id').eq('purchase_order_id',poId);const valid=new Set((poLines??[]).map((x:any)=>x.id));if(lines.some(l=>l.purchase_order_item_id&&!valid.has(l.purchase_order_item_id)))throw appError('An invoice line is linked to a line that is not on the selected purchase order.');}const subtotal=lines.reduce((s,l)=>s+(Number(l.quantity)||0)*(Number(l.unit_cost)||0),0);/* Build 81 (AP-01): a payable can come from the supplier's DR when no SI was given */const siNo=opt(fd,'invoice_number'),drNo=opt(fd,'supplier_dr_number');if(!siNo&&!drNo)throw appError('Enter the supplier SI / invoice no. or the supplier DR no.');const {data,error}=await db.from('finance_supplier_invoices').insert({...biz(p),invoice_number:siNo||`DR ${drNo}`,supplier_dr_number:drNo,supplier_id:req(fd,'supplier_id'),purchase_order_id:opt(fd,'purchase_order_id'),invoice_date:req(fd,'invoice_date'),due_date:opt(fd,'due_date'),subtotal,tax_amount:Number(fd.get('tax_amount')||0),other_charges:Number(fd.get('other_charges')||0),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create supplier invoice.');const {error:le}=await db.from('finance_supplier_invoice_items').insert(lines.map(l=>({...biz(p),invoice_id:data.id,purchase_order_item_id:l.purchase_order_item_id||null,description:l.description,quantity:Number(l.quantity),unit:l.unit||'unit',unit_cost:Number(l.unit_cost)||0})));if(le){await db.from('finance_supplier_invoices').delete().eq('id',data.id);throw appError(le.message)}await audit(p.user.id,data.id,'finance_supplier_invoices','supplier_invoice_created',{subtotal});revalidatePath('/finance/accounts-payable')}
export async function prepareSupplierInvoiceAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_supplier_invoices').update({status:'prepared',prepared_by:p.user.id,prepared_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','draft');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_supplier_invoices','prepared',{});revalidatePath('/finance/accounts-payable');revalidatePath('/approvals')}
export async function reviewSupplierInvoiceAction(id:string,approve:boolean,reason?:string){const p=await finance(),db=createClient();const patch:any={status:approve?'reviewed':'draft',reviewed_by:approve?p.user.id:null,reviewed_at:approve?new Date().toISOString():null,notes:reason?`Returned: ${reason}`:undefined,updated_at:new Date().toISOString()};const {error}=await db.from('finance_supplier_invoices').update(patch).eq('id',id).eq('status','prepared');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_supplier_invoices',approve?'reviewed':'returned',{reason:reason||null});revalidatePath('/finance/accounts-payable');revalidatePath('/approvals')}
export async function approveSupplierInvoiceAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_supplier_invoices').update({status:'approved',approved_by:p.user.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','reviewed');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_supplier_invoices','approved',{});revalidatePath('/finance/accounts-payable');revalidatePath('/approvals')}
export async function createSupplierPaymentAction(fd:FormData){const p=await finance(),db=createClient();const invoiceId=req(fd,'invoice_id');const amount=Number(fd.get('amount')||0);if(amount<=0)throw appError('Payment amount must be greater than zero.');const {data:inv,error:ie}=await db.from('finance_supplier_invoices').select('id,total_amount,amount_paid,status').eq('id',invoiceId).single();if(ie||!inv)throw appError('Invoice not found.');if(['draft','prepared','reviewed','voided'].includes(inv.status))throw appError('Only approved or partially paid invoices can receive payments.');if(amount>Number(inv.total_amount)-Number(inv.amount_paid))throw appError('Payment exceeds invoice balance.');const {data,error}=await db.from('finance_supplier_payments').insert({...biz(p),payment_number:req(fd,'payment_number'),invoice_id:invoiceId,payment_date:req(fd,'payment_date'),amount,payment_method:req(fd,'payment_method'),reference_number:opt(fd,'reference_number'),bank_account:opt(fd,'bank_account'),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create payment.');await audit(p.user.id,data.id,'finance_supplier_payments','supplier_payment_created',{amount,invoice_id:invoiceId});revalidatePath('/finance/accounts-payable')}
export async function prepareSupplierPaymentAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_supplier_payments').update({status:'prepared',prepared_by:p.user.id,prepared_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','draft');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_supplier_payments','prepared',{});revalidatePath('/finance/accounts-payable');revalidatePath('/approvals')}
export async function reviewSupplierPaymentAction(id:string,approve:boolean){const p=await finance(),db=createClient();const {error}=await db.from('finance_supplier_payments').update({status:approve?'reviewed':'draft',reviewed_by:approve?p.user.id:null,reviewed_at:approve?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id).eq('status','prepared');if(error)throw appError(error.message);await audit(p.user.id,id, 'finance_supplier_payments',approve?'reviewed':'returned',{});revalidatePath('/finance/accounts-payable');revalidatePath('/approvals')}
export async function approveSupplierPaymentAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_supplier_payments').update({status:'approved',approved_by:p.user.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','reviewed');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_supplier_payments','approved',{});revalidatePath('/finance/accounts-payable');revalidatePath('/approvals')}
export async function postSupplierPaymentAction(id:string){const p=await finance(),db=createClient();const {data:pay,error:pe}=await db.from('finance_supplier_payments').select('id,invoice_id,amount,status').eq('id',id).single();if(pe||!pay)throw appError('Payment not found.');if(pay.status!=='approved')throw appError('Only approved payments can be posted.');const {data:inv,error:ie}=await db.from('finance_supplier_invoices').select('total_amount,amount_paid').eq('id',pay.invoice_id).single();if(ie||!inv)throw appError('Invoice not found.');if(Number(pay.amount)>Number(inv.total_amount)-Number(inv.amount_paid))throw appError('Payment exceeds invoice balance.');const {error}=await db.from('finance_supplier_payments').update({status:'posted',posted_by:p.user.id,posted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','approved');if(error)throw appError(error.message);const {error:fe}=await db.rpc('recalculate_supplier_invoice_paid',{p_invoice_id:pay.invoice_id});if(fe)throw appError(fe.message);await audit(p.user.id,id,'finance_supplier_payments','posted',{invoice_id:pay.invoice_id,amount:pay.amount});revalidatePath('/finance/accounts-payable');revalidatePath('/finance/procurement')}
