'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';
function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
function req(fd: FormData,key:string){const v=String(fd.get(key)??'').trim();if(!v)throw appError(`${key.replaceAll('_',' ')} is required.`);return v;}
function opt(fd: FormData,key:string){const v=String(fd.get(key)??'').trim();return v||null;}
async function finance(){const p=await getSessionProfile();if(!p?.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.section_code!=='finance'&&!p.access.some(a=>a.section_code==='finance'))throw appError('Finance access required.');return p;}
async function audit(actor:string,id:string,table:string,action:string,detail:Record<string,unknown>){const {error}=await createClient().from('audit_log').insert({actor_id:actor,entity_table:table,entity_id:id,action,detail});if(error)throw appError(error.message);}
export async function createCustomerAction(fd:FormData){const p=await finance(),db=createClient();const {data,error}=await db.from('finance_customers').insert({...biz(p),customer_code:req(fd,'customer_code'),legal_name:req(fd,'legal_name'),trade_name:opt(fd,'trade_name'),contact_person:opt(fd,'contact_person'),email:opt(fd,'email'),phone:opt(fd,'phone'),address:opt(fd,'address'),tax_id:opt(fd,'tax_id'),payment_terms:opt(fd,'payment_terms'),credit_limit:Number(fd.get('credit_limit')||0),notes:opt(fd,'notes'),agent_id:opt(fd,'agent_id'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create customer.');await audit(p.user.id,data.id,'finance_customers','customer_created',{});revalidatePath('/finance/accounts-receivable');}
// Build 81 (AR-01): correct a customer's details (the statement of account reads them live).
export async function updateCustomerAction(fd:FormData){const p=await finance(),db=createClient();const id=req(fd,'customer_id');const credit=Number(fd.get('credit_limit')||0);if(!Number.isFinite(credit)||credit<0)throw appError('Credit limit must be 0 or more.');const {data,error}=await db.from('finance_customers').update({legal_name:req(fd,'legal_name'),trade_name:opt(fd,'trade_name'),contact_person:opt(fd,'contact_person'),email:opt(fd,'email'),phone:opt(fd,'phone'),address:opt(fd,'address'),tax_id:opt(fd,'tax_id'),payment_terms:opt(fd,'payment_terms'),credit_limit:credit,notes:opt(fd,'notes'),...(opt(fd,'agent_id')?{agent_id:opt(fd,'agent_id')}:{}),updated_at:new Date().toISOString()}).eq('id',id).select('id');if(error)throw appError(error.message);if(!data?.length)throw appError('Customer not found, or you cannot edit it.');await audit(p.user.id,id,'finance_customers','customer_updated',{});revalidatePath('/finance/accounts-receivable');}
export async function toggleCustomerAction(id:string,active:boolean){const p=await finance(),db=createClient();const {error}=await db.from('finance_customers').update({active,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'finance_customers',active?'customer_activated':'customer_deactivated',{});revalidatePath('/finance/accounts-receivable');}
export async function createCustomerInvoiceAction(fd:FormData){const p=await finance(),db=createClient();const lines=JSON.parse(String(fd.get('lines')||'[]')) as Array<{description:string;quantity:number;unit:string;unit_price:number;notes?:string}>;if(!lines.length)throw appError('Add at least one invoice line.');const subtotal=lines.reduce((s,l)=>s+(Number(l.quantity)||0)*(Number(l.unit_price)||0),0);const {data,error}=await db.from('finance_customer_invoices').insert({...biz(p),invoice_number:req(fd,'invoice_number'),customer_id:req(fd,'customer_id'),invoice_date:req(fd,'invoice_date'),due_date:opt(fd,'due_date'),currency:opt(fd,'currency')||'PHP',subtotal,tax_amount:Number(fd.get('tax_amount')||0),discount_amount:Number(fd.get('discount_amount')||0),other_charges:Number(fd.get('other_charges')||0),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create customer invoice.');const {error:le}=await db.from('finance_customer_invoice_items').insert(lines.map(l=>({...biz(p),invoice_id:data.id,description:l.description,quantity:Number(l.quantity),unit:l.unit||'unit',unit_price:Number(l.unit_price)||0,notes:l.notes||null})));if(le){await db.from('finance_customer_invoices').delete().eq('id',data.id);throw appError(le.message);}await audit(p.user.id,data.id,'finance_customer_invoices','customer_invoice_created',{subtotal});revalidatePath('/finance/accounts-receivable');}
export async function prepareCustomerInvoiceAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_customer_invoices').update({status:'prepared',prepared_by:p.user.id,prepared_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','draft');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_customer_invoices','prepared',{});revalidatePath('/finance/accounts-receivable');revalidatePath('/approvals');}
export async function reviewCustomerInvoiceAction(id:string,accept:boolean,reason?:string){const p=await finance(),db=createClient();const patch:any={status:accept?'reviewed':'draft',reviewed_by:accept?p.user.id:null,reviewed_at:accept?new Date().toISOString():null,notes:accept?undefined:reason||'Returned by reviewer.',updated_at:new Date().toISOString()};const {error}=await db.from('finance_customer_invoices').update(patch).eq('id',id).eq('status','prepared');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_customer_invoices',accept?'reviewed':'returned',{reason:reason||null});revalidatePath('/finance/accounts-receivable');revalidatePath('/approvals');}
export async function approveCustomerInvoiceAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_customer_invoices').update({status:'approved',approved_by:p.user.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','reviewed');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_customer_invoices','approved',{});revalidatePath('/finance/accounts-receivable');revalidatePath('/approvals');}
export async function createCustomerReceiptAction(fd:FormData){const p=await finance(),db=createClient();const invoiceId=req(fd,'invoice_id');const amount=Number(fd.get('amount')||0);if(amount<=0)throw appError('Receipt amount must be greater than zero.');const {data:inv,error:ie}=await db.from('finance_customer_invoices').select('id,total_amount,amount_received,status').eq('id',invoiceId).single();if(ie||!inv)throw appError('Invoice not found.');if(['draft','prepared','reviewed','voided'].includes(inv.status))throw appError('Only approved or partially paid invoices can receive receipts.');if(amount>Number(inv.total_amount)-Number(inv.amount_received))throw appError('Receipt exceeds invoice balance.');const {data,error}=await db.from('finance_customer_receipts').insert({...biz(p),receipt_number:req(fd,'receipt_number'),invoice_id:invoiceId,receipt_date:req(fd,'receipt_date'),amount,payment_method:req(fd,'payment_method'),reference_number:opt(fd,'reference_number'),bank_account:opt(fd,'bank_account'),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create receipt.');await audit(p.user.id,data.id,'finance_customer_receipts','customer_receipt_created',{invoice_id:invoiceId,amount});revalidatePath('/finance/accounts-receivable');}
export async function prepareCustomerReceiptAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_customer_receipts').update({status:'prepared',prepared_by:p.user.id,prepared_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','draft');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_customer_receipts','prepared',{});revalidatePath('/finance/accounts-receivable');revalidatePath('/approvals');}
export async function reviewCustomerReceiptAction(id:string,accept:boolean){const p=await finance(),db=createClient();const {error}=await db.from('finance_customer_receipts').update({status:accept?'reviewed':'draft',reviewed_by:accept?p.user.id:null,reviewed_at:accept?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id).eq('status','prepared');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_customer_receipts',accept?'reviewed':'returned',{});revalidatePath('/finance/accounts-receivable');revalidatePath('/approvals');}
export async function approveCustomerReceiptAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_customer_receipts').update({status:'approved',approved_by:p.user.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','reviewed');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_customer_receipts','approved',{});revalidatePath('/finance/accounts-receivable');revalidatePath('/approvals');}
export async function postCustomerReceiptAction(id:string){const p=await finance(),db=createClient();const {data:rec,error:re}=await db.from('finance_customer_receipts').select('id,invoice_id,amount,status').eq('id',id).single();if(re||!rec)throw appError('Receipt not found.');if(rec.status!=='approved')throw appError('Only approved receipts can be posted.');const {data:inv,error:ie}=await db.from('finance_customer_invoices').select('total_amount,amount_received').eq('id',rec.invoice_id).single();if(ie||!inv)throw appError('Invoice not found.');if(Number(rec.amount)>Number(inv.total_amount)-Number(inv.amount_received))throw appError('Receipt exceeds invoice balance.');const {error}=await db.from('finance_customer_receipts').update({status:'posted',posted_by:p.user.id,posted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','approved');if(error)throw appError(error.message);const {error:fe}=await db.rpc('recalculate_customer_invoice_received',{p_invoice_id:rec.invoice_id});if(fe)throw appError(fe.message);await audit(p.user.id,id,'finance_customer_receipts','posted',{invoice_id:rec.invoice_id,amount:rec.amount});revalidatePath('/finance/accounts-receivable');revalidatePath('/dashboard');}
