'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';
function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
function req(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();if(!v)throw appError(`${k.replaceAll('_',' ')} is required.`);return v}
function opt(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();return v||null}
async function finance(){const p=await getSessionProfile();if(!p?.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.role!=='finance'&&!p.access.some(a=>a.section_code==='finance'))throw appError('Finance access required.');return p}
async function audit(actor:string,id:string,table:string,action:string,detail:Record<string,unknown>){const {error}=await createClient().from('audit_log').insert({actor_id:actor,entity_table:table,entity_id:id,action,detail});if(error)throw appError(error.message)}
export async function createBankAccountAction(fd:FormData){const p=await finance(),db=createClient();const {data,error}=await db.from('finance_bank_accounts').insert({...biz(p),account_code:req(fd,'account_code'),account_name:req(fd,'account_name'),bank_name:opt(fd,'bank_name'),account_number_masked:opt(fd,'account_number_masked'),account_type:req(fd,'account_type'),currency:opt(fd,'currency')||'PHP',opening_balance:Number(fd.get('opening_balance')||0),current_balance:Number(fd.get('opening_balance')||0),is_cash_on_hand:fd.get('is_cash_on_hand')==='on',notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create bank account.');await audit(p.user.id,data.id,'finance_bank_accounts','bank_account_created',{});revalidatePath('/finance/bank-cash')}
export async function toggleBankAccountAction(id:string,active:boolean){const p=await finance(),db=createClient();const {error}=await db.from('finance_bank_accounts').update({status:active?'active':'inactive'}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'finance_bank_accounts',active?'bank_account_activated':'bank_account_deactivated',{});revalidatePath('/finance/bank-cash')}
export async function createCashTransactionAction(fd:FormData){const p=await finance(),db=createClient();const type=req(fd,'transaction_type') as string;const direction=['deposit','transfer_in','interest'].includes(type)?'in':'out';const amount=Number(fd.get('amount')||0);if(amount<=0)throw appError('Amount must be greater than zero.');const {data,error}=await db.from('finance_cash_transactions').insert({...biz(p),transaction_number:req(fd,'transaction_number'),bank_account_id:req(fd,'bank_account_id'),transaction_date:req(fd,'transaction_date'),transaction_type:type,amount,direction,description:req(fd,'description'),reference_number:opt(fd,'reference_number'),counterparty:opt(fd,'counterparty'),source_module:opt(fd,'source_module'),source_record_id:opt(fd,'source_record_id'),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create cash transaction.');await audit(p.user.id,data.id,'finance_cash_transactions','cash_transaction_created',{amount,direction});revalidatePath('/finance/bank-cash')}
export async function prepareCashTransactionAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_cash_transactions').update({status:'prepared',prepared_by:p.user.id,prepared_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','draft');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_cash_transactions','prepared',{});revalidatePath('/finance/bank-cash');revalidatePath('/approvals')}
export async function reviewCashTransactionAction(id:string,accept:boolean){const p=await finance(),db=createClient();const {error}=await db.from('finance_cash_transactions').update({status:accept?'reviewed':'draft',reviewed_by:accept?p.user.id:null,reviewed_at:accept?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id).eq('status','prepared');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_cash_transactions',accept?'reviewed':'returned',{});revalidatePath('/finance/bank-cash');revalidatePath('/approvals')}
export async function approveCashTransactionAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_cash_transactions').update({status:'approved',approved_by:p.user.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','reviewed');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_cash_transactions','approved',{});revalidatePath('/finance/bank-cash');revalidatePath('/approvals')}
export async function postCashTransactionAction(id:string){const p=await finance(),db=createClient();const {data:t,error:te}=await db.from('finance_cash_transactions').select('id,bank_account_id,amount,direction,status').eq('id',id).single();if(te||!t)throw appError('Transaction not found.');if(t.status!=='approved')throw appError('Only approved transactions can be posted.');const {error}=await db.from('finance_cash_transactions').update({status:'posted',posted_by:p.user.id,posted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','approved');if(error)throw appError(error.message);const {error:be}=await db.rpc('recalculate_finance_bank_balance',{p_bank_account_id:t.bank_account_id});if(be)throw appError(be.message);await audit(p.user.id,id,'finance_cash_transactions','posted',{amount:t.amount,direction:t.direction});revalidatePath('/finance/bank-cash');revalidatePath('/dashboard')}
// U057 Check Register: a check is a finance_cash_transactions row with
// transaction_type='check', direction='out' (checks are always disbursements
// -- there is no "incoming check" concept modeled here), plus the
// check-specific check_number/payee fields. Reuses the exact same
// draft->prepared->reviewed->approved->posted workflow already built for
// every other cash transaction (prepareCashTransactionAction etc. above
// work on these rows unmodified since transaction_type isn't part of their
// status-transition logic).
export async function createCheckTransactionAction(fd:FormData){const p=await finance(),db=createClient();const amount=Number(fd.get('amount')||0);if(amount<=0)throw appError('Amount must be greater than zero.');const checkNumber=req(fd,'check_number');const {data,error}=await db.from('finance_cash_transactions').insert({...biz(p),transaction_number:req(fd,'transaction_number'),bank_account_id:req(fd,'bank_account_id'),transaction_date:req(fd,'transaction_date'),transaction_type:'check',amount,direction:'out',check_number:checkNumber,payee:req(fd,'payee'),description:opt(fd,'description')||`Check ${checkNumber}`,reference_number:opt(fd,'reference_number'),counterparty:opt(fd,'payee'),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create check.');await audit(p.user.id,data.id,'finance_cash_transactions','check_created',{amount,check_number:checkNumber});revalidatePath('/finance/bank-cash')}
export async function voidCheckAction(id:string,reason?:string){const p=await finance(),db=createClient();const {data:t,error:te}=await db.from('finance_cash_transactions').select('id,transaction_type,status').eq('id',id).single();if(te||!t)throw appError('Check not found.');if(t.transaction_type!=='check')throw appError('Not a check transaction.');if(t.status==='voided')throw appError('Check is already voided.');if(t.status==='posted')throw appError('A posted check cannot be voided directly -- reverse it with an offsetting transaction instead.');const {error}=await db.from('finance_cash_transactions').update({status:'voided',notes:reason?`Voided: ${reason}`:'Voided',updated_at:new Date().toISOString()}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'finance_cash_transactions','check_voided',{reason:reason||null});revalidatePath('/finance/bank-cash')}
export async function createReconciliationAction(fd:FormData){const p=await finance(),db=createClient();const bankId=req(fd,'bank_account_id');const statementDate=req(fd,'statement_date');const closing=Number(fd.get('statement_closing_balance')||0);const {data,error}=await db.from('finance_bank_reconciliations').insert({...biz(p),bank_account_id:bankId,statement_date:statementDate,statement_opening_balance:Number(fd.get('statement_opening_balance')||0),statement_closing_balance:closing,notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create reconciliation.');await db.rpc('recalculate_finance_reconciliation',{p_reconciliation_id:data.id});await audit(p.user.id,data.id,'finance_bank_reconciliations','reconciliation_created',{statementDate});revalidatePath('/finance/bank-cash')}
export async function matchReconciliationItemAction(id:string,status:'matched'|'unmatched'|'excluded'){const p=await finance(),db=createClient();const {error}=await db.from('finance_bank_reconciliation_items').update({status}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'finance_bank_reconciliation_items',`item_${status}`,{});revalidatePath('/finance/bank-cash')}
export async function completeReconciliationAction(id:string){const p=await finance(),db=createClient();await db.rpc('recalculate_finance_reconciliation',{p_reconciliation_id:id});const {data:r,error:re}=await db.from('finance_bank_reconciliations').select('difference,status').eq('id',id).single();if(re||!r)throw appError(re?.message||'Reconciliation not found.');if(r.status==='locked')throw appError('Reconciliation is locked.');if(Math.abs(Number(r.difference))>0.009)throw appError('Reconciliation cannot be completed while a difference remains.');const {error}=await db.from('finance_bank_reconciliations').update({status:'completed',completed_by:p.user.id,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'finance_bank_reconciliations','reconciliation_completed',{});revalidatePath('/finance/bank-cash')}
export async function lockReconciliationAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_bank_reconciliations').update({status:'locked',updated_at:new Date().toISOString()}).eq('id',id).eq('status','completed');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_bank_reconciliations','reconciliation_locked',{});revalidatePath('/finance/bank-cash')}
