'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';
function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
function req(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();if(!v)throw appError(`${k.replaceAll('_',' ')} is required.`);return v}
function opt(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();return v||null}
async function finance(){const p=await getSessionProfile();if(!p?.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.role!=='finance'&&!p.access.some(a=>a.section_code==='finance'))throw appError('Finance access required.');return p}
async function audit(actor:string,id:string,table:string,action:string,detail:Record<string,unknown>){const {error}=await createClient().from('audit_log').insert({actor_id:actor,entity_table:table,entity_id:id,action,detail});if(error)throw appError(error.message)}
const months=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
export async function createBudgetAction(fd:FormData){const p=await finance(),db=createClient();const {data,error}=await db.from('finance_budgets').insert({...biz(p),budget_code:req(fd,'budget_code'),name:req(fd,'name'),fiscal_year:Number(req(fd,'fiscal_year')),scenario:req(fd,'scenario')||'budget',version:Number(fd.get('version')||1),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create budget.');await audit(p.user.id,data.id,'finance_budgets','budget_created',{});revalidatePath('/finance/budgets')}
export async function addBudgetLineAction(budgetId:string,fd:FormData){const p=await finance(),db=createClient();const row:any={...biz(p),budget_id:budgetId,line_code:req(fd,'line_code'),account_name:req(fd,'account_name'),department:opt(fd,'department'),category:opt(fd,'category'),notes:opt(fd,'notes')};for(const m of months){row[`${m}_budget`]=Number(fd.get(`${m}_budget`)||0);row[`${m}_forecast`]=Number(fd.get(`${m}_forecast`)||0)}const {data,error}=await db.from('finance_budget_lines').insert(row).select('id').single();if(error||!data)throw appError(error?.message||'Unable to add budget line.');await db.rpc('recalculate_finance_budget_totals',{p_budget_id:budgetId});await audit(p.user.id,data.id,'finance_budget_lines','budget_line_created',{budget_id:budgetId});revalidatePath('/finance/budgets')}
export async function updateBudgetLineAction(id:string,fd:FormData){const p=await finance(),db=createClient();const row:any={account_name:req(fd,'account_name'),department:opt(fd,'department'),category:opt(fd,'category'),notes:opt(fd,'notes'),updated_at:new Date().toISOString()};for(const m of months){row[`${m}_budget`]=Number(fd.get(`${m}_budget`)||0);row[`${m}_forecast`]=Number(fd.get(`${m}_forecast`)||0)}const {data,error}=await db.from('finance_budget_lines').update(row).eq('id',id).select('budget_id').single();if(error||!data)throw appError(error?.message||'Unable to update budget line.');await db.rpc('recalculate_finance_budget_totals',{p_budget_id:data.budget_id});await audit(p.user.id,id,'finance_budget_lines','budget_line_updated',{});revalidatePath('/finance/budgets')}
export async function deleteBudgetLineAction(id:string){const p=await finance(),db=createClient();const {data}=await db.from('finance_budget_lines').select('budget_id').eq('id',id).single();if(!data)throw appError('Budget line not found.');const {error}=await db.from('finance_budget_lines').delete().eq('id',id);if(error)throw appError(error.message);await db.rpc('recalculate_finance_budget_totals',{p_budget_id:data.budget_id});await audit(p.user.id,id,'finance_budget_lines','budget_line_deleted',{});revalidatePath('/finance/budgets')}
export async function prepareBudgetAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_budgets').update({status:'prepared',prepared_by:p.user.id,prepared_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','draft');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_budgets','prepared',{});revalidatePath('/finance/budgets');revalidatePath('/approvals')}
export async function reviewBudgetAction(id:string,accept:boolean){const p=await finance(),db=createClient();const {error}=await db.from('finance_budgets').update({status:accept?'reviewed':'draft',reviewed_by:accept?p.user.id:null,reviewed_at:accept?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id).eq('status','prepared');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_budgets',accept?'reviewed':'returned',{});revalidatePath('/finance/budgets');revalidatePath('/approvals')}
export async function approveBudgetAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_budgets').update({status:'approved',approved_by:p.user.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','reviewed');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_budgets','approved',{});revalidatePath('/finance/budgets');revalidatePath('/approvals')}
export async function closeBudgetAction(id:string){const p=await finance(),db=createClient();const {error}=await db.from('finance_budgets').update({status:'closed',closed_by:p.user.id,closed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','approved');if(error)throw appError(error.message);await audit(p.user.id,id,'finance_budgets','closed',{});revalidatePath('/finance/budgets')}
export async function saveActualAction(lineId:string,year:number,month:number,amount:number,sourceModule?:string){const p=await finance(),db=createClient();if(month<1||month>12)throw appError('Invalid month.');const {data:line}=await db.from('finance_budget_lines').select('budget_id').eq('id',lineId).single();if(!line)throw appError('Budget line not found.');const {error}=await db.from('finance_budget_actuals').upsert({budget_line_id:lineId,fiscal_year:year,month,actual_amount:amount,source_module:sourceModule||null,recorded_by:p.user.id,updated_at:new Date().toISOString()},{onConflict:'budget_line_id,month'});if(error)throw appError(error.message);await audit(p.user.id,lineId,'finance_budget_actuals','actual_saved',{year,month,amount});revalidatePath('/finance/budgets')}
