'use server';
import { appError } from '@/core/errors/appError';
import {revalidatePath} from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import {getSessionProfile} from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';
function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
const req=(fd:FormData,k:string)=>{const v=String(fd.get(k)??'').trim();if(!v)throw appError(`${k.replaceAll('_',' ')} is required.`);return v};
const opt=(fd:FormData,k:string)=>{const v=String(fd.get(k)??'').trim();return v||null};
async function logistics(){const p=await getSessionProfile();if(!p?.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.role!=='logistics'&&!p.access.some(a=>a.section_code==='logistics'))throw appError('Logistics access required.');return p}
async function audit(actor:string,id:string,table:string,action:string,detail:Record<string,unknown>={}){const {error}=await createClient().from('audit_log').insert({actor_id:actor,entity_table:table,entity_id:id,action,detail});if(error)throw appError(error.message)}
export async function createDeliveryOrderAction(fd:FormData){const p=await logistics(),db=createClient();const lines=JSON.parse(String(fd.get('lines')||'[]')) as any[];if(!lines.length)throw appError('At least one delivery line is required.');const {data,error}=await db.from('logistics_delivery_orders').insert({...biz(p),delivery_number:req(fd,'delivery_number'),customer_id:opt(fd,'customer_id'),source_location_id:req(fd,'source_location_id'),delivery_date:req(fd,'delivery_date'),requested_delivery_date:opt(fd,'requested_delivery_date'),delivery_address:opt(fd,'delivery_address'),contact_name:opt(fd,'contact_name'),contact_phone:opt(fd,'contact_phone'),sales_reference:opt(fd,'sales_reference'),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create delivery order.');const {error:le}=await db.from('logistics_delivery_order_items').insert(lines.map(l=>({...biz(p),delivery_order_id:data.id,inventory_item_id:l.inventory_item_id,quantity:Number(l.quantity),unit_price:Number(l.unit_price||0),notes:l.notes||null})));if(le){await db.from('logistics_delivery_orders').delete().eq('id',data.id);throw appError(le.message)}await audit(p.user.id,data.id,'logistics_delivery_orders','delivery_order_created');revalidatePath('/logistics/warehouse-delivery')}
async function transition(id:string,status:string,from:string,actorField?:string,action= status){const p=await logistics(),db=createClient();const patch:any={status,updated_at:new Date().toISOString()};if(actorField){patch[actorField]=p.user.id;patch[actorField.replace('_by','_at')]=new Date().toISOString()}const {error}=await db.from('logistics_delivery_orders').update(patch).eq('id',id).eq('status',from);if(error)throw appError(error.message);await audit(p.user.id,id,'logistics_delivery_orders',action);revalidatePath('/logistics/warehouse-delivery');revalidatePath('/approvals')}
export async function prepareDeliveryOrderAction(id:string){return transition(id,'prepared','draft','prepared_by','prepared');}
export async function pickDeliveryOrderAction(id:string){return transition(id,'picked','prepared',undefined,'picked');}
export async function packDeliveryOrderAction(id:string){return transition(id,'packed','picked',undefined,'packed');}
export async function reviewDeliveryOrderAction(id:string,accept:boolean){return transition(id,accept?'reviewed':'draft','packed','reviewed_by',accept?'reviewed':'returned');}
export async function approveDeliveryOrderAction(id:string){return transition(id,'approved','reviewed','approved_by','approved');}
export async function createDispatchAction(fd:FormData){const p=await logistics(),db=createClient();const orderId=req(fd,'delivery_order_id');const {data:o,error:oe}=await db.from('logistics_delivery_orders').select('id,status').eq('id',orderId).single();if(oe||!o||o.status!=='approved')throw appError('Only approved delivery orders can be dispatched.');const {data,error}=await db.from('logistics_dispatches').insert({...biz(p),dispatch_number:req(fd,'dispatch_number'),delivery_order_id:orderId,vehicle_id:opt(fd,'vehicle_id'),driver_id:opt(fd,'driver_id'),dispatch_date:req(fd,'dispatch_date'),expected_arrival:opt(fd,'expected_arrival'),recipient_name:opt(fd,'recipient_name'),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create dispatch.');await audit(p.user.id,data.id,'logistics_dispatches','dispatch_created');revalidatePath('/logistics/warehouse-delivery')}
export async function markDispatchInTransitAction(id:string){const p=await logistics(),db=createClient();const {data:d,error}=await db.from('logistics_dispatches').select('id,delivery_order_id,delivery_status').eq('id',id).single();if(error||!d)throw appError('Dispatch not found.');if(d.delivery_status!=='planned'&&d.delivery_status!=='loaded')throw appError('Dispatch is not ready for transit.');const now=new Date().toISOString();await db.from('logistics_dispatches').update({delivery_status:'in_transit',departure_time:now,updated_at:now}).eq('id',id);await db.from('logistics_delivery_orders').update({status:'dispatched',dispatched_at:now,updated_at:now}).eq('id',d.delivery_order_id).eq('status','approved');await audit(p.user.id,id,'logistics_dispatches','dispatch_in_transit');revalidatePath('/logistics/warehouse-delivery')}
export async function completeDeliveryAction(id:string,fd:FormData){const p=await logistics(),db=createClient();const {data:d,error}=await db.from('logistics_dispatches').select('id,delivery_order_id,delivery_status').eq('id',id).single();if(error||!d)throw appError('Dispatch not found.');if(d.delivery_status!=='in_transit')throw appError('Dispatch must be in transit.');const now=new Date().toISOString();const {error:de}=await db.from('logistics_dispatches').update({delivery_status:'delivered',actual_arrival:now,proof_of_delivery_reference:opt(fd,'proof_of_delivery_reference'),recipient_name:opt(fd,'recipient_name')||undefined,updated_at:now}).eq('id',id);if(de)throw appError(de.message);await db.from('logistics_delivery_orders').update({status:'delivered',delivered_at:now,updated_at:now}).eq('id',d.delivery_order_id).eq('status','dispatched');const {data:lines}=await db.from('logistics_delivery_order_items').select('*').eq('delivery_order_id',d.delivery_order_id);for(const line of lines??[]){const {error:me}=await db.from('logistics_stock_movements').insert({...biz(p),movement_number:`ISS-${String(d.delivery_order_id).slice(0,8)}-${String(line.id).slice(0,8)}`,inventory_item_id:line.inventory_item_id,location_id:(await db.from('logistics_delivery_orders').select('source_location_id').eq('id',d.delivery_order_id).single()).data?.source_location_id,movement_date:new Date().toISOString().slice(0,10),movement_type:'issue',quantity:line.quantity,unit_cost:0,source_table:'logistics_delivery_orders',source_record_id:d.delivery_order_id,reference_number:(await db.from('logistics_delivery_orders').select('delivery_number').eq('id',d.delivery_order_id).single()).data?.delivery_number,created_by:p.user.id});if(me)throw appError(me.message)}await audit(p.user.id,id,'logistics_dispatches','delivery_completed');revalidatePath('/logistics/warehouse-delivery');revalidatePath('/logistics/inventory');revalidatePath('/finance/accounting')}
