'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';
function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
const VEHICLE_STATUSES=['available','assigned','in_use','maintenance','out_of_service','retired','disposed'];
const CONDITIONS=['new','good','fair','needs_repair','damaged'];
const TRIP_STATUSES=['planned','started','completed','cancelled'];
const EXPENSE_TYPES=['fuel','toll','parking','maintenance','repair','registration','insurance','other'];
function req(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();if(!v)throw appError(`${k.replaceAll('_',' ')} is required.`);return v}
function opt(fd:FormData,k:string){const v=String(fd.get(k)??'').trim();return v||null}
function en(v:string,a:string[],label:string){if(!a.includes(v))throw appError(`Invalid ${label}.`)}
async function admin(){const p=await getSessionProfile();if(!p||!p.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.section_code!=='admin'&&!p.access.some(a=>a.section_code==='admin'))throw appError('Admin access required.');return p}
// U009 — mirrors the employees/actions.ts check: existing has_workflow_role
// primitive only, no new role vocabulary.
function isAdminApprover(p:Awaited<ReturnType<typeof getSessionProfile>>){if(!p)return false;if(isAdminTier(p))return true;return p.access.some(a=>a.section_code==='admin'&&a.workflow_role==='approver')}
async function audit(actor:string,id:string,action:string,detail:Record<string,unknown>){const {error}=await createClient().from('audit_log').insert({actor_id:actor,entity_table:'fleet',entity_id:id,action,detail});if(error)throw appError(error.message)}
export async function createVehicleAction(fd:FormData){const p=await admin(),db=createClient();const status='available';const condition=(opt(fd,'condition')||'good');en(condition,CONDITIONS,'condition');const payload={...biz(p),vehicle_no:req(fd,'vehicle_no').toUpperCase(),plate_no:opt(fd,'plate_no')?.toUpperCase(),vehicle_type:req(fd,'vehicle_type'),make:opt(fd,'make'),model:opt(fd,'model'),year:opt(fd,'year')?Number(opt(fd,'year')):null,color:opt(fd,'color'),vin:opt(fd,'vin'),engine_no:opt(fd,'engine_no'),purchase_date:opt(fd,'purchase_date'),purchase_cost:opt(fd,'purchase_cost')?Number(opt(fd,'purchase_cost')):null,supplier:opt(fd,'supplier'),registration_expiry:opt(fd,'registration_expiry'),insurance_expiry:opt(fd,'insurance_expiry'),odometer:opt(fd,'odometer')?Number(opt(fd,'odometer')):0,capacity:opt(fd,'capacity'),location:opt(fd,'location'),condition,status,notes:opt(fd,'notes'),created_by:p.user.id};const {data,error}=await db.from('fleet_vehicles').insert(payload).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create vehicle.');await audit(p.user.id,data.id,'vehicle_created',{vehicle_no:payload.vehicle_no});revalidatePath('/admin/fleet');return {ok:true}}
export async function updateVehicleAction(fd:FormData){const p=await admin(),db=createClient(),id=req(fd,'vehicle_id'),status=req(fd,'status'),condition=req(fd,'condition');en(status,VEHICLE_STATUSES,'status');en(condition,CONDITIONS,'condition');if(status==='assigned'||status==='in_use')throw appError('Use fleet assignment/trip actions for active vehicle use.');const {data:active}=await db.from('fleet_assignments').select('id').eq('vehicle_id',id).is('returned_at',null).maybeSingle();if(active&&['available','maintenance','out_of_service','retired','disposed'].includes(status))throw appError('Return the active assignment before changing this vehicle to an inactive-use status.');const {error}=await db.from('fleet_vehicles').update({vehicle_no:req(fd,'vehicle_no').toUpperCase(),plate_no:opt(fd,'plate_no')?.toUpperCase(),vehicle_type:req(fd,'vehicle_type'),make:opt(fd,'make'),model:opt(fd,'model'),year:opt(fd,'year')?Number(opt(fd,'year')):null,color:opt(fd,'color'),vin:opt(fd,'vin'),engine_no:opt(fd,'engine_no'),purchase_date:opt(fd,'purchase_date'),purchase_cost:opt(fd,'purchase_cost')?Number(opt(fd,'purchase_cost')):null,supplier:opt(fd,'supplier'),registration_expiry:opt(fd,'registration_expiry'),insurance_expiry:opt(fd,'insurance_expiry'),odometer:opt(fd,'odometer')?Number(opt(fd,'odometer')):0,capacity:opt(fd,'capacity'),location:opt(fd,'location'),condition,status,notes:opt(fd,'notes')}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'vehicle_edited',{status,condition});revalidatePath('/admin/fleet');return {ok:true}}
export async function registerDriverAction(fd:FormData){const p=await admin(),db=createClient(),employeeId=req(fd,'employee_id');const emp=await db.from('employees').select('id,employment_status').eq('id',employeeId).maybeSingle();if(!emp.data||emp.data.employment_status==='separated')throw appError('Employee is not eligible.');const payload:Record<string,unknown>={...biz(p),employee_id:employeeId,license_expiry:opt(fd,'license_expiry'),license_type:opt(fd,'license_type'),authorized:fd.get('authorized')==='on',notes:opt(fd,'notes'),created_by:p.user.id};if(isAdminApprover(p))payload.license_no=opt(fd,'license_no');const {data,error}=await db.from('fleet_drivers').insert(payload).select('id').single();if(error||!data)throw appError(error?.message||'Unable to register driver.');await audit(p.user.id,data.id,'driver_registered',{employee_id:employeeId});revalidatePath('/admin/fleet');return {ok:true}}
export async function assignVehicleAction(fd:FormData){const p=await admin(),db=createClient(),vehicleId=req(fd,'vehicle_id'),employeeId=req(fd,'employee_id');const {data:v}=await db.from('fleet_vehicles').select('id,status').eq('id',vehicleId).maybeSingle();if(!v||v.status!=='available')throw appError('Only available vehicles can be assigned.');const {data:d}=await db.from('fleet_drivers').select('id,authorized,license_expiry').eq('employee_id',employeeId).maybeSingle();if(!d||!d.authorized)throw appError('Employee is not an authorized fleet driver.');if(d.license_expiry&&d.license_expiry<new Date().toISOString().slice(0,10))throw appError('Driver license is expired.');const {data,error}=await db.from('fleet_assignments').insert({...biz(p),vehicle_id:vehicleId,employee_id:employeeId,purpose:opt(fd,'purpose'),location:opt(fd,'location'),notes:opt(fd,'notes'),assigned_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to assign vehicle.');await db.from('fleet_vehicles').update({status:'assigned'}).eq('id',vehicleId);await audit(p.user.id,vehicleId,'vehicle_assigned',{employee_id:employeeId,assignment_id:data.id});revalidatePath('/admin/fleet');return {ok:true}}
export async function returnVehicleAction(fd:FormData){const p=await admin(),db=createClient(),vehicleId=req(fd,'vehicle_id');const {data:a}=await db.from('fleet_assignments').select('id,employee_id').eq('vehicle_id',vehicleId).is('returned_at',null).maybeSingle();if(!a)throw appError('No active vehicle assignment found.');const {error}=await db.from('fleet_assignments').update({returned_at:new Date().toISOString(),returned_by:p.user.id,notes:opt(fd,'notes')}).eq('id',a.id);if(error)throw appError(error.message);const {error:ve}=await db.from('fleet_vehicles').update({status:'available',location:opt(fd,'location')}).eq('id',vehicleId);if(ve)throw appError(ve.message);await audit(p.user.id,vehicleId,'vehicle_returned',{employee_id:a.employee_id,assignment_id:a.id});revalidatePath('/admin/fleet');return {ok:true}}
export async function createTripAction(fd:FormData){const p=await admin(),db=createClient();const vehicleId=req(fd,'vehicle_id'),driverId=opt(fd,'driver_employee_id');const tripNo=req(fd,'trip_no').toUpperCase();const {data:v}=await db.from('fleet_vehicles').select('id,status,odometer').eq('id',vehicleId).maybeSingle();if(!v)throw appError('Vehicle not found.');if(['maintenance','out_of_service','retired','disposed'].includes(v.status))throw appError('Vehicle is not available for a trip.');if(driverId){const {data:d}=await db.from('fleet_drivers').select('authorized,license_expiry').eq('employee_id',driverId).maybeSingle();if(!d?.authorized)throw appError('Driver is not authorized.');if(d.license_expiry&&d.license_expiry<new Date().toISOString().slice(0,10))throw appError('Driver license is expired.');}const {data,error}=await db.from('fleet_trips').insert({...biz(p),trip_no:tripNo,vehicle_id:vehicleId,driver_employee_id:driverId,trip_date:req(fd,'trip_date'),departure_at:opt(fd,'departure_at'),origin:opt(fd,'origin'),destination:opt(fd,'destination'),purpose:req(fd,'purpose'),starting_odometer:opt(fd,'starting_odometer')?Number(opt(fd,'starting_odometer')):v.odometer,status:'planned',notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create trip.');await audit(p.user.id,data.id,'trip_created',{trip_no:tripNo});revalidatePath('/admin/fleet');return {ok:true}}
export async function updateTripStatusAction(fd:FormData){const p=await admin(),db=createClient(),id=req(fd,'trip_id'),status=req(fd,'status');en(status,TRIP_STATUSES,'trip status');const {data:trip}=await db.from('fleet_trips').select('vehicle_id,starting_odometer').eq('id',id).maybeSingle();if(!trip)throw appError('Trip not found.');const payload:any={status};if(status==='started')payload.departure_at=new Date().toISOString();if(status==='completed'){payload.return_at=new Date().toISOString();const end=opt(fd,'ending_odometer');if(end===null)throw appError('Ending odometer is required when completing a trip.');payload.ending_odometer=Number(end);const {error:ve}=await db.from('fleet_vehicles').update({odometer:Number(end),status:'available'}).eq('id',trip.vehicle_id);if(ve)throw appError(ve.message)}if(status==='started'){await db.from('fleet_vehicles').update({status:'in_use'}).eq('id',trip.vehicle_id)}if(status==='cancelled'){await db.from('fleet_vehicles').update({status:'available'}).eq('id',trip.vehicle_id)}const {error}=await db.from('fleet_trips').update(payload).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'trip_status_changed',{status});revalidatePath('/admin/fleet');return {ok:true}}
export async function createFleetExpenseAction(fd:FormData){const p=await admin(),db=createClient(),amount=Number(req(fd,'amount'));if(!(amount>0))throw appError('Amount must be greater than zero.');const type=req(fd,'expense_type');en(type,EXPENSE_TYPES,'expense type');const {data,error}=await db.from('fleet_expenses').insert({...biz(p),vehicle_id:req(fd,'vehicle_id'),trip_id:opt(fd,'trip_id'),expense_date:req(fd,'expense_date'),expense_type:type,description:req(fd,'description'),amount,vendor:opt(fd,'vendor'),receipt_reference:opt(fd,'receipt_reference'),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create fleet expense.');await audit(p.user.id,data.id,'fleet_expense_created',{amount,type});revalidatePath('/admin/fleet');return {ok:true}}
export async function createMaintenanceAction(fd:FormData){const p=await admin(),db=createClient(),cost=opt(fd,'cost');const {data,error}=await db.from('fleet_maintenance').insert({...biz(p),vehicle_id:req(fd,'vehicle_id'),request_id:opt(fd,'request_id'),service_date:req(fd,'service_date'),service_type:req(fd,'service_type'),description:req(fd,'description'),odometer:opt(fd,'odometer')?Number(opt(fd,'odometer')):null,vendor:opt(fd,'vendor'),cost:cost?Number(cost):null,next_service_date:opt(fd,'next_service_date'),next_service_odometer:opt(fd,'next_service_odometer')?Number(opt(fd,'next_service_odometer')):null,status:'completed',notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create maintenance record.');await db.from('fleet_vehicles').update({status:'available',odometer:opt(fd,'odometer')?Number(opt(fd,'odometer')):undefined}).eq('id',req(fd,'vehicle_id'));const requestId=opt(fd,'request_id');if(requestId){const {error:re}=await db.from('internal_requests').update({status:'fulfilled',fulfilled_by:p.user.id,fulfilled_at:new Date().toISOString()}).eq('id',requestId).eq('status','approved');if(re)throw appError(re.message);}await audit(p.user.id,data.id,'maintenance_recorded',{vehicle_id:req(fd,'vehicle_id'),request_id:requestId});revalidatePath('/admin/fleet');revalidatePath('/admin/requests');return {ok:true}}

// U036 — Fleet Maintenance Request Integration. Rather than a second,
// parallel request/approval table, this reuses the existing generic
// internal_requests draft/prepared/reviewed/approved/rejected/fulfilled
// engine (the same "one authoritative mechanism" principle already
// applied to PR-10/PR-11/PO-11 in Build 44): any signed-in active user —
// not just admin-section staff, so a driver can actually flag an issue —
// may file a vehicle-maintenance request, which then goes through the
// exact same review/approval chain every other internal request does.
// `createMaintenanceAction` above closes the loop by marking the request
// fulfilled and linking it to the resulting fleet_maintenance row once an
// admin actually performs and records the service.
export async function requestVehicleMaintenanceAction(fd:FormData){
  const p=await getSessionProfile();
  if(!p||!p.user.is_active) throw appError('Authentication required.');
  const db=createClient();
  const vehicleId=req(fd,'vehicle_id');
  const {data:vehicle}=await db.from('fleet_vehicles').select('id,vehicle_no').eq('id',vehicleId).maybeSingle();
  if(!vehicle) throw appError('Vehicle not found.');
  const {data:category}=await db.from('internal_request_categories').select('id').eq('code','fleet_maintenance').maybeSingle();
  if(!category) throw appError('Fleet Maintenance Request category is not configured.');
  const description=req(fd,'description');
  // request_no has no DB default (unlike PR/PO/asset numbers) — the
  // existing internal-requests engine generates it app-side; mirrored here.
  const stamp=new Date();const prefix=`IR-${stamp.getUTCFullYear()}${String(stamp.getUTCMonth()+1).padStart(2,'0')}`;
  const {count}=await db.from('internal_requests').select('id',{count:'exact',head:true}).like('request_no',`${prefix}-%`);
  const requestNo=`${prefix}-${String((count??0)+1).padStart(4,'0')}`;
  const payload={...biz(p),request_no:requestNo,category_id:category.id,vehicle_id:vehicleId,requester_user_id:p.user.id,title:`Maintenance request: ${vehicle.vehicle_no}`,description,priority:(opt(fd,'priority')||'normal'),needed_by:opt(fd,'needed_by'),status:'prepared',prepared_by:p.user.id,prepared_at:new Date().toISOString()};
  const {data,error}=await db.from('internal_requests').insert(payload).select('id').single();
  if(error||!data) throw appError(error?.message||'Unable to submit maintenance request.');
  const {error:ie}=await db.from('internal_request_items').insert({...biz(p),request_id:data.id,item_description:description,quantity:1,unit:'service'});
  if(ie){await db.from('internal_requests').delete().eq('id',data.id);throw appError(ie.message);}
  await audit(p.user.id,data.id,'maintenance_request_submitted',{vehicle_id:vehicleId});
  revalidatePath('/admin/fleet');revalidatePath('/admin/requests');
  return {ok:true};
}
