'use client';
import { errorText } from '@/core/errors/appError';
import {createContext,useContext,useMemo,useState,type ReactNode} from 'react';
import {ActionBar,PopupAction} from '@/core/ui/PopupAction';
import {createFleetExpenseAction,createMaintenanceAction,createTripAction,createVehicleAction,registerDriverAction,assignVehicleAction,returnVehicleAction,requestVehicleMaintenanceAction,updateTripStatusAction,updateVehicleAction} from './actions';
import {approveInternalRequestAction,rejectInternalRequestAction,reviewInternalRequestAction} from '@/modules/admin/requests/actions';
type Emp={id:string;employee_no:string;first_name:string;last_name:string;preferred_name?:string|null;employment_status:string};
type Vehicle={id:string;vehicle_no:string;plate_no?:string|null;vehicle_type:string;make?:string|null;model?:string|null;year?:number|null;color?:string|null;vin?:string|null;engine_no?:string|null;purchase_date?:string|null;purchase_cost?:number|null;supplier?:string|null;registration_expiry?:string|null;insurance_expiry?:string|null;odometer:number;capacity?:string|null;location?:string|null;condition:string;status:string;notes?:string|null};
type Driver={id:string;employee_id:string;license_no?:string|null;license_expiry?:string|null;license_type?:string|null;authorized:boolean;employee?:any};
type Assignment={id:string;vehicle_id:string;employee_id:string;assigned_at:string;returned_at?:string|null;purpose?:string|null;location?:string|null;employee?:any;vehicle?:any};
type Trip={id:string;trip_no:string;vehicle_id:string;driver_employee_id?:string|null;trip_date:string;departure_at?:string|null;return_at?:string|null;origin?:string|null;destination?:string|null;purpose:string;starting_odometer?:number|null;ending_odometer?:number|null;status:string;vehicle?:any;driver?:any};
type Expense={id:string;vehicle_id:string;expense_date:string;expense_type:string;description:string;amount:number;vendor?:string|null;vehicle?:any};
type Maint={id:string;vehicle_id:string;service_date:string;service_type:string;description:string;odometer?:number|null;vendor?:string|null;cost?:number|null;next_service_date?:string|null;vehicle?:any};
// U036 — a Fleet Maintenance Request, filed through the shared internal_requests engine.
type MaintRequest={id:string;vehicle_id:string|null;status:string;rejection_reason?:string|null;created_at:string;vehicle?:{vehicle_no:string}|null;items?:{item_description:string}[]};
const statuses=['available','assigned','in_use','maintenance','out_of_service','retired','disposed'];const conditions=['new','good','fair','needs_repair','damaged'];const trips=['planned','started','completed','cancelled'];const expenseTypes=['fuel','toll','parking','maintenance','repair','registration','insurance','other'];
const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());const person=(e:any)=>e?.preferred_name||`${e?.first_name??''} ${e?.last_name??''}`.trim();
export default function FleetManagement({profile,vehicles,employees,drivers,assignments,trips,expenses,maintenance,maintenanceRequests,canViewConfidential}:{profile:any;vehicles:Vehicle[];employees:Emp[];drivers:Driver[];assignments:Assignment[];trips:Trip[];expenses:Expense[];maintenance:Maint[];maintenanceRequests:MaintRequest[];canViewConfidential:boolean}){
 const [tab,setTab]=useState('vehicles'),[modal,setModal]=useState<string|null>(null),[editing,setEditing]=useState<Vehicle|null>(null),[selected,setSelected]=useState<Vehicle|null>(null),[selectedRequest,setSelectedRequest]=useState<MaintRequest|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[q,setQ]=useState('');
 const filtered=useMemo(()=>vehicles.filter(v=>`${v.vehicle_no} ${v.plate_no??''} ${v.vehicle_type} ${v.make??''} ${v.model??''} ${v.location??''}`.toLowerCase().includes(q.toLowerCase())),[vehicles,q]);
 const activeAssignments=assignments.filter(a=>!a.returned_at);const run=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{await fn();setModal(null);setEditing(null);setSelected(null)}catch(e){setError(e instanceof Error?errorText(e):'Operation failed.')}finally{setBusy(false)}};
 const stats=Object.fromEntries(statuses.map(s=>[s,vehicles.filter(v=>v.status===s).length]));
 // Build 65: page-level add/record forms open in PopupActions (one ActionBar per tab). The form
 // components are shared with the row-level modals; inside a pop-up their own Modal frame is skipped.
 type V='primary'|'secondary';
 const vehiclePopup=(v:V='primary')=><PopupAction label="+ New vehicle" title="New Vehicle" variant={v} notice={error} wide>{(close)=><InPopup.Provider value={true}><VehicleForm vehicle={null} busy={busy} onClose={close} onSubmit={f=>run(async()=>{await createVehicleAction(f);close()})}/></InPopup.Provider>}</PopupAction>;
 const driverPopup=(v:V='primary')=><PopupAction label="Register driver" title="Register Driver" variant={v} notice={error}>{(close)=><InPopup.Provider value={true}><DriverForm employees={employees} busy={busy} canViewConfidential={canViewConfidential} onClose={close} onSubmit={f=>run(async()=>{await registerDriverAction(f);close()})}/></InPopup.Provider>}</PopupAction>;
 const tripPopup=(v:V='primary')=><PopupAction label="Plan trip" title="Plan Fleet Trip" variant={v} notice={error}>{(close)=><InPopup.Provider value={true}><TripForm vehicles={vehicles} employees={employees} drivers={drivers} busy={busy} onClose={close} onSubmit={f=>run(async()=>{await createTripAction(f);close()})}/></InPopup.Provider>}</PopupAction>;
 const expensePopup=(v:V='primary')=><PopupAction label="Record expense" title="Record Fleet Expense" variant={v} notice={error}>{(close)=><InPopup.Provider value={true}><ExpenseForm vehicles={vehicles} trips={trips} busy={busy} onClose={close} onSubmit={f=>run(async()=>{await createFleetExpenseAction(f);close()})}/></InPopup.Provider>}</PopupAction>;
 const maintenancePopup=(v:V='primary')=><PopupAction label="Record maintenance" title="Record Maintenance" variant={v} notice={error}>{(close)=><InPopup.Provider value={true}><MaintenanceForm vehicles={vehicles} request={null} busy={busy} onClose={close} onSubmit={f=>run(async()=>{await createMaintenanceAction(f);close()})}/></InPopup.Provider>}</PopupAction>;
 const requestPopup=(v:V='primary')=><PopupAction label="Request maintenance" title="Request Vehicle Maintenance" variant={v} notice={error}>{(close)=><InPopup.Provider value={true}><RequestMaintenanceForm vehicles={vehicles} busy={busy} onClose={close} onSubmit={f=>run(async()=>{await requestVehicleMaintenanceAction(f);close()})}/></InPopup.Provider>}</PopupAction>;
 return <div className="space-y-6"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-2xl font-semibold">Fleet Management</h1><p className="text-sm text-slate-500">Vehicles, drivers, assignments, trips, expenses and maintenance.</p></div></div>
 <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-7">{statuses.map(s=><Stat key={s} title={label(s)} value={String(stats[s]??0)}/>)}</div>
 {error&&<div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="flex flex-wrap gap-2 border-b pb-2">{[['vehicles','Vehicles'],['drivers','Drivers'],['assignments','Assignments'],['trips','Trips'],['expenses','Expenses'],['maintenance','Maintenance'],['requests','Maintenance Requests']].map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`rounded px-3 py-2 text-sm ${tab===v?'bg-slate-900 text-white':'bg-slate-100 text-slate-700'}`}>{l}{v==='requests'&&maintenanceRequests.filter(r=>r.status==='prepared'||r.status==='reviewed').length>0?` (${maintenanceRequests.filter(r=>r.status==='prepared'||r.status==='reviewed').length})`:''}</button>)}</div>
 {tab==='vehicles'&&<section className="space-y-3"><ActionBar>{vehiclePopup()}{tripPopup('secondary')}{expensePopup('secondary')}{maintenancePopup('secondary')}</ActionBar><div className="flex flex-wrap gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search vehicle, plate, model..." className="rounded border px-3 py-2 text-sm"/></div><div className="overflow-x-auto rounded bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{['Vehicle','Type','Status','Odometer','Registration','Insurance','Location','Actions'].map(x=><th key={x} className="px-4 py-3 text-left font-medium">{x}</th>)}</tr></thead><tbody>{filtered.map(v=><tr key={v.id} className="border-t"><td className="px-4 py-3"><b>{v.vehicle_no}</b><div className="text-xs text-slate-500">{v.plate_no||'No plate'} · {v.make||''} {v.model||''}</div></td><td className="px-4 py-3">{v.vehicle_type}</td><td className="px-4 py-3"><span className="rounded bg-slate-100 px-2 py-1 text-xs">{label(v.status)}</span></td><td className="px-4 py-3">{v.odometer}</td><td className="px-4 py-3">{expiry(v.registration_expiry)}</td><td className="px-4 py-3">{expiry(v.insurance_expiry)}</td><td className="px-4 py-3">{v.location||'—'}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-1">{v.status==='available'&&<button onClick={()=>{setSelected(v);setModal('assign')}} className="rounded bg-emerald-700 px-2 py-1 text-xs text-white">Assign</button>}{v.status==='assigned'&&<button onClick={()=>{setSelected(v);setModal('return')}} className="rounded bg-amber-600 px-2 py-1 text-xs text-white">Return</button>}<button onClick={()=>{setEditing(v);setModal('vehicle')}} className="rounded border px-2 py-1 text-xs">Edit</button></div></td></tr>)}</tbody></table></div></section>}
 {tab==='drivers'&&<section><ActionBar className="mb-3">{driverPopup()}</ActionBar><div className="mb-3"><p className="text-sm text-slate-500">Only authorized, currently employed drivers with valid licenses can be assigned vehicles.</p></div><Table headers={['Employee','License','Type','Expiry','Authorized']} rows={drivers.map(d=>[person(d.employee),canViewConfidential?(d.license_no||'—'):'Confidential',d.license_type||'—',d.license_expiry||'—',d.authorized?'Yes':'No'])}/></section>}
 {tab==='assignments'&&<Table headers={['Vehicle','Employee','Assigned','Purpose','Location','Returned']} rows={assignments.map(a=>[a.vehicle?.vehicle_no,person(a.employee),new Date(a.assigned_at).toLocaleString(),a.purpose||'—',a.location||'—',a.returned_at?new Date(a.returned_at).toLocaleString():'Active'])}/>} 
 {tab==='trips'&&<section><ActionBar className="mb-3">{tripPopup()}</ActionBar><Table headers={['Trip','Date','Vehicle','Driver','Route','Purpose','Status','Action']} rows={trips.map(t=>[t.trip_no,t.trip_date,t.vehicle?.vehicle_no||'—',person(t.driver)||'—',`${t.origin||'—'} → ${t.destination||'—'}`,t.purpose,<span className="rounded bg-slate-100 px-2 py-1 text-xs">{label(t.status)}</span>,t.status!=='completed'&&t.status!=='cancelled'?<div className="flex gap-1">{t.status==='planned'&&<button onClick={()=>run(async()=>{const f=new FormData();f.set('trip_id',t.id);f.set('status','started');await updateTripStatusAction(f)})} className="rounded bg-emerald-700 px-2 py-1 text-xs text-white">Start</button>}{t.status==='started'&&<button onClick={()=>{setSelected(t as any);setModal('completeTrip')}} className="rounded bg-slate-900 px-2 py-1 text-xs text-white">Complete</button>}<button onClick={()=>run(async()=>{const f=new FormData();f.set('trip_id',t.id);f.set('status','cancelled');await updateTripStatusAction(f)})} className="rounded border px-2 py-1 text-xs">Cancel</button></div>:'—'])}/></section>}
 {tab==='expenses'&&<section><ActionBar className="mb-3">{expensePopup()}</ActionBar><Table headers={['Date','Vehicle','Type','Description','Vendor','Amount']} rows={expenses.map(x=>[x.expense_date,x.vehicle?.vehicle_no||'—',label(x.expense_type),x.description,x.vendor||'—',`₱ ${Number(x.amount).toLocaleString(undefined,{minimumFractionDigits:2})}`])}/></section>}
 {tab==='maintenance'&&<section><ActionBar className="mb-3">{maintenancePopup()}</ActionBar><Table headers={['Date','Vehicle','Service','Description','Vendor','Cost','Next service']} rows={maintenance.map(x=>[x.service_date,x.vehicle?.vehicle_no||'—',x.service_type,x.description,x.vendor||'—',x.cost?`₱ ${Number(x.cost).toLocaleString(undefined,{minimumFractionDigits:2})}`:'—',x.next_service_date||'—'])}/></section>}
 {tab==='requests'&&<section className="space-y-3">
   <ActionBar>{requestPopup()}</ActionBar>
   <p className="text-sm text-slate-500">Filed by any signed-in employee through the same review/approve chain as every other internal request; routes through Fleet once approved.</p>
   <div className="overflow-x-auto rounded bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{['Filed','Vehicle','Issue','Status','Actions'].map(x=><th key={x} className="px-4 py-3 text-left font-medium">{x}</th>)}</tr></thead><tbody>{maintenanceRequests.map(r=><tr key={r.id} className="border-t"><td className="px-4 py-3">{new Date(r.created_at).toLocaleDateString()}</td><td className="px-4 py-3">{r.vehicle?.vehicle_no||'—'}</td><td className="px-4 py-3">{r.items?.[0]?.item_description||'—'}</td><td className="px-4 py-3"><span className="rounded bg-slate-100 px-2 py-1 text-xs">{label(r.status)}</span>{r.rejection_reason&&<div className="text-xs text-red-600">{r.rejection_reason}</div>}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-1">
     {r.status==='prepared'&&<><button onClick={()=>run(async()=>{const f=new FormData();f.set('request_id',r.id);f.set('decision','reviewed');await reviewInternalRequestAction(f)})} className="rounded bg-emerald-700 px-2 py-1 text-xs text-white">Mark reviewed</button><button onClick={()=>run(async()=>{const f=new FormData();f.set('request_id',r.id);f.set('decision','rejected');f.set('reason','Not approved at review.');await reviewInternalRequestAction(f)})} className="rounded border px-2 py-1 text-xs">Reject</button></>}
     {r.status==='reviewed'&&<><button onClick={()=>run(async()=>{const f=new FormData();f.set('request_id',r.id);await approveInternalRequestAction(f)})} className="rounded bg-emerald-700 px-2 py-1 text-xs text-white">Approve</button><button onClick={()=>run(async()=>{const f=new FormData();f.set('request_id',r.id);f.set('reason','Not approved.');await rejectInternalRequestAction(f)})} className="rounded border px-2 py-1 text-xs">Reject</button></>}
     {r.status==='approved'&&<button onClick={()=>{setSelectedRequest(r);setModal('maintenance')}} className="rounded bg-slate-900 px-2 py-1 text-xs text-white">Complete maintenance</button>}
     {(r.status==='fulfilled')&&<span className="text-xs text-slate-500">Completed</span>}
   </div></td></tr>)}{maintenanceRequests.length===0&&<tr><td colSpan={5} className="p-6 text-center text-sm text-slate-400">No maintenance requests filed yet.</td></tr>}</tbody></table></div>
 </section>}
 {modal==='vehicle'&&<VehicleForm vehicle={editing} busy={busy} onClose={()=>setModal(null)} onSubmit={f=>run(()=>editing?updateVehicleAction(f):createVehicleAction(f))}/>} {modal==='assign'&&selected&&<AssignForm vehicle={selected} employees={employees} drivers={drivers} busy={busy} onClose={()=>setModal(null)} onSubmit={f=>run(()=>assignVehicleAction(f))}/>} {modal==='return'&&selected&&<ReturnForm vehicle={selected} busy={busy} onClose={()=>setModal(null)} onSubmit={f=>run(()=>returnVehicleAction(f))}/>} {modal==='completeTrip'&&selected&&<CompleteTrip trip={selected as any} busy={busy} onClose={()=>setModal(null)} onSubmit={f=>run(()=>updateTripStatusAction(f))}/>}
 {modal==='maintenance'&&<MaintenanceForm vehicles={vehicles} request={selectedRequest} busy={busy} onClose={()=>{setModal(null);setSelectedRequest(null)}} onSubmit={f=>run(()=>createMaintenanceAction(f))}/>}
 </div>
}
function Stat({title,value}:{title:string;value:string}){return <div className="rounded bg-white p-3 shadow-sm"><div className="text-xs text-slate-500">{title}</div><div className="text-xl font-semibold">{value}</div></div>}
function Table({headers,rows}:{headers:string[];rows:any[][]}){return <div className="overflow-x-auto rounded bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{headers.map(h=><th key={h} className="px-4 py-3 text-left font-medium">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t">{r.map((c,j)=><td key={j} className="px-4 py-3">{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="p-6 text-center text-sm text-slate-400">No records yet.</div>}</div>}
const expiry=(d?:string|null)=>d?new Date(d+'T00:00:00').toLocaleDateString():'—';
const InPopup=createContext(false);
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){if(useContext(InPopup))return <>{children}</>;return <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/40 p-4"><div className="w-full max-w-3xl rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b px-6 py-4"><h3 className="font-semibold">{title}</h3><button onClick={onClose}>✕</button></div><div className="p-6">{children}</div></div></div>}
function Field({name,label,type='text',required=false,defaultValue,step}:{name:string;label:string;type?:string;required?:boolean;defaultValue?:any;step?:string}){return <label className="text-sm">{label}{required?' *':''}<input name={name} type={type} required={required} defaultValue={defaultValue??''} step={step} className="mt-1 w-full rounded border px-3 py-2"/></label>}
function Select({name,label,options,defaultValue,required=true}:{name:string;label:string;options:{v:string;l:string}[];defaultValue?:string;required?:boolean}){return <label className="text-sm">{label}{required?' *':''}<select name={name} required={required} defaultValue={defaultValue} className="mt-1 w-full rounded border px-3 py-2">{options.map(o=><option key={o.v} value={o.v}>{o.l}</option>)}</select></label>}
function Actions({busy,onClose}:{busy:boolean;onClose:()=>void}){return <div className="flex justify-end gap-2 border-t pt-4 sm:col-span-2"><button type="button" onClick={onClose} className="rounded border px-4 py-2 text-sm">Cancel</button><button disabled={busy} className="rounded bg-slate-900 px-4 py-2 text-sm text-white">{busy?'Saving...':'Save'}</button></div>}
function VehicleForm({vehicle,busy,onClose,onSubmit}:{vehicle:Vehicle|null;busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title={vehicle?'Edit Vehicle':'New Vehicle'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(vehicle)f.set('vehicle_id',vehicle.id);onSubmit(f)}} className="grid gap-4 sm:grid-cols-2"><Field name="vehicle_no" label="Vehicle number" required defaultValue={vehicle?.vehicle_no}/><Field name="plate_no" label="Plate number" defaultValue={vehicle?.plate_no}/><Field name="vehicle_type" label="Vehicle type" required defaultValue={vehicle?.vehicle_type}/><Field name="make" label="Make" defaultValue={vehicle?.make}/><Field name="model" label="Model" defaultValue={vehicle?.model}/><Field name="year" label="Year" type="number" defaultValue={vehicle?.year}/><Field name="color" label="Color" defaultValue={vehicle?.color}/><Field name="vin" label="VIN" defaultValue={vehicle?.vin}/><Field name="engine_no" label="Engine number" defaultValue={vehicle?.engine_no}/><Field name="purchase_date" label="Purchase date" type="date" defaultValue={vehicle?.purchase_date}/><Field name="purchase_cost" label="Purchase cost" type="number" step="0.01" defaultValue={vehicle?.purchase_cost}/><Field name="supplier" label="Supplier" defaultValue={vehicle?.supplier}/><Field name="registration_expiry" label="Registration expiry" type="date" defaultValue={vehicle?.registration_expiry}/><Field name="insurance_expiry" label="Insurance expiry" type="date" defaultValue={vehicle?.insurance_expiry}/><Field name="odometer" label="Odometer" type="number" step="0.1" defaultValue={vehicle?.odometer??0}/><Field name="capacity" label="Capacity" defaultValue={vehicle?.capacity}/><Field name="location" label="Location" defaultValue={vehicle?.location}/><Select name="condition" label="Condition" options={conditions.map(x=>({v:x,l:label(x)}))} defaultValue={vehicle?.condition||'good'}/>{vehicle&&<Select name="status" label="Status" options={statuses.filter(x=>!['assigned','in_use'].includes(x)).map(x=>({v:x,l:label(x)}))} defaultValue={vehicle.status}/>}<label className="text-sm sm:col-span-2">Notes<textarea name="notes" rows={3} defaultValue={vehicle?.notes||''} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></form></Modal>}
function DriverForm({employees,busy,canViewConfidential,onClose,onSubmit}:{employees:Emp[];busy:boolean;canViewConfidential:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title="Register Driver" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4 sm:grid-cols-2"><Select name="employee_id" label="Employee" options={employees.map(e=>({v:e.id,l:`${e.employee_no} — ${person(e)}`}))}/>{canViewConfidential?<Field name="license_no" label="License number"/>:<p className="text-sm text-slate-400 sm:col-span-1">License number (confidential — Admin approvers only)</p>}<Field name="license_type" label="License type"/><Field name="license_expiry" label="License expiry" type="date"/><label className="flex items-center gap-2 text-sm"><input name="authorized" type="checkbox" defaultChecked/> Authorized driver</label><label className="text-sm sm:col-span-2">Notes<textarea name="notes" rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></form></Modal>}
function AssignForm({vehicle,employees,drivers,busy,onClose,onSubmit}:{vehicle:Vehicle;employees:Emp[];drivers:Driver[];busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){const eligible=employees.filter(e=>drivers.some(d=>d.employee_id===e.id&&d.authorized&&(!d.license_expiry||d.license_expiry>=new Date().toISOString().slice(0,10))));return <Modal title={`Assign ${vehicle.vehicle_no}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);f.set('vehicle_id',vehicle.id);onSubmit(f)}} className="grid gap-4"><Select name="employee_id" label="Authorized driver" options={eligible.map(e=>({v:e.id,l:`${e.employee_no} — ${person(e)}`}))}/><Field name="purpose" label="Assignment purpose"/><Field name="location" label="Base/location"/><label className="text-sm">Notes<textarea name="notes" rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></form></Modal>}
function ReturnForm({vehicle,busy,onClose,onSubmit}:{vehicle:Vehicle;busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title={`Return ${vehicle.vehicle_no}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);f.set('vehicle_id',vehicle.id);onSubmit(f)}} className="grid gap-4"><Field name="location" label="Return location"/><label className="text-sm">Notes<textarea name="notes" rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></form></Modal>}
function TripForm({vehicles,employees,drivers,busy,onClose,onSubmit}:{vehicles:Vehicle[];employees:Emp[];drivers:Driver[];busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title="Plan Fleet Trip" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4 sm:grid-cols-2"><Field name="trip_no" label="Trip number" required/><Field name="trip_date" label="Trip date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/><Select name="vehicle_id" label="Vehicle" options={vehicles.filter(v=>!['maintenance','out_of_service','retired','disposed'].includes(v.status)).map(v=>({v:v.id,l:`${v.vehicle_no} — ${v.plate_no||v.model||v.vehicle_type}`}))}/><Select name="driver_employee_id" label="Driver" required={false} options={[{v:'',l:'Unassigned'},...drivers.filter(d=>d.authorized).map(d=>({v:d.employee_id,l:person(d.employee)}))]}/><Field name="departure_at" label="Departure time" type="datetime-local"/><Field name="starting_odometer" label="Starting odometer" type="number" step="0.1"/><Field name="origin" label="Origin"/><Field name="destination" label="Destination"/><Field name="purpose" label="Purpose" required/><label className="text-sm sm:col-span-2">Notes<textarea name="notes" rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></form></Modal>}
function CompleteTrip({trip,busy,onClose,onSubmit}:{trip:Trip;busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title={`Complete ${trip.trip_no}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);f.set('trip_id',trip.id);f.set('status','completed');onSubmit(f)}} className="grid gap-4"><Field name="ending_odometer" label="Ending odometer" type="number" step="0.1" required/><Actions busy={busy} onClose={onClose}/></form></Modal>}
function ExpenseForm({vehicles,trips,busy,onClose,onSubmit}:{vehicles:Vehicle[];trips:Trip[];busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title="Record Fleet Expense" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4 sm:grid-cols-2"><Select name="vehicle_id" label="Vehicle" options={vehicles.map(v=>({v:v.id,l:v.vehicle_no}))}/><Select name="trip_id" label="Trip" required={false} options={[{v:'',l:'No trip'},...trips.map(t=>({v:t.id,l:`${t.trip_no} — ${t.trip_date}`}))]}/><Field name="expense_date" label="Date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/><Select name="expense_type" label="Type" options={expenseTypes.map(x=>({v:x,l:label(x)}))}/><Field name="description" label="Description" required/><Field name="amount" label="Amount" type="number" step="0.01" required/><Field name="vendor" label="Vendor"/><Field name="receipt_reference" label="Receipt reference"/><label className="text-sm sm:col-span-2">Notes<textarea name="notes" rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></form></Modal>}
function MaintenanceForm({vehicles,request,busy,onClose,onSubmit}:{vehicles:Vehicle[];request?:MaintRequest|null;busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title={request?`Complete Maintenance Request — ${request.vehicle?.vehicle_no||''}`:'Record Maintenance'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(request)f.set('request_id',request.id);onSubmit(f)}} className="grid gap-4 sm:grid-cols-2">{request?<input type="hidden" name="vehicle_id" value={request.vehicle_id??''}/>:<Select name="vehicle_id" label="Vehicle" options={vehicles.map(v=>({v:v.id,l:v.vehicle_no}))}/>}<Field name="service_date" label="Service date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/><Field name="service_type" label="Service type" required/><Field name="description" label="Description" required defaultValue={request?.items?.[0]?.item_description}/><Field name="odometer" label="Odometer" type="number" step="0.1"/><Field name="vendor" label="Vendor"/><Field name="cost" label="Cost" type="number" step="0.01"/><Field name="next_service_date" label="Next service date" type="date"/><Field name="next_service_odometer" label="Next service odometer" type="number" step="0.1"/><label className="text-sm sm:col-span-2">Notes<textarea name="notes" rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></form></Modal>}
// U036 — any signed-in employee can file a maintenance request against a
// vehicle; it enters the shared internal_requests review/approve chain.
function RequestMaintenanceForm({vehicles,busy,onClose,onSubmit}:{vehicles:Vehicle[];busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title="Request Vehicle Maintenance" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4"><Select name="vehicle_id" label="Vehicle" options={vehicles.filter(v=>v.status!=='retired'&&v.status!=='disposed').map(v=>({v:v.id,l:`${v.vehicle_no} — ${v.plate_no||v.model||v.vehicle_type}`}))}/><label className="text-sm">What's the issue? *<textarea name="description" required rows={3} className="mt-1 w-full rounded border px-3 py-2" placeholder="e.g. Aircon not cooling, unusual engine noise..."/></label><Select name="priority" label="Priority" required={false} options={[{v:'normal',l:'Normal'},{v:'high',l:'High'},{v:'urgent',l:'Urgent'},{v:'low',l:'Low'}]} defaultValue="normal"/><Actions busy={busy} onClose={onClose}/></form></Modal>}
