'use client';
import { errorText } from '@/core/errors/appError';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ActionBar, PopupAction } from '@/core/ui/PopupAction';
import { approveCorrectionAction, assignScheduleAction, checkAndNotifyAction, clockInAction, clockOutAction, closePeriodAction, createScheduleAction, recalculateAttendanceAction, requestCorrectionAction, reviewCorrectionAction, saveAttendanceAction } from './actions';
import { approveLeaveAction, cancelLeaveAction, createLeaveTypeAction, requestLeaveAction, reviewLeaveAction } from '@/modules/admin/leave/actions';

type Employee={id:string;employee_no:string;first_name:string;last_name:string;preferred_name:string|null;user_id:string|null;employment_status:string;department_id:string|null;position_id:string|null;work_location_id:string|null};
type Schedule={id:string;name:string;timezone:string;grace_minutes:number};
type Attendance={id:string;employee_id:string;attendance_date:string;schedule_id:string|null;time_in:string|null;break_out:string|null;break_in:string|null;time_out:string|null;regular_hours:number;overtime_hours:number;late_minutes:number;undertime_minutes:number;status:string;notes:string|null};
type Correction={id:string;attendance_id:string;requested_by:string;reason:string;requested_time_in:string|null;requested_time_out:string|null;requested_status:string|null;status:string;rejection_reason:string|null};
type Period={id:string;name:string;start_date:string;end_date:string;status:string};
type Assignment={id:string;employee_id:string;schedule_id:string;effective_from:string;effective_to:string|null};
type Master={id:string;name:string};
type LeaveType={id:string;code:string;name:string;paid:boolean;active:boolean;requires_approval:boolean;default_days_per_year:number|null};
type LeaveRequest={id:string;employee_id:string;leave_type_id:string;start_date:string;end_date:string;day_type:string;days:number;reason:string;status:string;rejection_reason:string|null;requested_by:string};
type LeaveBalance={id:string;employee_id:string;leave_type_id:string;leave_year:number;entitlement:number;used:number;adjustment:number};
const labels:Record<string,string>={present:'Present',absent:'Absent',late:'Late',undertime:'Undertime',half_day:'Half day',leave:'Leave',holiday:'Holiday',rest_day:'Rest day',official_business:'Official business',work_from_home:'Work from home',incomplete:'Incomplete'};
const leaveStatusLabel:Record<string,string>={prepared:'Prepared',reviewed:'Reviewed',approved:'Approved',rejected:'Rejected',cancelled:'Cancelled'};
const emptyAttendance={employee_id:'',attendance_date:new Date().toISOString().slice(0,10),schedule_id:'',time_in:'',break_out:'',break_in:'',time_out:'',regular_hours:'8',overtime_hours:'0',late_minutes:'0',undertime_minutes:'0',status:'present',notes:''};
export default function TimekeepingManagement({employees,schedules,attendance,corrections,periods,assignments,departments,positions,locations,leaveTypes,leaveRequests,leaveBalances,initialTab}: {employees:Employee[];schedules:Schedule[];attendance:Attendance[];corrections:Correction[];periods:Period[];assignments:Assignment[];departments:Master[];positions:Master[];locations:Master[];leaveTypes:LeaveType[];leaveRequests:LeaveRequest[];leaveBalances:LeaveBalance[];initialTab?:string}){
 const [tab,setTab]=useState(initialTab&&['today','corrections','schedules','periods','leave','leavebalances','leavetypes'].includes(initialTab)?initialTab:'today'); const [query,setQuery]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const router=useRouter();
 const [deptFilter,setDeptFilter]=useState(''); const [posFilter,setPosFilter]=useState(''); const [locFilter,setLocFilter]=useState('');
 const filtered=useMemo(()=>attendance.filter(a=>{const e=employees.find(x=>x.id===a.employee_id); if(deptFilter&&e?.department_id!==deptFilter) return false; if(posFilter&&e?.position_id!==posFilter) return false; if(locFilter&&e?.work_location_id!==locFilter) return false; const h=[e?.employee_no,e?.first_name,e?.last_name,e?.preferred_name,a.attendance_date,a.status].filter(Boolean).join(' ').toLowerCase(); return !query||h.includes(query.toLowerCase())}),[attendance,employees,query,deptFilter,posFilter,locFilter]);
 const [notice,setNotice]=useState('');
 async function run(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();router.refresh()}catch(e){setError(e instanceof Error?errorText(e):'Operation failed.')}finally{setBusy(false)}}
 async function runCheckAndNotify(){setBusy(true);setError('');setNotice('');try{const r=await checkAndNotifyAction();setNotice(`Checked: ${r.noClockIn} missing clock-in, ${r.staleCorrections} stale correction(s), ${r.staleLeave} stale leave request(s). Notifications sent where applicable.`);router.refresh()}catch(e){setError(e instanceof Error?errorText(e):'Check failed.')}finally{setBusy(false)}}
 const pending=corrections.filter(c=>['prepared','reviewed'].includes(c.status));
 const nameFor=(list:Master[],id:string|null)=>id?(list.find(m=>m.id===id)?.name||'—'):'—';
 return <div className="space-y-6">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-semibold">Timekeeping & Leave</h2><p className="text-sm text-slate-500">Schedules, daily attendance, corrections, locked payroll periods, and leave requests/balances in one place.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>run(clockInAction)} disabled={busy} className="rounded bg-emerald-700 px-3 py-2 text-sm text-white">Clock in</button><button onClick={()=>run(clockOutAction)} disabled={busy} className="rounded bg-slate-800 px-3 py-2 text-sm text-white">Clock out</button><button onClick={runCheckAndNotify} disabled={busy} className="rounded border border-amber-400 bg-amber-50 px-3 py-2 text-sm text-amber-800">Check & notify</button></div></div>
  {error&&<div className="rounded border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  {notice&&<div className="rounded border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</div>}
  <div className="grid gap-4 sm:grid-cols-4"><Stat title="Employees" value={String(employees.filter(e=>e.employment_status!=='separated').length)}/><Stat title="Attendance records" value={String(attendance.length)}/><Stat title="Pending corrections" value={String(pending.length)}/><Stat title="Pending leave" value={String(leaveRequests.filter(r=>['prepared','reviewed'].includes(r.status)).length)}/></div>
  <div className="flex flex-wrap gap-2 border-b pb-2">{[['today','Attendance'],['corrections','Corrections'],['schedules','Schedules'],['periods','Periods'],['leave','Leave requests'],['leavebalances','Leave balances'],['leavetypes','Leave types']].map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`rounded px-3 py-2 text-sm ${tab===v?'bg-slate-900 text-white':'bg-slate-100 text-slate-700'}`}>{l}</button>)}</div>
  {tab==='today'&&<section className="space-y-4"><ActionBar><PopupAction label="Record attendance" title="Record attendance" notice={error} wide>{(close)=><AttendanceForm employees={employees} schedules={schedules} busy={busy} onClose={close} onSubmit={f=>run(async()=>{await saveAttendanceAction(f);close()})}/>}</PopupAction></ActionBar><div className="grid gap-3 sm:grid-cols-4"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee, date or status..." className="rounded border px-3 py-2 text-sm sm:col-span-1"/><select value={deptFilter} onChange={e=>setDeptFilter(e.target.value)} className="rounded border px-3 py-2 text-sm"><option value="">All departments</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select value={posFilter} onChange={e=>setPosFilter(e.target.value)} className="rounded border px-3 py-2 text-sm"><option value="">All positions</option>{positions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={locFilter} onChange={e=>setLocFilter(e.target.value)} className="rounded border px-3 py-2 text-sm"><option value="">All work locations</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div className="overflow-x-auto rounded-lg border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Dept / Position</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">In</th><th className="px-4 py-3">Out</th><th className="px-4 py-3">Regular</th><th className="px-4 py-3">OT</th><th className="px-4 py-3">Late</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{filtered.map(a=>{const e=employees.find(x=>x.id===a.employee_id);return <tr key={a.id} className="border-t"><td className="px-4 py-3">{e?.preferred_name||`${e?.first_name} ${e?.last_name}`}<div className="text-xs text-slate-500">{e?.employee_no}</div></td><td className="px-4 py-3 text-xs text-slate-500">{nameFor(departments,e?.department_id||null)} / {nameFor(positions,e?.position_id||null)}</td><td className="px-4 py-3">{a.attendance_date}</td><td className="px-4 py-3">{fmt(a.time_in)}</td><td className="px-4 py-3">{fmt(a.time_out)}</td><td className="px-4 py-3">{a.regular_hours}h</td><td className="px-4 py-3">{a.overtime_hours}h</td><td className="px-4 py-3">{a.late_minutes}m</td><td className="px-4 py-3">{labels[a.status]||a.status}</td><td className="px-4 py-3"><button onClick={()=>run(async()=>{const f=new FormData();f.set('attendance_id',a.id);await recalculateAttendanceAction(f)})} disabled={busy} className="text-blue-700 hover:underline">Recalculate</button></td></tr>})}{filtered.length===0&&<tr><td colSpan={10} className="px-4 py-10 text-center text-slate-500">No attendance records found.</td></tr>}</tbody></table></div></section>}
  {tab==='corrections'&&<section className="rounded-lg border bg-white overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-4 py-3">Employee / attendance</th><th className="px-4 py-3">Reason</th><th className="px-4 py-3">Requested</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{corrections.map(c=>{const a=attendance.find(x=>x.id===c.attendance_id);const e=employees.find(x=>x.id===a?.employee_id);return <tr key={c.id} className="border-t"><td className="px-4 py-3">{e?.preferred_name||`${e?.first_name} ${e?.last_name}`}<div className="text-xs text-slate-500">{a?.attendance_date}</div></td><td className="px-4 py-3 max-w-sm">{c.reason}</td><td className="px-4 py-3">{fmt(c.requested_time_in)} → {fmt(c.requested_time_out)}</td><td className="px-4 py-3">{c.status}</td><td className="px-4 py-3 whitespace-nowrap">{c.status==='prepared'&&<button onClick={()=>run(async()=>{const f=new FormData();f.set('correction_id',c.id);f.set('decision','reviewed');await reviewCorrectionAction(f)})} className="mr-3 text-blue-700 hover:underline">Review</button>}{c.status==='prepared'&&<button onClick={()=>run(async()=>{const f=new FormData();f.set('correction_id',c.id);f.set('decision','rejected');f.set('rejection_reason','Rejected by Admin');await reviewCorrectionAction(f)})} className="mr-3 text-red-700 hover:underline">Reject</button>}{c.status==='reviewed'&&<button onClick={()=>run(async()=>{const f=new FormData();f.set('correction_id',c.id);await approveCorrectionAction(f)})} className="text-emerald-700 hover:underline">Approve</button>}</td></tr>})}{corrections.length===0&&<tr><td colSpan={5} className="px-4 py-10 text-center text-slate-500">No correction requests.</td></tr>}</tbody></table></section>}
  {tab==='schedules'&&<section className="space-y-4"><ActionBar><PopupAction label="+ New schedule" title="Create work schedule" notice={error} wide>{(close)=><ScheduleForm busy={busy} onClose={close} onSubmit={f=>run(async()=>{await createScheduleAction(f);close()})}/>}</PopupAction><PopupAction label="Assign schedule" title="Assign work schedule" variant="secondary" notice={error}>{(close)=><AssignForm employees={employees} schedules={schedules} busy={busy} onClose={close} onSubmit={f=>run(async()=>{await assignScheduleAction(f);close()})}/>}</PopupAction></ActionBar><div className="grid gap-4 md:grid-cols-2">{schedules.map(s=>{const assigned=assignments.filter(a=>a.schedule_id===s.id&&(!a.effective_to||a.effective_to>=new Date().toISOString().slice(0,10)));return <div key={s.id} className="rounded-lg border bg-white p-5"><h3 className="font-semibold">{s.name}</h3><p className="text-sm text-slate-500">{s.timezone} · {s.grace_minutes} minute grace period</p><div className="mt-3 text-xs uppercase tracking-wide text-slate-500">Currently assigned ({assigned.length})</div><ul className="mt-1 space-y-1 text-sm text-slate-700">{assigned.slice(0,6).map(a=>{const e=employees.find(x=>x.id===a.employee_id);return <li key={a.id}>{e?.preferred_name||`${e?.first_name} ${e?.last_name}`} <span className="text-xs text-slate-400">from {a.effective_from}</span></li>})}{assigned.length===0&&<li className="text-slate-400">No employees currently assigned.</li>}</ul></div>})}</div>{schedules.length===0&&<div className="rounded-lg border bg-white p-8 text-center text-slate-500">No schedules created yet.</div>}</section>}
  {tab==='periods'&&<section className="space-y-3">{periods.map(p=><div key={p.id} className="flex flex-col gap-3 rounded-lg border bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-medium">{p.name}</div><div className="text-sm text-slate-500">{p.start_date} → {p.end_date} · {p.status}</div></div>{p.status!=='locked'&&<button disabled={busy} onClick={()=>run(async()=>{const f=new FormData();f.set('period_id',p.id);await closePeriodAction(f)})} className="rounded border px-3 py-2 text-sm">Lock period</button>}</div>)}{periods.length===0&&<div className="rounded-lg border bg-white p-8 text-center text-slate-500">No attendance periods created yet.</div>}</section>}
  {tab==='leave'&&<section className="space-y-4"><ActionBar><PopupAction label="Request leave" title="Request leave" notice={error}>{(close)=><LeaveForm employees={employees} types={leaveTypes.filter(t=>t.active)} busy={busy} onClose={close} onSubmit={f=>run(async()=>{await requestLeaveAction(f);close()})}/>}</PopupAction></ActionBar><div className="overflow-x-auto rounded-lg border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Leave</th><th className="px-4 py-3">Dates</th><th className="px-4 py-3">Days</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{leaveRequests.map(r=>{const e=employees.find(x=>x.id===r.employee_id),t=leaveTypes.find(x=>x.id===r.leave_type_id);return <tr key={r.id} className="border-t"><td className="px-4 py-3">{e?.preferred_name||`${e?.first_name} ${e?.last_name}`}<div className="text-xs text-slate-500">{e?.employee_no}</div></td><td className="px-4 py-3">{t?.name}{t?.paid?'':' · unpaid'}</td><td className="px-4 py-3">{r.start_date} → {r.end_date}<div className="text-xs text-slate-500">{r.day_type}</div></td><td className="px-4 py-3">{r.days}</td><td className="px-4 py-3">{leaveStatusLabel[r.status]||r.status}</td><td className="px-4 py-3 whitespace-nowrap">{r.status==='prepared'&&<><button disabled={busy} onClick={()=>run(async()=>{const f=new FormData();f.set('leave_request_id',r.id);f.set('decision','reviewed');await reviewLeaveAction(f)})} className="mr-3 text-blue-700 hover:underline">Review</button><button disabled={busy} onClick={()=>run(async()=>{const f=new FormData();f.set('leave_request_id',r.id);f.set('decision','rejected');f.set('rejection_reason','Rejected by Admin');await reviewLeaveAction(f)})} className="mr-3 text-red-700 hover:underline">Reject</button></>}{r.status==='reviewed'&&<button disabled={busy} onClick={()=>run(async()=>{const f=new FormData();f.set('leave_request_id',r.id);await approveLeaveAction(f)})} className="mr-3 text-emerald-700 hover:underline">Approve</button>}{['prepared','reviewed'].includes(r.status)&&<button disabled={busy} onClick={()=>run(async()=>{const f=new FormData();f.set('leave_request_id',r.id);await cancelLeaveAction(f)})} className="text-slate-600 hover:underline">Cancel</button>}</td></tr>})}{leaveRequests.length===0&&<tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">No leave requests found.</td></tr>}</tbody></table></div></section>}
  {tab==='leavebalances'&&<section className="overflow-x-auto rounded-lg border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Leave type</th><th className="px-4 py-3">Entitlement</th><th className="px-4 py-3">Used</th><th className="px-4 py-3">Adjustment</th><th className="px-4 py-3">Available</th></tr></thead><tbody>{leaveBalances.map(b=>{const e=employees.find(x=>x.id===b.employee_id),t=leaveTypes.find(x=>x.id===b.leave_type_id),available=Number(b.entitlement)+Number(b.adjustment)-Number(b.used);return <tr key={b.id} className="border-t"><td className="px-4 py-3">{e?.preferred_name||`${e?.first_name} ${e?.last_name}`}</td><td className="px-4 py-3">{t?.name}</td><td className="px-4 py-3">{b.entitlement}</td><td className="px-4 py-3">{b.used}</td><td className="px-4 py-3">{b.adjustment}</td><td className="px-4 py-3 font-medium">{available}</td></tr>})}{leaveBalances.length===0&&<tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">No leave balances yet. They are created when an approved leave is posted.</td></tr>}</tbody></table></section>}
  {tab==='leavetypes'&&<section className="space-y-4"><ActionBar><PopupAction label="+ New leave type" title="New leave type" notice={error}>{(close)=><LeaveTypeForm busy={busy} onClose={close} onSubmit={f=>run(async()=>{await createLeaveTypeAction(f);close()})}/>}</PopupAction></ActionBar><div className="grid gap-4 md:grid-cols-2">{leaveTypes.map(t=><div key={t.id} className="rounded-lg border bg-white p-5"><div className="flex justify-between"><h3 className="font-semibold">{t.name}</h3><span className="text-xs text-slate-500">{t.code}</span></div><p className="mt-2 text-sm text-slate-500">{t.paid?'Paid':'Unpaid'} · {t.requires_approval?'Approval required':'No approval'}</p><p className="mt-1 text-sm text-slate-500">Default entitlement: {t.default_days_per_year??'Not set'} days/year</p></div>)}</div></section>}
 </div>
}
function Stat({title,value}:{title:string;value:string}){return <div className="rounded-lg border bg-white p-4"><div className="text-xs uppercase tracking-wide text-slate-500">{title}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>}
function fmt(v:string|null){return v?new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'}
function ScheduleForm({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="space-y-4"><Field name="name" label="Schedule name" required/><Field name="timezone" label="Timezone" defaultValue="Asia/Manila"/><Field name="grace_minutes" label="Grace minutes" type="number" defaultValue="10"/><div className="grid gap-3 sm:grid-cols-2">{['monday','tuesday','wednesday','thursday','friday','saturday','sunday'].map(d=><div key={d} className="rounded border p-3"><div className="mb-2 text-sm font-medium capitalize">{d}</div><div className="grid grid-cols-2 gap-2"><Field name={`${d}_in`} label="In" type="time"/><Field name={`${d}_out`} label="Out" type="time"/><Field name={`${d}_break_start`} label="Break out" type="time"/><Field name={`${d}_break_end`} label="Break in" type="time"/></div></div>)}</div><Actions busy={busy} onClose={onClose} text="Create schedule"/></form>}
function AttendanceForm({employees,schedules,busy,onClose,onSubmit}:{employees:Employee[];schedules:Schedule[];busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4 sm:grid-cols-2"><Select name="employee_id" label="Employee" options={employees.filter(e=>e.employment_status!=='separated').map(e=>[e.id,`${e.employee_no} — ${e.preferred_name||e.first_name+' '+e.last_name}`])}/><Field name="attendance_date" label="Date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><Select name="schedule_id" label="Schedule" options={[['','No schedule'],...schedules.map(s=>[s.id,s.name])]}/><Select name="status" label="Status" options={Object.entries(labels)}/><Field name="time_in" label="Time in" type="datetime-local"/><Field name="break_out" label="Break out" type="datetime-local"/><Field name="break_in" label="Break in" type="datetime-local"/><Field name="time_out" label="Time out" type="datetime-local"/><div className="rounded border bg-slate-50 p-3 text-sm text-slate-600 sm:col-span-2">Regular hours, overtime, late minutes and undertime are calculated automatically from the employee's assigned schedule. The selected schedule is used when supplied; otherwise IBX resolves the effective schedule for the attendance date.</div><label className="text-sm sm:col-span-2">Notes<textarea name="notes" rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose} text="Save attendance"/></form>}
function AssignForm({employees,schedules,busy,onClose,onSubmit}:{employees:Employee[];schedules:Schedule[];busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4 sm:grid-cols-2"><Select name="employee_id" label="Employee" options={employees.filter(e=>e.employment_status!=='separated').map(e=>[e.id,`${e.employee_no} — ${e.preferred_name||e.first_name+' '+e.last_name}`])}/><Select name="schedule_id" label="Schedule" options={schedules.map(s=>[s.id,s.name])}/><Field name="effective_from" label="Effective from" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><Field name="effective_to" label="Effective to (optional)" type="date"/><div className="rounded border bg-slate-50 p-3 text-sm text-slate-600 sm:col-span-2">Assignment history is preserved — a new assignment does not delete prior ones, so past attendance keeps the schedule that was in effect on that date.</div><Actions busy={busy} onClose={onClose} text="Assign schedule"/></form>}
function LeaveForm({employees,types,busy,onClose,onSubmit}:{employees:Employee[];types:LeaveType[];busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4 sm:grid-cols-2"><Select name="employee_id" label="Employee" options={employees.filter(e=>e.employment_status!=='separated').map(e=>[e.id,`${e.employee_no} — ${e.preferred_name||e.first_name+' '+e.last_name}`])}/><Select name="leave_type_id" label="Leave type" options={types.map(t=>[t.id,`${t.name}${t.paid?'':' (unpaid)'}`])}/><Field name="start_date" label="Start" type="date" required/><Field name="end_date" label="End" type="date" required/><Select name="day_type" label="Day type" options={[['full_day','Full day'],['first_half','First half'],['second_half','Second half']]}/><label className="text-sm sm:col-span-2">Reason<textarea name="reason" required rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose} text="Submit request"/></form>}
function LeaveTypeForm({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4 sm:grid-cols-2"><Field name="code" label="Code (e.g. vacation)" required/><Field name="name" label="Name" required/><Field name="default_days_per_year" label="Default days/year" type="number"/><label className="text-sm sm:col-span-2">Description<textarea name="description" rows={2} className="mt-1 w-full rounded border px-3 py-2"/></label><label className="text-sm"><input type="checkbox" name="paid" defaultChecked className="mr-2"/>Paid leave</label><label className="text-sm"><input type="checkbox" name="requires_approval" defaultChecked className="mr-2"/>Requires approval</label><Actions busy={busy} onClose={onClose} text="Create leave type"/></form>}
function Actions({busy,onClose,text}:{busy:boolean;onClose:()=>void;text:string}){return <div className="flex justify-end gap-3 border-t pt-4 sm:col-span-2"><button type="button" onClick={onClose} className="rounded border px-4 py-2 text-sm">Cancel</button><button disabled={busy} className="rounded bg-slate-900 px-4 py-2 text-sm text-white">{busy?'Saving...':text}</button></div>}
function Field({name,label,type='text',defaultValue,required=false}:{name:string;label:string;type?:string;defaultValue?:string;required?:boolean}){return <label className="text-sm">{label}{required&&' *'}<input name={name} type={type} defaultValue={defaultValue} required={required} className="mt-1 w-full rounded border px-3 py-2"/></label>}
function Select({name,label,options}:{name:string;label:string;options:string[][]}){return <label className="text-sm">{label}<select name={name} className="mt-1 w-full rounded border px-3 py-2">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
