'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';

function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
function req(fd: FormData, key: string) { const v=String(fd.get(key)??'').trim(); if(!v) throw appError(`${key.replaceAll('_',' ')} is required.`); return v; }
function opt(fd: FormData,key:string){const v=String(fd.get(key)??'').trim();return v||null;}
async function admin(){const p=await getSessionProfile();if(!p||!p.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.section_code!=='admin'&&!p.access.some(a=>a.section_code==='admin'))throw appError('Admin access required.');return p;}
async function audit(actor:string,id:string,action:string,detail:Record<string,unknown>){const db=createClient();const {error}=await db.from('audit_log').insert({actor_id:actor,entity_table:'supplies',entity_id:id,action,detail});if(error)throw appError(error.message);}
function qty(fd:FormData){const n=Number(req(fd,'quantity'));if(!Number.isFinite(n)||n<=0)throw appError('Quantity must be greater than zero.');return n;}

export async function createSupplyCategoryAction(fd:FormData){const p=await admin();const db=createClient();const code=req(fd,'code').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');const name=req(fd,'name');const {data,error}=await db.from('supply_categories').insert({code,name,description:opt(fd,'description')}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create category.');await audit(p.user.id,data.id,'category_created',{code,name});revalidatePath('/admin/supplies');return {ok:true};}
export async function createSupplyAction(fd:FormData){const p=await admin();const db=createClient();const stock=Number(opt(fd,'opening_stock')||0);const reorder=Number(opt(fd,'reorder_level')||0);const cost=opt(fd,'unit_cost');if(!Number.isFinite(stock)||stock<0||!Number.isFinite(reorder)||reorder<0)throw appError('Stock and reorder level must be zero or greater.');if(cost!==null&&(!Number.isFinite(Number(cost))||Number(cost)<0))throw appError('Unit cost must be zero or greater.');
  // U025/U029 — optional links into Procurement's shared supplier master
  // and the PO/receipt this supply item was actually acquired through,
  // alongside the existing free-text `supplier` fallback (same pattern as U004).
  const payload={...biz(p),item_code:req(fd,'item_code').toUpperCase(),name:req(fd,'name'),category_id:req(fd,'category_id'),description:opt(fd,'description'),unit:req(fd,'unit')||'piece',stock_on_hand:stock,reorder_level:reorder,location:opt(fd,'location'),supplier:opt(fd,'supplier'),supplier_id:opt(fd,'supplier_id'),source_po_id:opt(fd,'source_po_id'),source_receipt_id:opt(fd,'source_receipt_id'),unit_cost:cost?Number(cost):null,created_by:p.user.id};const {data,error}=await db.from('supplies').insert(payload).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create supply item.');if(stock>0){const {error:te}=await db.from('supply_transactions').insert({...biz(p),supply_id:data.id,transaction_type:'receive',quantity:stock,balance_after:stock,notes:'Opening stock',performed_by:p.user.id});if(te)throw appError(te.message);}await audit(p.user.id,data.id,'created',{item_code:payload.item_code,name:payload.name,opening_stock:stock});revalidatePath('/admin/supplies');return {ok:true};}
export async function updateSupplyAction(fd:FormData){const p=await admin();const db=createClient();const id=req(fd,'supply_id');const {error}=await db.from('supplies').update({item_code:req(fd,'item_code').toUpperCase(),name:req(fd,'name'),category_id:req(fd,'category_id'),description:opt(fd,'description'),unit:req(fd,'unit')||'piece',reorder_level:Number(opt(fd,'reorder_level')||0),location:opt(fd,'location'),supplier:opt(fd,'supplier'),supplier_id:opt(fd,'supplier_id'),unit_cost:opt(fd,'unit_cost')?Number(opt(fd,'unit_cost')):null,active:fd.get('active')==='on'}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'edited',{name:String(fd.get('name')??'')});revalidatePath('/admin/supplies');return {ok:true};}
export async function transactSupplyAction(fd:FormData){const p=await admin();const db=createClient();const id=req(fd,'supply_id');const type=req(fd,'transaction_type');if(!['receive','issue','adjust_in','adjust_out'].includes(type))throw appError('Invalid transaction type.');const n=qty(fd);const {data:supply}=await db.from('supplies').select('id,stock_on_hand,name').eq('id',id).maybeSingle();if(!supply)throw appError('Supply item not found.');const current=Number(supply.stock_on_hand);const incoming=type==='receive'||type==='adjust_in';const next=incoming?current+n:current-n;if(next<0)throw appError(`Insufficient stock. Available: ${current}.`);const {error:ue}=await db.from('supplies').update({stock_on_hand:next}).eq('id',id);if(ue)throw appError(ue.message);const {error:te}=await db.from('supply_transactions').insert({...biz(p),supply_id:id,transaction_type:type,quantity:n,balance_after:next,reference_type:opt(fd,'reference_type'),reference_id:opt(fd,'reference_id'),notes:opt(fd,'notes'),performed_by:p.user.id});if(te)throw appError(te.message);await audit(p.user.id,id,'stock_transaction',{type,quantity:n,balance_after:next});revalidatePath('/admin/supplies');revalidatePath('/admin/requests');return {ok:true};}
