'use client';
import { errorText } from '@/core/errors/appError';
import { useMemo,useState } from 'react';
import { ActionBar,PopupAction } from '@/core/ui/PopupAction';
import { createSupplyAction,createSupplyCategoryAction,transactSupplyAction,updateSupplyAction } from './actions';
type Cat={id:string;code:string;name:string;description?:string|null};
type Supplier={id:string;supplier_code:string;legal_name:string;trade_name?:string|null};
type Supply={id:string;item_code:string;name:string;category_id:string;description?:string|null;unit:string;stock_on_hand:number;reorder_level:number;location?:string|null;supplier?:string|null;supplier_id?:string|null;active:boolean;category?:{name:string};supplier_ref?:{supplier_code:string;legal_name:string;trade_name?:string|null}|null;unit_cost?:number|null};
type Tx={id:string;supply_id:string;transaction_type:string;quantity:number;balance_after:number;notes?:string|null;created_at:string};
const types=['receive','issue','adjust_in','adjust_out'];
const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function SuppliesManagement({categories,supplies,transactions,suppliers}:{categories:Cat[];supplies:Supply[];transactions:Tx[];suppliers:Supplier[]}){
 const [q,setQ]=useState(''),[low,setLow]=useState(false),[modal,setModal]=useState<'item'|'category'|'stock'|null>(null),[editing,setEditing]=useState<Supply|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Supply|null>(null);
 const filtered=useMemo(()=>supplies.filter(s=>{const hay=`${s.item_code} ${s.name} ${s.category?.name??''} ${s.location??''} ${s.supplier??''}`.toLowerCase();return(!q||hay.includes(q.toLowerCase()))&&(!low||Number(s.stock_on_hand)<=Number(s.reorder_level))}),[supplies,q,low]);
 async function run(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();setModal(null);setEditing(null);setSelected(null)}catch(e){setError(e instanceof Error?errorText(e):'Operation failed.')}finally{setBusy(false)}}
 // Build 65: the supply-item form is shared by the "+ New supply item" pop-up and the row-level Edit modal.
 const itemForm=(onSaved?:()=>void)=><form action={fd=>run(async()=>{await (editing?updateSupplyAction(fd):createSupplyAction(fd));onSaved?.()})} className="grid gap-3 sm:grid-cols-2">{editing&&<input type="hidden" name="supply_id" value={editing.id}/>}<Field name="item_code" label="Item Code" defaultValue={editing?.item_code}/><Field name="name" label="Name" defaultValue={editing?.name}/><Select name="category_id" label="Category" value={editing?.category_id} options={categories.map(c=>[c.id,c.name])}/><Field name="unit" label="Unit" defaultValue={editing?.unit||'piece'}/>{!editing&&<Field name="opening_stock" label="Opening Stock" type="number" defaultValue="0"/>}<Field name="reorder_level" label="Reorder Level" type="number" defaultValue={String(editing?.reorder_level??0)}/><Field name="location" label="Location" defaultValue={editing?.location??''}/><Select name="supplier_id" label="Catalog supplier (optional)" value={editing?.supplier_id??''} options={[['','— none / not a catalog supplier —'],...suppliers.map(s=>[s.id,`${s.trade_name||s.legal_name} (${s.supplier_code})`])]}/><Field name="supplier" label="Supplier (free text, if not in the list above)" defaultValue={editing?.supplier??''}/><Field name="unit_cost" label="Unit Cost" type="number" step="0.01" defaultValue={editing?.unit_cost==null?'':String(editing.unit_cost)}/><Field name="description" label="Description" defaultValue={editing?.description??''}/>{editing&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" name="active" defaultChecked={editing.active}/> Active</label>}<div className="sm:col-span-2"><Submit busy={busy}/></div></form>;
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-semibold">Office Supplies</h1><p className="text-sm text-slate-500">Track consumables, stock levels, locations and stock movements.</p></div></div>
 <ActionBar><PopupAction label="+ New supply item" title="New Supply Item" notice={error} onOpen={()=>setEditing(null)}>{(close)=>itemForm(close)}</PopupAction><PopupAction label="+ New category" title="New Supply Category" variant="secondary" notice={error}>{(close)=><form action={fd=>run(async()=>{await createSupplyCategoryAction(fd);close()})} className="space-y-3"><Field name="code" label="Code"/><Field name="name" label="Name"/><Field name="description" label="Description"/><Submit busy={busy}/></form>}</PopupAction></ActionBar>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Items',supplies.length],['Low Stock',supplies.filter(s=>Number(s.stock_on_hand)<=Number(s.reorder_level)).length],['Units on Hand',supplies.reduce((n,s)=>n+Number(s.stock_on_hand),0)],['Active',supplies.filter(s=>s.active).length]].map(([a,b])=><div key={String(a)} className="bg-white rounded-lg border p-4"><div className="text-xs text-slate-500">{a}</div><div className="text-xl font-semibold mt-1">{b}</div></div>)}</div>
 <div className="bg-white rounded-lg border p-4 flex flex-wrap gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search item code, name, category..." className="border rounded px-3 py-2 text-sm flex-1 min-w-64"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={low} onChange={e=>setLow(e.target.checked)}/> Low stock only</label></div>
 {error&&<div className="bg-red-50 border border-red-200 text-red-700 rounded p-3 text-sm">{error}</div>}
 <div className="bg-white rounded-lg border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="text-left p-3">Item</th><th className="text-left p-3">Category</th><th className="text-right p-3">Stock</th><th className="text-right p-3">Reorder</th><th className="text-left p-3">Location</th><th className="text-left p-3">Status</th><th className="p-3"></th></tr></thead><tbody>{filtered.map(s=><tr key={s.id} className="border-t"><td className="p-3"><div className="font-medium">{s.name}</div><div className="text-xs text-slate-500">{s.item_code} · {s.unit}</div></td><td className="p-3">{s.category?.name}</td><td className={`p-3 text-right font-semibold ${Number(s.stock_on_hand)<=Number(s.reorder_level)?'text-amber-700':''}`}>{s.stock_on_hand}</td><td className="p-3 text-right">{s.reorder_level}</td><td className="p-3">{s.location||'—'}</td><td className="p-3">{s.active?'Active':'Inactive'}</td><td className="p-3"><div className="flex justify-end gap-2"><button onClick={()=>{setSelected(s);setModal('stock')}} className="text-xs px-2 py-1 rounded bg-slate-900 text-white">Stock</button><button onClick={()=>{setEditing(s);setModal('item')}} className="text-xs px-2 py-1 rounded bg-slate-100">Edit</button></div></td></tr>)}{filtered.length===0&&<tr><td colSpan={7} className="p-8 text-center text-slate-400">No supply items found.</td></tr>}</tbody></table></div>
 <div className="bg-white rounded-lg border p-4"><h2 className="font-semibold mb-3">Recent stock movements</h2><div className="divide-y">{transactions.slice(0,12).map(t=><div key={t.id} className="py-2 flex justify-between text-sm"><span><b>{label(t.transaction_type)}</b> · {supplies.find(s=>s.id===t.supply_id)?.name||'Unknown item'} · {t.quantity}</span><span className="text-slate-500">balance {t.balance_after}</span></div>)}{transactions.length===0&&<div className="text-sm text-slate-400">No movements yet.</div>}</div></div>
 {modal==='item'&&<Modal title={editing?'Edit Supply Item':'New Supply Item'} close={()=>setModal(null)}>{itemForm()}</Modal>}
 {modal==='stock'&&selected&&<Modal title={`Stock movement · ${selected.name}`} close={()=>setModal(null)}><form action={fd=>run(()=>transactSupplyAction(fd))} className="space-y-3"><input type="hidden" name="supply_id" value={selected.id}/><div className="bg-slate-50 rounded p-3 text-sm">Current stock: <b>{selected.stock_on_hand} {selected.unit}</b></div><Select name="transaction_type" label="Movement" options={types.map(x=>[x,label(x)])}/><Field name="quantity" label="Quantity" type="number" step="0.001"/><Field name="notes" label="Notes"/><Submit busy={busy}/></form></Modal>}
 </div>
}
function Field({name,label:lab,type='text',defaultValue='',step}:{name:string;label:string;type?:string;defaultValue?:string;step?:string}){return <label className="text-sm space-y-1 block"><span className="text-slate-600">{lab}</span><input name={name} required={['item_code','name'].includes(name)} type={type} step={step} defaultValue={defaultValue} className="w-full border rounded px-3 py-2"/></label>}
function Select({name,label:lab,options,value}:{name:string;label:string;options:string[][];value?:string}){return <label className="text-sm space-y-1 block"><span className="text-slate-600">{lab}</span><select name={name} defaultValue={value} className="w-full border rounded px-3 py-2">{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
function Submit({busy}:{busy:boolean}){return <button disabled={busy} className="w-full px-3 py-2 rounded bg-slate-900 text-white text-sm disabled:opacity-50">{busy?'Saving...':'Save'}</button>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4"><div className="bg-white rounded-xl shadow-xl w-full max-w-2xl max-h-[90vh] overflow-auto"><div className="p-4 border-b flex justify-between"><h2 className="font-semibold">{title}</h2><button onClick={close}>✕</button></div><div className="p-4">{children}</div></div></div>}
