'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';

function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
function req(fd: FormData, key: string) { const v=String(fd.get(key)??'').trim(); if(!v) throw appError(`${key.replaceAll('_',' ')} is required.`); return v; }
function opt(fd: FormData,key:string){const v=String(fd.get(key)??'').trim();return v||null;}
async function admin(){const p=await getSessionProfile();if(!p||!p.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.section_code!=='admin'&&!p.access.some(a=>a.section_code==='admin'))throw appError('Admin access required.');return p;}
async function audit(actor:string,id:string,table:string,action:string,detail:Record<string,unknown>){const {error}=await createClient().from('audit_log').insert({actor_id:actor,entity_table:table,entity_id:id,action,detail});if(error)throw appError(error.message);}

export async function createPolicyAction(fd:FormData){const p=await admin(),db=createClient();const {data,error}=await db.from('admin_policies').insert({...biz(p),policy_no:req(fd,'policy_no'),title:req(fd,'title'),category_id:opt(fd,'category_id'),version:req(fd,'version'),effective_date:opt(fd,'effective_date'),review_date:opt(fd,'review_date'),owner_department:opt(fd,'owner_department'),summary:opt(fd,'summary'),content:req(fd,'content'),acknowledgement_required:fd.get('acknowledgement_required')==='on',created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create policy.');await audit(p.user.id,data.id,'admin_policies','policy_created',{title:String(fd.get('title')??'')});revalidatePath('/admin/policies');return {ok:true};}
export async function updatePolicyAction(fd:FormData){const p=await admin(),db=createClient(),id=req(fd,'id');const {data:row}=await db.from('admin_policies').select('status,created_by').eq('id',id).single();if(!row)throw appError('Policy not found.');if(row.status!=='draft')throw appError('Only draft policies can be edited.');const {error}=await db.from('admin_policies').update({title:req(fd,'title'),category_id:opt(fd,'category_id'),version:req(fd,'version'),effective_date:opt(fd,'effective_date'),review_date:opt(fd,'review_date'),owner_department:opt(fd,'owner_department'),summary:opt(fd,'summary'),content:req(fd,'content'),acknowledgement_required:fd.get('acknowledgement_required')==='on',updated_at:new Date().toISOString()}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'admin_policies','policy_edited',{});revalidatePath('/admin/policies');return {ok:true};}
export async function publishPolicyAction(id:string){const p=await admin(),db=createClient();const {data:row}=await db.from('admin_policies').select('status').eq('id',id).single();if(!row||row.status!=='draft')throw appError('Only draft policies can be published.');const {error}=await db.from('admin_policies').update({status:'published',published_at:new Date().toISOString(),published_by:p.user.id,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'admin_policies','policy_published',{});revalidatePath('/admin/policies');revalidatePath('/dashboard');return {ok:true};}
export async function archivePolicyAction(id:string){const p=await admin(),db=createClient();const {error}=await db.from('admin_policies').update({status:'archived',archived_at:new Date().toISOString(),archived_by:p.user.id,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'admin_policies','policy_archived',{});revalidatePath('/admin/policies');return {ok:true};}
export async function acknowledgePolicyAction(id:string){const p=await getSessionProfile();if(!p?.user.is_active)throw appError('Authentication required.');const db=createClient();const {data:policy}=await db.from('admin_policies').select('id,status,acknowledgement_required').eq('id',id).single();if(!policy||policy.status!=='published'||!policy.acknowledgement_required)throw appError('Policy does not require acknowledgement.');const {error}=await db.from('admin_policy_acknowledgements').upsert({policy_id:id,user_id:p.user.id},{onConflict:'policy_id,user_id'});if(error)throw appError(error.message);await audit(p.user.id,id,'admin_policy_acknowledgements','policy_acknowledged',{});revalidatePath('/admin/policies');return {ok:true};}

export async function createAnnouncementAction(fd:FormData){const p=await admin(),db=createClient();const {data,error}=await db.from('admin_announcements').insert({...biz(p),announcement_no:req(fd,'announcement_no'),title:req(fd,'title'),priority:req(fd,'priority'),audience:req(fd,'audience'),summary:opt(fd,'summary'),content:req(fd,'content'),publish_from:opt(fd,'publish_from'),publish_until:opt(fd,'publish_until'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create announcement.');await audit(p.user.id,data.id,'admin_announcements','announcement_created',{title:String(fd.get('title')??'')});revalidatePath('/admin/policies');return {ok:true};}
export async function publishAnnouncementAction(id:string){const p=await admin(),db=createClient();const {error}=await db.from('admin_announcements').update({status:'published',published_at:new Date().toISOString(),published_by:p.user.id,updated_at:new Date().toISOString()}).eq('id',id).eq('status','draft');if(error)throw appError(error.message);await audit(p.user.id,id,'admin_announcements','announcement_published',{});revalidatePath('/admin/policies');revalidatePath('/dashboard');return {ok:true};}
export async function archiveAnnouncementAction(id:string){const p=await admin(),db=createClient();const {error}=await db.from('admin_announcements').update({status:'archived',archived_at:new Date().toISOString(),archived_by:p.user.id,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'admin_announcements','announcement_archived',{});revalidatePath('/admin/policies');return {ok:true};}
