'use client';
import { Form } from '@/core/ui/Form';
import { errorText } from '@/core/errors/appError';
import {useMemo, useState, useTransition} from 'react';
import {createCommissionPayoutAction, transitionCommissionAction, transitionCommissionPayoutAction} from './revenueActions';
import {useDialog} from '@/core/ui/Dialog';
import { ActionBar, PopupAction } from '@/core/ui/PopupAction';
const money=(v:any)=>`₱${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const name=(e:any)=>e?`${e.employee_no||''} — ${e.first_name||''} ${e.last_name||''}`.trim():'Unassigned';
function Card({title,children}:{title:string;children:any}){return <section className="rounded-xl border bg-white shadow-sm"><div className="border-b px-4 py-3 font-semibold">{title}</div><div className="p-4">{children}</div></section>}
function Badge({s}:{s:string}){return <span className="inline-flex rounded-full bg-slate-100 px-2 py-1 text-xs capitalize">{String(s).replaceAll('_',' ')}</span>}
function Field({l,children}:{l:string;children:any}){return <div><label className="label">{l}</label>{children}</div>}
export default function CommissionOperationsManagement({commissions,payouts,employees,summary}:{commissions:any[];payouts:any[];employees:any[];summary:any[]}){
 const dialog=useDialog();
 const [pending,start]=useTransition(); const [employee,setEmployee]=useState('all'); const [status,setStatus]=useState('all');
 const filtered=useMemo(()=>commissions.filter(c=>(employee==='all'||c.employee_id===employee)&&(status==='all'||c.status===status)),[commissions,employee,status]);
 const totals=filtered.reduce((a,c)=>({count:a.count+1,amount:a.amount+Number(c.commission_amount||0),approved:a.approved+(c.status==='approved'||c.status==='paid'?Number(c.commission_amount||0):0),paid:a.paid+(c.status==='paid'?Number(c.commission_amount||0):0)}),{count:0,amount:0,approved:0,paid:0});
 const run=(f:()=>Promise<any>)=>start(()=>f().catch(e=>dialog.alert(errorText(e),{tone:'danger',title:'Action failed'})));
 return <div className="space-y-5">
  <ActionBar><PopupAction label="+ Create payout batch" title="Create commission payout batch" wide>{(close)=><Form action={fd=>run(async()=>{await createCommissionPayoutAction(fd);close()})} className="grid md:grid-cols-5 gap-3"><Field l="Payout no."><input className="input" name="payout_number" placeholder="CP-2026-001" required/></Field><Field l="Employee"><select className="input" name="employee_id"><option value="">All / unassigned</option>{employees.map(e=><option key={e.id} value={e.id}>{name(e)}</option>)}</select></Field><Field l="Period start"><input className="input" type="date" name="period_start" required/></Field><Field l="Period end"><input className="input" type="date" name="period_end" required/></Field><Field l="Adjustments"><input className="input" type="number" step="0.01" name="adjustments" defaultValue="0"/></Field><div className="md:col-span-5"><Field l="Notes"><input className="input" name="notes"/></Field></div><div className="md:col-span-5"><button className="button" disabled={pending}>Create payout batch</button></div></Form>}</PopupAction></ActionBar>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Commission records',totals.count],['Accrued',money(totals.amount)],['Approved',money(totals.approved)],['Paid',money(totals.paid)]].map(([l,v])=><div key={String(l)} className="rounded-xl border bg-white p-4"><div className="text-sm text-slate-500">{l}</div><div className="text-xl font-semibold">{v}</div></div>)}</div>
  <Card title="Commission operations"><div className="grid md:grid-cols-2 gap-3 mb-4"><Field l="Employee"><select className="input" value={employee} onChange={e=>setEmployee(e.target.value)}><option value="all">All employees</option>{employees.map(e=><option key={e.id} value={e.id}>{name(e)}</option>)}</select></Field><Field l="Status"><select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{['draft','prepared','reviewed','approved','paid','cancelled'].map(s=><option key={s}>{s}</option>)}</select></Field></div>
   <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">Commission</th><th className="p-3">Employee</th><th className="p-3">Order</th><th className="p-3">Base</th><th className="p-3">Rate</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id} className="border-b"><td className="p-3 font-medium">{c.commission_number}</td><td className="p-3">{name(c.employee)}</td><td className="p-3">{c.order?.order_number||'—'}</td><td className="p-3">{money(c.commission_base)}</td><td className="p-3">{c.commission_rate}%</td><td className="p-3">{money(c.commission_amount)}</td><td className="p-3"><Badge s={c.status}/></td><td className="p-3 flex gap-1 flex-wrap">{c.status==='draft'&&<button className="button-sm" disabled={pending} onClick={()=>run(()=>transitionCommissionAction(c.id,'prepared'))}>Prepare</button>}{c.status==='prepared'&&<button className="button-sm" disabled={pending} onClick={()=>run(()=>transitionCommissionAction(c.id,'reviewed'))}>Review</button>}{c.status==='reviewed'&&<button className="button-sm" disabled={pending} onClick={()=>run(()=>transitionCommissionAction(c.id,'approved'))}>Approve</button>}{c.status==='approved'&&<button className="button-sm" disabled={pending} onClick={()=>run(()=>transitionCommissionAction(c.id,'paid'))}>Mark paid</button>}</td></tr>)}</tbody></table>{!filtered.length&&<div className="p-6 text-center text-slate-400">No commission records match the filters.</div>}</div>
  </Card>
  <Card title="Payout batches"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">Payout</th><th className="p-3">Employee</th><th className="p-3">Period</th><th className="p-3">Gross</th><th className="p-3">Adjustments</th><th className="p-3">Net</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{payouts.map(p=><tr key={p.id} className="border-b"><td className="p-3 font-medium">{p.payout_number}</td><td className="p-3">{name(p.employee)}</td><td className="p-3">{p.period_start} → {p.period_end}</td><td className="p-3">{money(p.gross_commission)}</td><td className="p-3">{money(p.adjustments)}</td><td className="p-3">{money(p.net_commission)}</td><td className="p-3"><Badge s={p.status}/></td><td className="p-3 flex gap-1 flex-wrap">{p.status==='draft'&&<button className="button-sm" onClick={()=>run(()=>transitionCommissionPayoutAction(p.id,'prepared'))}>Prepare</button>}{p.status==='prepared'&&<button className="button-sm" onClick={()=>run(()=>transitionCommissionPayoutAction(p.id,'reviewed'))}>Review</button>}{p.status==='reviewed'&&<button className="button-sm" onClick={()=>run(()=>transitionCommissionPayoutAction(p.id,'approved'))}>Approve</button>}{p.status==='approved'&&<button className="button-sm" onClick={()=>run(()=>transitionCommissionPayoutAction(p.id,'paid'))}>Mark paid</button>}</td></tr>)}</tbody></table>{!payouts.length&&<div className="p-6 text-center text-slate-400">No payout batches yet.</div>}</div></Card>
  <Card title="Monthly commission reporting"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">Period</th><th className="p-3">Employee</th><th className="p-3">Count</th><th className="p-3">Accrued</th><th className="p-3">Prepared</th><th className="p-3">Reviewed</th><th className="p-3">Approved</th><th className="p-3">Paid</th><th className="p-3">Open</th></tr></thead><tbody>{summary.map(s=><tr key={s.id} className="border-b"><td className="p-3">{s.year}-{String(s.month).padStart(2,'0')}</td><td className="p-3">{name(s.employee)}</td><td className="p-3">{s.commission_count}</td><td className="p-3">{money(s.accrued)}</td><td className="p-3">{money(s.prepared)}</td><td className="p-3">{money(s.reviewed)}</td><td className="p-3">{money(s.approved)}</td><td className="p-3">{money(s.paid)}</td><td className="p-3">{money(s.open_amount)}</td></tr>)}</tbody></table>{!summary.length&&<div className="p-6 text-center text-slate-400">No monthly summary has been generated yet.</div>}</div></Card>
 </div>
}
