'use server';
import { appError } from '@/core/errors/appError';

import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';

function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
type AssetStatus = 'available'|'assigned'|'maintenance'|'retired'|'disposed'|'lost';
type AssetCondition = 'new'|'good'|'fair'|'needs_repair'|'damaged';
const STATUSES: AssetStatus[] = ['available','assigned','maintenance','retired','disposed','lost'];
const CONDITIONS: AssetCondition[] = ['new','good','fair','needs_repair','damaged'];
function req(fd: FormData,k:string){const v=String(fd.get(k)??'').trim();if(!v)throw appError(`${k.replaceAll('_',' ')} is required.`);return v;}
function opt(fd: FormData,k:string){const v=String(fd.get(k)??'').trim();return v||null;}
function en<T extends string>(v:string,a:T[],label:string): asserts v is T{if(!a.includes(v as T))throw appError(`Invalid ${label}.`)}
async function admin(){const p=await getSessionProfile();if(!p||!p.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.section_code!=='admin'&&!p.access.some(a=>a.section_code==='admin'))throw appError('Admin access required.');return p;}
async function audit(actor:string,id:string,action:string,detail:Record<string,unknown>){const db=createClient();const {error}=await db.from('audit_log').insert({actor_id:actor,entity_table:'assets',entity_id:id,action,detail});if(error)throw appError(error.message);}

export async function createAssetCategoryAction(fd:FormData){const p=await admin();const db=createClient();const code=req(fd,'code').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');const name=req(fd,'name');const {data,error}=await db.from('asset_categories').insert({code,name,description:opt(fd,'description')}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create asset category.');await audit(p.user.id,data.id,'category_created',{code,name});revalidatePath('/admin/assets');return {ok:true};}

export async function createAssetAction(fd:FormData){const p=await admin();const db=createClient();const categoryId=req(fd,'category_id');const purchaseCost=opt(fd,'purchase_cost');if(purchaseCost!==null&&(Number.isNaN(Number(purchaseCost))||Number(purchaseCost)<0))throw appError('Purchase cost must be zero or greater.');
  // U031 — asset_no is no longer taken from the form: the DB default +
  // guard_asset_no() trigger generates AST-#### on insert and locks it.
  // U025/U029 — optional links into Procurement: a catalog supplier and/or
  // the PO/receipt this asset was actually acquired through, alongside the
  // existing free-text `supplier` fallback (same pattern as expenses.supplier_id, U004).
  const payload={...biz(p),category_id:categoryId,name:req(fd,'name'),description:opt(fd,'description'),serial_number:opt(fd,'serial_number'),manufacturer:opt(fd,'manufacturer'),model:opt(fd,'model'),purchase_date:opt(fd,'purchase_date'),purchase_cost:purchaseCost?Number(purchaseCost):null,supplier:opt(fd,'supplier'),supplier_id:opt(fd,'supplier_id'),source_po_id:opt(fd,'source_po_id'),source_receipt_id:opt(fd,'source_receipt_id'),warranty_until:opt(fd,'warranty_until'),location:opt(fd,'location'),condition:(opt(fd,'condition')||'new') as AssetCondition,status:'available' as AssetStatus,notes:opt(fd,'notes'),created_by:p.user.id};en(payload.condition,CONDITIONS,'condition');const {data,error}=await db.from('assets').insert(payload).select('id,asset_no').single();if(error||!data)throw appError(error?.message||'Unable to create asset.');await audit(p.user.id,data.id,'created',{asset_no:(data as any).asset_no,name:payload.name,category_id:categoryId});revalidatePath('/admin/assets');return {ok:true,asset_no:(data as any).asset_no};}

export async function updateAssetAction(fd:FormData){const p=await admin();const db=createClient();const id=req(fd,'asset_id');const condition=req(fd,'condition');en(condition,CONDITIONS,'condition');const status=req(fd,'status');en(status,STATUSES,'status');if(status==='assigned')throw appError('Use Assign Asset to assign an asset to an employee.');if(status==='retired')throw appError('Use Retire Asset to retire an asset (a reason is required).');if(status==='disposed')throw appError('Use Dispose Asset to dispose an asset (a disposal date is required).');const {error}=await db.from('assets').update({name:req(fd,'name'),description:opt(fd,'description'),category_id:req(fd,'category_id'),serial_number:opt(fd,'serial_number'),manufacturer:opt(fd,'manufacturer'),model:opt(fd,'model'),purchase_date:opt(fd,'purchase_date'),purchase_cost:opt(fd,'purchase_cost')?Number(opt(fd,'purchase_cost')):null,supplier:opt(fd,'supplier'),supplier_id:opt(fd,'supplier_id'),warranty_until:opt(fd,'warranty_until'),location:opt(fd,'location'),condition,status,notes:opt(fd,'notes')}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'edited',{status,condition});revalidatePath('/admin/assets');return {ok:true};}

// U027 — retiring/disposing an asset now goes through its own action with a
// required reason (retire) / disposal date (dispose), rather than a bare
// status dropdown; guard_asset_status_transition() enforces the same rule
// at the DB layer so no other code path can bypass it either.
export async function retireAssetAction(fd:FormData){const p=await admin();const db=createClient();const id=req(fd,'asset_id');const reason=req(fd,'retirement_reason');const {data:asset}=await db.from('assets').select('id,status').eq('id',id).maybeSingle();if(!asset)throw appError('Asset not found.');if(asset.status==='disposed')throw appError('A disposed asset cannot change status further.');if(asset.status==='assigned')throw appError('Return the active assignment before retiring this asset.');const {error}=await db.from('assets').update({status:'retired',retirement_reason:reason}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'retired',{reason});revalidatePath('/admin/assets');return {ok:true};}

export async function disposeAssetAction(fd:FormData){const p=await admin();const db=createClient();const id=req(fd,'asset_id');const disposalDate=req(fd,'disposal_date');const disposalValue=opt(fd,'disposal_value');if(disposalValue!==null&&(Number.isNaN(Number(disposalValue))||Number(disposalValue)<0))throw appError('Disposal value must be zero or greater.');const {data:asset}=await db.from('assets').select('id,status').eq('id',id).maybeSingle();if(!asset)throw appError('Asset not found.');if(asset.status==='disposed')throw appError('This asset is already disposed.');if(asset.status==='assigned')throw appError('Return the active assignment before disposing this asset.');const {error}=await db.from('assets').update({status:'disposed',disposal_date:disposalDate,disposal_value:disposalValue?Number(disposalValue):null}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'disposed',{disposal_date:disposalDate});revalidatePath('/admin/assets');return {ok:true};}

// U030 — Asset Maintenance History for general (non-fleet) assets, mirroring
// fleet_maintenance's create-and-return-to-available pattern.
export async function createAssetMaintenanceAction(fd:FormData){const p=await admin();const db=createClient();const assetId=req(fd,'asset_id');const cost=opt(fd,'cost');if(cost!==null&&(Number.isNaN(Number(cost))||Number(cost)<0))throw appError('Cost must be zero or greater.');const {data,error}=await db.from('asset_maintenance').insert({...biz(p),asset_id:assetId,service_date:req(fd,'service_date'),service_type:req(fd,'service_type'),description:req(fd,'description'),vendor:opt(fd,'vendor'),cost:cost?Number(cost):null,next_service_date:opt(fd,'next_service_date'),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create maintenance record.');const {data:asset}=await db.from('assets').select('status').eq('id',assetId).maybeSingle();if(asset?.status==='maintenance'){const {error:ue}=await db.from('assets').update({status:'available'}).eq('id',assetId);if(ue)throw appError(ue.message);}await audit(p.user.id,data.id,'maintenance_recorded',{asset_id:assetId});revalidatePath('/admin/assets');return {ok:true};}

export async function assignAssetAction(fd:FormData){const p=await admin();const db=createClient();const assetId=req(fd,'asset_id');const employeeId=req(fd,'employee_id');const {data:asset}=await db.from('assets').select('id,status').eq('id',assetId).maybeSingle();if(!asset)throw appError('Asset not found.');if(asset.status!=='available')throw appError('Only available assets can be assigned.');const {data:employee}=await db.from('employees').select('id,employment_status').eq('id',employeeId).maybeSingle();if(!employee||employee.employment_status==='separated')throw appError('Employee is not eligible for an assignment.');const {data,error}=await db.from('asset_assignments').insert({...biz(p),asset_id:assetId,employee_id:employeeId,issued_condition:(opt(fd,'issued_condition')||'good') as AssetCondition,expected_return_date:opt(fd,'expected_return_date'),assignment_notes:opt(fd,'assignment_notes'),assigned_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to assign asset.');const {error:ae}=await db.from('assets').update({status:'assigned'}).eq('id',assetId);if(ae)throw appError(ae.message);await audit(p.user.id,assetId,'assigned',{employee_id:employeeId,assignment_id:data.id});revalidatePath('/admin/assets');return {ok:true};}

export async function returnAssetAction(fd:FormData){const p=await admin();const db=createClient();const assetId=req(fd,'asset_id');const {data:assignment}=await db.from('asset_assignments').select('id,employee_id').eq('asset_id',assetId).is('returned_at',null).maybeSingle();if(!assignment)throw appError('No active assignment found.');const condition=req(fd,'returned_condition');en(condition,CONDITIONS,'returned condition');const {error}=await db.from('asset_assignments').update({returned_at:new Date().toISOString(),returned_condition:condition,returned_by:p.user.id,assignment_notes:opt(fd,'return_notes')}).eq('id',assignment.id);if(error)throw appError(error.message);const {error:ae}=await db.from('assets').update({status:'available',condition,location:opt(fd,'location')}).eq('id',assetId);if(ae)throw appError(ae.message);await audit(p.user.id,assetId,'returned',{employee_id:assignment.employee_id,assignment_id:assignment.id,condition});revalidatePath('/admin/assets');return {ok:true};}

export async function setAssetStatusAction(fd:FormData){const p=await admin();const db=createClient();const id=req(fd,'asset_id');const status=req(fd,'status');en(status,STATUSES,'status');if(status==='assigned')throw appError('Use Assign Asset to assign an asset.');if(status==='available'){const {data:a}=await db.from('asset_assignments').select('id').eq('asset_id',id).is('returned_at',null).maybeSingle();if(a)throw appError('Return the active assignment before marking the asset available.');}const {error}=await db.from('assets').update({status}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'status_changed',{status});revalidatePath('/admin/assets');return {ok:true};}
