'use client';
import { Form } from '@/core/ui/Form';
import { errorText } from '@/core/errors/appError';
import { useMemo,useState,type ReactNode } from 'react';
import { assignAssetAction,createAssetAction,createAssetCategoryAction,createAssetMaintenanceAction,disposeAssetAction,returnAssetAction,retireAssetAction,setAssetStatusAction,updateAssetAction } from './actions';

type Cat={id:string;code:string;name:string;description?:string|null};
type Emp={id:string;employee_no:string;first_name:string;last_name:string;preferred_name?:string|null;employment_status:string};
type Supplier={id:string;supplier_code:string;legal_name:string;trade_name?:string|null};
type AssignmentRow={id:string;employee_id:string;assigned_at:string;returned_at?:string|null;expected_return_date?:string|null;issued_condition:string;returned_condition?:string|null;employee?:{employee_no:string;first_name:string;last_name:string;preferred_name?:string|null}};
type MaintenanceRow={id:string;asset_id:string;service_date:string;service_type:string;description:string;vendor?:string|null;cost?:number|null;next_service_date?:string|null;notes?:string|null};
type Asset={id:string;asset_no:string;category_id:string;name:string;description?:string|null;serial_number?:string|null;manufacturer?:string|null;model?:string|null;purchase_date?:string|null;purchase_cost?:number|null;supplier?:string|null;supplier_id?:string|null;source_po_id?:string|null;source_receipt_id?:string|null;warranty_until?:string|null;location?:string|null;condition:string;status:string;notes?:string|null;retirement_reason?:string|null;disposal_date?:string|null;disposal_value?:number|null;category?:{name:string};supplier_ref?:{supplier_code:string;legal_name:string;trade_name?:string|null}|null;active_assignment?:AssignmentRow|null;assignment_history?:AssignmentRow[]};
const statuses=['available','assigned','maintenance','retired','disposed','lost']; const conditions=['new','good','fair','needs_repair','damaged'];
function label(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function money(n?:number|null){return n==null?'—':`₱${Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}

export default function AssetsManagement({categories,assets,employees,suppliers,maintenance}:{categories:Cat[];assets:Asset[];employees:Emp[];suppliers:Supplier[];maintenance:MaintenanceRow[]}){
 const [view,setView]=useState<'list'|'dashboard'>('list');
 const [q,setQ]=useState(''),[status,setStatus]=useState('all'),[cat,setCat]=useState('all'),[modal,setModal]=useState<'asset'|'category'|'assign'|'return'|'retire'|'dispose'|'maintenance'|'history'|null>(null),[editing,setEditing]=useState<Asset|null>(null),[selected,setSelected]=useState<Asset|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const filtered=useMemo(()=>assets.filter(a=>{const hay=`${a.asset_no} ${a.name} ${a.serial_number??''} ${a.manufacturer??''} ${a.model??''} ${a.location??''} ${a.category?.name??''} ${a.active_assignment?.employee?.first_name??''} ${a.active_assignment?.employee?.last_name??''}`.toLowerCase();return(!q||hay.includes(q.toLowerCase()))&&(status==='all'||a.status===status)&&(cat==='all'||a.category_id===cat)}),[assets,q,status,cat]);
 const counts=Object.fromEntries(statuses.map(s=>[s,assets.filter(a=>a.status===s).length]));
 const maintenanceByAsset=useMemo(()=>{const m=new Map<string,MaintenanceRow[]>();for(const row of maintenance){const l=m.get(row.asset_id)??[];l.push(row);m.set(row.asset_id,l);}return m;},[maintenance]);
 async function run(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();setModal(null);setEditing(null);setSelected(null)}catch(e){setError(e instanceof Error?errorText(e):'Operation failed.')}finally{setBusy(false)}}
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Assets & Equipment</h1><p className="text-sm text-slate-500">Track company property, assignments, condition and lifecycle.</p></div>
 <div className="flex rounded border bg-white text-sm"><button onClick={()=>setView('list')} className={`px-3 py-1.5 ${view==='list'?'bg-slate-900 text-white':''}`}>List</button><button onClick={()=>setView('dashboard')} className={`px-3 py-1.5 ${view==='dashboard'?'bg-slate-900 text-white':''}`}>Dashboard</button></div></div>
 {error&&<div className="rounded border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 {view==='dashboard'?<AssetDashboard assets={assets} categories={categories} maintenance={maintenance}/>:<>
 <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{statuses.map(s=><Stat key={s} label={label(s)} value={counts[s]??0}/>)}</div>
 <div className="flex flex-wrap gap-2"><button onClick={()=>setModal('asset')} className="rounded bg-slate-900 px-4 py-2 text-sm font-medium text-white">Add asset</button><button onClick={()=>setModal('category')} className="rounded border px-4 py-2 text-sm">Add category</button></div>
 <div className="rounded-xl border bg-white"><div className="flex flex-wrap gap-3 border-b p-4"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search asset, serial, employee..." className="min-w-64 flex-1 rounded border px-3 py-2 text-sm"/><select value={cat} onChange={e=>setCat(e.target.value)} className="rounded border px-3 py-2 text-sm"><option value="all">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded border px-3 py-2 text-sm"><option value="all">All statuses</option>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div>
 <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-4 py-3">Asset</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Serial / Model</th><th className="px-4 py-3">Supplier</th><th className="px-4 py-3">Assignment</th><th className="px-4 py-3">Condition</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y">{filtered.map(a=><tr key={a.id}><td className="px-4 py-3"><div className="font-medium">{a.asset_no}</div><div>{a.name}</div></td><td className="px-4 py-3">{a.category?.name??'—'}</td><td className="px-4 py-3"><div>{a.serial_number||'—'}</div><div className="text-xs text-slate-500">{[a.manufacturer,a.model].filter(Boolean).join(' ')}</div></td><td className="px-4 py-3">{a.supplier_ref?(a.supplier_ref.trade_name||a.supplier_ref.legal_name):(a.supplier||'—')}</td><td className="px-4 py-3">{a.active_assignment?.employee?`${a.active_assignment.employee.employee_no} — ${a.active_assignment.employee.preferred_name||`${a.active_assignment.employee.first_name} ${a.active_assignment.employee.last_name}`}`:'Unassigned'}</td><td className="px-4 py-3">{label(a.condition)}</td><td className="px-4 py-3">{label(a.status)}</td><td className="px-4 py-3 whitespace-nowrap space-x-2">
   <button onClick={()=>{setEditing(a);setModal('asset')}} className="text-blue-700 hover:underline">Edit</button>
   <button onClick={()=>{setSelected(a);setModal('history')}} className="text-slate-700 hover:underline">History</button>
   {a.status==='available'&&<button onClick={()=>{setSelected(a);setModal('assign')}} className="text-green-700 hover:underline">Assign</button>}
   {a.status==='assigned'&&<button onClick={()=>{setSelected(a);setModal('return')}} className="text-amber-700 hover:underline">Return</button>}
   {a.status!=='assigned'&&a.status!=='disposed'&&a.status!=='retired'&&<button onClick={()=>run(()=>{const f=new FormData();f.set('asset_id',a.id);f.set('status',a.status==='maintenance'?'available':'maintenance');return setAssetStatusAction(f)})} disabled={busy} className="text-slate-700 hover:underline">{a.status==='maintenance'?'Available':'Maintenance'}</button>}
   {a.status==='maintenance'&&<button onClick={()=>{setSelected(a);setModal('maintenance')}} className="text-purple-700 hover:underline">Log service</button>}
   {a.status!=='disposed'&&a.status!=='retired'&&a.status!=='assigned'&&<button onClick={()=>{setSelected(a);setModal('retire')}} className="text-orange-700 hover:underline">Retire</button>}
   {a.status!=='disposed'&&a.status!=='assigned'&&<button onClick={()=>{setSelected(a);setModal('dispose')}} className="text-red-700 hover:underline">Dispose</button>}
 </td></tr>)}{filtered.length===0&&<tr><td colSpan={8} className="px-4 py-10 text-center text-slate-500">No assets found.</td></tr>}</tbody></table></div></div>
 {modal==='asset'&&<AssetForm categories={categories} suppliers={suppliers} asset={editing} busy={busy} onClose={()=>{setModal(null);setEditing(null)}} onSubmit={fd=>run(()=>editing?updateAssetAction(fd):createAssetAction(fd))}/>}
 {modal==='category'&&<CategoryForm busy={busy} onClose={()=>setModal(null)} onSubmit={fd=>run(()=>createAssetCategoryAction(fd))}/>}
 {modal==='assign'&&selected&&<AssignForm employees={employees} busy={busy} onClose={()=>setModal(null)} onSubmit={fd=>{fd.set('asset_id',selected.id);return run(()=>assignAssetAction(fd))}}/>}
 {modal==='return'&&selected&&<ReturnForm busy={busy} onClose={()=>setModal(null)} onSubmit={fd=>{fd.set('asset_id',selected.id);return run(()=>returnAssetAction(fd))}}/>}
 {modal==='retire'&&selected&&<RetireForm busy={busy} onClose={()=>setModal(null)} onSubmit={fd=>{fd.set('asset_id',selected.id);return run(()=>retireAssetAction(fd))}}/>}
 {modal==='dispose'&&selected&&<DisposeForm busy={busy} onClose={()=>setModal(null)} onSubmit={fd=>{fd.set('asset_id',selected.id);return run(()=>disposeAssetAction(fd))}}/>}
 {modal==='maintenance'&&selected&&<MaintenanceForm busy={busy} onClose={()=>setModal(null)} onSubmit={fd=>{fd.set('asset_id',selected.id);return run(()=>createAssetMaintenanceAction(fd))}}/>}
 {modal==='history'&&selected&&<HistoryModal asset={selected} maintenance={maintenanceByAsset.get(selected.id)??[]} onClose={()=>{setModal(null);setSelected(null)}}/>}
 </>}
 </div>
}
function Stat({label,value}:{label:string;value:number|string}){return <div className="rounded-lg border bg-white p-4"><div className="text-xs uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>}

// U032 — Asset Dashboard: utilization, value, maintenance-due and
// per-category breakdown, computed from the same data the list view
// already has (no separate route/query needed).
function AssetDashboard({assets,categories,maintenance}:{assets:Asset[];categories:Cat[];maintenance:MaintenanceRow[]}){
 const total=assets.length;
 const active=assets.filter(a=>a.status!=='retired'&&a.status!=='disposed').length;
 const assigned=assets.filter(a=>a.status==='assigned').length;
 const utilization=active?Math.round((assigned/active)*100):0;
 const totalValue=assets.reduce((s,a)=>s+(a.purchase_cost??0),0);
 const bookValue=assets.filter(a=>a.status!=='disposed').reduce((s,a)=>s+(a.purchase_cost??0),0);
 const inMaintenance=assets.filter(a=>a.status==='maintenance').length;
 const today=new Date().toISOString().slice(0,10);
 const dueSoon=maintenance.filter(m=>m.next_service_date&&m.next_service_date<=today).length;
 const byCategory=categories.map(c=>{const rows=assets.filter(a=>a.category_id===c.id);return {name:c.name,count:rows.length,value:rows.reduce((s,a)=>s+(a.purchase_cost??0),0),assigned:rows.filter(a=>a.status==='assigned').length};}).filter(r=>r.count>0);
 return <div className="space-y-6">
 <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-5">
   <Stat label="Total assets" value={total}/>
   <Stat label="Utilization (assigned / active)" value={`${utilization}%`}/>
   <Stat label="Total acquisition value" value={money(totalValue)}/>
   <Stat label="Current book value (excl. disposed)" value={money(bookValue)}/>
   <Stat label="Maintenance due / in progress" value={`${dueSoon} due · ${inMaintenance} in service`}/>
 </div>
 <div className="rounded-xl border bg-white"><div className="border-b p-4 font-medium">By category</div>
 <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-4 py-3">Category</th><th className="px-4 py-3">Count</th><th className="px-4 py-3">Assigned</th><th className="px-4 py-3">Acquisition value</th></tr></thead><tbody className="divide-y">{byCategory.map(r=><tr key={r.name}><td className="px-4 py-3">{r.name}</td><td className="px-4 py-3">{r.count}</td><td className="px-4 py-3">{r.assigned}</td><td className="px-4 py-3">{money(r.value)}</td></tr>)}{byCategory.length===0&&<tr><td colSpan={4} className="px-4 py-10 text-center text-slate-500">No assets yet.</td></tr>}</tbody></table></div></div>
 </div>
}

function AssetForm({categories,suppliers,asset,busy,onClose,onSubmit}:{categories:Cat[];suppliers:Supplier[];asset:Asset|null;busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>Promise<any>|void}){return <Modal title={asset?'Edit asset':'Add asset'} onClose={onClose}><Form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(asset)f.set('asset_id',asset.id);onSubmit(f)}} className="grid gap-4 sm:grid-cols-2">
 {asset?<div className="text-sm"><span className="text-slate-500">Asset number</span><div className="mt-1 rounded border bg-slate-50 px-3 py-2 font-mono">{asset.asset_no}</div></div>:<div className="text-sm sm:col-span-1"><span className="text-slate-500">Asset number</span><div className="mt-1 rounded border bg-slate-50 px-3 py-2 text-slate-400">Assigned automatically on save</div></div>}
 <Field name="name" label="Asset name" required defaultValue={asset?.name}/>
 <label className="text-sm">Category<select name="category_id" defaultValue={asset?.category_id} required className="mt-1 w-full rounded border px-3 py-2">{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <Field name="serial_number" label="Serial number" defaultValue={asset?.serial_number}/>
 <Field name="manufacturer" label="Manufacturer" defaultValue={asset?.manufacturer}/>
 <Field name="model" label="Model" defaultValue={asset?.model}/>
 <Field name="purchase_date" label="Purchase date" type="date" defaultValue={asset?.purchase_date}/>
 <Field name="purchase_cost" label="Purchase cost" type="number" step="0.01" defaultValue={asset?.purchase_cost?.toString()}/>
 <label className="text-sm">Catalog supplier (optional)<select name="supplier_id" defaultValue={asset?.supplier_id??''} className="mt-1 w-full rounded border px-3 py-2"><option value="">— none / not a catalog supplier —</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.trade_name||s.legal_name} ({s.supplier_code})</option>)}</select></label>
 <Field name="supplier" label="Supplier (free text, if not in the list above)" defaultValue={asset?.supplier}/>
 <Field name="warranty_until" label="Warranty until" type="date" defaultValue={asset?.warranty_until}/>
 <Field name="location" label="Location" defaultValue={asset?.location}/>
 <label className="text-sm">Condition<select name="condition" defaultValue={asset?.condition||'new'} className="mt-1 w-full rounded border px-3 py-2">{conditions.map(c=><option key={c} value={c}>{label(c)}</option>)}</select></label>
 {asset&&<label className="text-sm">Status<select name="status" defaultValue={asset.status} className="mt-1 w-full rounded border px-3 py-2">{statuses.filter(s=>s!=='assigned'&&s!=='retired'&&s!=='disposed').map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>}
 <label className="text-sm sm:col-span-2">Description<textarea name="description" defaultValue={asset?.description??''} rows={2} className="mt-1 w-full rounded border px-3 py-2"/></label>
 <label className="text-sm sm:col-span-2">Notes<textarea name="notes" defaultValue={asset?.notes??''} rows={2} className="mt-1 w-full rounded border px-3 py-2"/></label>
 <Actions busy={busy} onClose={onClose}/></Form></Modal>}
function CategoryForm({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title="Add asset category" onClose={onClose}><Form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4"><Field name="code" label="Code" required/><Field name="name" label="Name" required/><label className="text-sm">Description<textarea name="description" rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></Form></Modal>}
function AssignForm({employees,busy,onClose,onSubmit}:{employees:Emp[];busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title="Assign asset" onClose={onClose}><Form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4"><label className="text-sm">Employee<select name="employee_id" required className="mt-1 w-full rounded border px-3 py-2">{employees.map(e=><option key={e.id} value={e.id}>{e.employee_no} — {e.preferred_name||`${e.first_name} ${e.last_name}`}</option>)}</select></label><label className="text-sm">Issued condition<select name="issued_condition" defaultValue="good" className="mt-1 w-full rounded border px-3 py-2">{conditions.map(c=><option key={c} value={c}>{label(c)}</option>)}</select></label><Field name="expected_return_date" label="Expected return" type="date"/><label className="text-sm">Assignment notes<textarea name="assignment_notes" rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></Form></Modal>}
function ReturnForm({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title="Return asset" onClose={onClose}><Form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4"><label className="text-sm">Returned condition<select name="returned_condition" defaultValue="good" className="mt-1 w-full rounded border px-3 py-2">{conditions.map(c=><option key={c} value={c}>{label(c)}</option>)}</select></label><Field name="location" label="New location"/><label className="text-sm">Return notes<textarea name="return_notes" rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></Form></Modal>}
function RetireForm({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title="Retire asset" onClose={onClose}><Form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4"><label className="text-sm">Retirement reason *<textarea name="retirement_reason" required rows={3} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></Form></Modal>}
function DisposeForm({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title="Dispose asset" onClose={onClose}><Form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4"><Field name="disposal_date" label="Disposal date" type="date" required/><Field name="disposal_value" label="Disposal / salvage value" type="number" step="0.01"/><Actions busy={busy} onClose={onClose}/></Form></Modal>}
function MaintenanceForm({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <Modal title="Log maintenance" onClose={onClose}><Form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}} className="grid gap-4 sm:grid-cols-2"><Field name="service_date" label="Service date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/><Field name="service_type" label="Service type" required/><Field name="vendor" label="Vendor"/><Field name="cost" label="Cost" type="number" step="0.01"/><Field name="next_service_date" label="Next service due" type="date"/><label className="text-sm sm:col-span-2">Description *<textarea name="description" required rows={2} className="mt-1 w-full rounded border px-3 py-2"/></label><label className="text-sm sm:col-span-2">Notes<textarea name="notes" rows={2} className="mt-1 w-full rounded border px-3 py-2"/></label><Actions busy={busy} onClose={onClose}/></Form></Modal>}
function HistoryModal({asset,maintenance,onClose}:{asset:Asset;maintenance:MaintenanceRow[];onClose:()=>void}){
 const history=asset.assignment_history??[];
 return <Modal title={`History — ${asset.asset_no}`} onClose={onClose}>
 <div className="space-y-6">
 <div><h4 className="mb-2 text-sm font-medium">Assignment history</h4>
 {history.length===0?<p className="text-sm text-slate-500">No assignments recorded.</p>:<table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-3 py-2">Employee</th><th className="px-3 py-2">Assigned</th><th className="px-3 py-2">Returned</th><th className="px-3 py-2">Condition (out / in)</th></tr></thead><tbody className="divide-y">{history.map(h=><tr key={h.id}><td className="px-3 py-2">{h.employee?`${h.employee.employee_no} — ${h.employee.preferred_name||`${h.employee.first_name} ${h.employee.last_name}`}`:'—'}</td><td className="px-3 py-2">{new Date(h.assigned_at).toLocaleDateString()}</td><td className="px-3 py-2">{h.returned_at?new Date(h.returned_at).toLocaleDateString():'Active'}</td><td className="px-3 py-2">{label(h.issued_condition)} / {h.returned_condition?label(h.returned_condition):'—'}</td></tr>)}</tbody></table>}
 </div>
 <div><h4 className="mb-2 text-sm font-medium">Maintenance history</h4>
 {maintenance.length===0?<p className="text-sm text-slate-500">No maintenance recorded.</p>:<table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-3 py-2">Date</th><th className="px-3 py-2">Type</th><th className="px-3 py-2">Description</th><th className="px-3 py-2">Cost</th></tr></thead><tbody className="divide-y">{maintenance.map(m=><tr key={m.id}><td className="px-3 py-2">{new Date(m.service_date).toLocaleDateString()}</td><td className="px-3 py-2">{m.service_type}</td><td className="px-3 py-2">{m.description}</td><td className="px-3 py-2">{money(m.cost)}</td></tr>)}</tbody></table>}
 </div>
 {(asset.status==='retired'||asset.status==='disposed')&&<div className="rounded border bg-slate-50 p-3 text-sm"><div className="font-medium">{label(asset.status)}</div>{asset.retirement_reason&&<div>Reason: {asset.retirement_reason}</div>}{asset.disposal_date&&<div>Disposed on {new Date(asset.disposal_date).toLocaleDateString()}{asset.disposal_value!=null?` for ${money(asset.disposal_value)}`:''}</div>}</div>}
 <div className="flex justify-end border-t pt-4"><button onClick={onClose} className="rounded border px-4 py-2 text-sm">Close</button></div>
 </div></Modal>}
function Field({name,label,type='text',required=false,defaultValue,step}:{name:string;label:string;type?:string;required?:boolean;defaultValue?:string|null;step?:string}){return <label className="text-sm">{label}{required?' *':''}<input name={name} type={type} required={required} defaultValue={defaultValue??''} step={step} className="mt-1 w-full rounded border px-3 py-2"/></label>}
function Actions({busy,onClose}:{busy:boolean;onClose:()=>void}){return <div className="flex justify-end gap-2 border-t pt-4 sm:col-span-2"><button type="button" onClick={onClose} className="rounded border px-4 py-2 text-sm">Cancel</button><button disabled={busy} className="rounded bg-slate-900 px-4 py-2 text-sm font-medium text-white">{busy?'Saving...':'Save'}</button></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/40 p-4"><div className="w-full max-w-3xl rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b px-6 py-4"><h3 className="font-semibold">{title}</h3><button onClick={onClose} className="text-slate-500">✕</button></div><div className="p-6">{children}</div></div></div>}
