'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';

function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
const val=(fd:FormData,k:string)=>{const v=String(fd.get(k)??'').trim();if(!v)throw appError(`${k.replaceAll('_',' ')} is required.`);return v};
const opt=(fd:FormData,k:string)=>{const v=String(fd.get(k)??'').trim();return v||null};
async function marketing(){const p=await getSessionProfile();if(!p?.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.section_code!=='marketing'&&!p.access.some(a=>a.section_code==='marketing'))throw appError('Marketing access required.');return p;}
async function audit(actor:string,id:string,table:string,action:string,detail:any={}){const {error}=await createClient().from('audit_log').insert({actor_id:actor,entity_table:table,entity_id:id,action,detail});if(error)throw appError(error.message);}
export async function createChannelAction(fd:FormData){const p=await marketing(),db=createClient();const {data,error}=await db.from('marketing_channels').insert({...biz(p),channel_code:val(fd,'channel_code'),channel_name:val(fd,'channel_name'),channel_type:opt(fd,'channel_type')||'other',created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create channel.');await audit(p.user.id,data.id,'marketing_channels','channel_created');revalidatePath('/marketing');}
export async function createCampaignAction(fd:FormData){const p=await marketing(),db=createClient();const {data,error}=await db.from('marketing_campaigns').insert({...biz(p),campaign_code:val(fd,'campaign_code'),campaign_name:val(fd,'campaign_name'),objective:opt(fd,'objective'),campaign_type:opt(fd,'campaign_type')||'general',channel_id:opt(fd,'channel_id'),owner_id:opt(fd,'owner_id')||p.user.id,start_date:opt(fd,'start_date'),end_date:opt(fd,'end_date'),budget:Number(fd.get('budget')||0),expected_revenue:Number(fd.get('expected_revenue')||0),target_leads:Number(fd.get('target_leads')||0),notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create campaign.');await audit(p.user.id,data.id,'marketing_campaigns','campaign_created');revalidatePath('/marketing');}
export async function prepareCampaignAction(id:string){const p=await marketing(),db=createClient();const {error}=await db.from('marketing_campaigns').update({status:'prepared',prepared_by:p.user.id,prepared_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','draft');if(error)throw appError(error.message);await audit(p.user.id,id,'marketing_campaigns','prepared');revalidatePath('/marketing');revalidatePath('/approvals');}
export async function reviewCampaignAction(id:string,approve:boolean,reason?:string){const p=await marketing(),db=createClient();const patch:any={status:approve?'reviewed':'draft',reviewed_by:approve?p.user.id:null,reviewed_at:approve?new Date().toISOString():null,notes:approve?undefined:(reason||'Returned for correction'),updated_at:new Date().toISOString()};const {error}=await db.from('marketing_campaigns').update(patch).eq('id',id).eq('status','prepared');if(error)throw appError(error.message);await audit(p.user.id,id,'marketing_campaigns',approve?'reviewed':'returned',{reason:reason||null});revalidatePath('/marketing');revalidatePath('/approvals');}
export async function approveCampaignAction(id:string){const p=await marketing(),db=createClient();const {error}=await db.from('marketing_campaigns').update({status:'approved',approved_by:p.user.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','reviewed');if(error)throw appError(error.message);await audit(p.user.id,id,'marketing_campaigns','approved');revalidatePath('/marketing');revalidatePath('/approvals');}
export async function setCampaignStatusAction(id:string,status:'active'|'paused'|'completed'|'cancelled'){const p=await marketing(),db=createClient();if(status==='active'){const {data,error}=await db.from('marketing_campaigns').select('status').eq('id',id).single();if(error||!data||!['approved','paused'].includes(data.status))throw appError('Only approved or paused campaigns can be activated.');}const {error}=await db.from('marketing_campaigns').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'marketing_campaigns',`campaign_${status}`);revalidatePath('/marketing');}
export async function createLeadAction(fd:FormData){const p=await marketing(),db=createClient();const {data,error}=await db.from('marketing_leads').insert({...biz(p),lead_code:val(fd,'lead_code'),campaign_id:opt(fd,'campaign_id'),channel_id:opt(fd,'channel_id'),company_name:opt(fd,'company_name'),contact_name:val(fd,'contact_name'),email:opt(fd,'email'),phone:opt(fd,'phone'),source:opt(fd,'source'),estimated_value:Number(fd.get('estimated_value')||0),assigned_to:opt(fd,'assigned_to')||p.user.id,notes:opt(fd,'notes'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create lead.');if(opt(fd,'campaign_id')) await db.rpc('marketing_refresh_campaign_metrics',{p_campaign_id:opt(fd,'campaign_id')});await audit(p.user.id,data.id,'marketing_leads','lead_created');revalidatePath('/marketing');}
export async function updateLeadStatusAction(id:string,status:string){const p=await marketing(),db=createClient();const {data:old}=await db.from('marketing_leads').select('campaign_id,status').eq('id',id).single();const {error}=await db.from('marketing_leads').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw appError(error.message);if(old?.campaign_id)await db.rpc('marketing_refresh_campaign_metrics',{p_campaign_id:old.campaign_id});await audit(p.user.id,id,'marketing_leads','lead_status_changed',{status});revalidatePath('/marketing');}
export async function createActivityAction(fd:FormData){const p=await marketing(),db=createClient();const {data,error}=await db.from('marketing_activities').insert({...biz(p),lead_id:opt(fd,'lead_id'),campaign_id:opt(fd,'campaign_id'),activity_type:val(fd,'activity_type'),activity_date:opt(fd,'activity_date')||new Date().toISOString(),subject:val(fd,'subject'),details:opt(fd,'details'),outcome:opt(fd,'outcome'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create activity.');await audit(p.user.id,data.id,'marketing_activities','activity_created');revalidatePath('/marketing');}
