'use client';
import { errorText } from '@/core/errors/appError';
import { useMemo, useState, type ReactNode } from 'react';
import { useDialog } from '@/core/ui/Dialog';
import { createBusinessDocumentAction, createBusinessDocumentTypeAction, deleteBusinessDocumentAction, getBusinessDocumentDownloadUrlAction, updateBusinessDocumentStatusAction } from './actions';

type Business = { id: string; code: string; legal_name: string; trade_name: string | null; is_active: boolean };
type Type = { id: string; code: string; name: string; description?: string | null; required: boolean; requires_expiry: boolean; default_validity_days?: number | null; active: boolean };
type Doc = { id: string; business_id: string; document_type_id: string; document_name: string; document_number?: string | null; issued_date?: string | null; expiry_date?: string | null; status: string; original_file_name?: string | null; file_size?: number | null; notes?: string | null; created_at: string; business?: { code: string; legal_name: string; trade_name: string | null }; type?: { name: string } };

const statuses = ['pending', 'verified', 'rejected', 'expired', 'archived'];
function daysUntil(date?: string | null) { if (!date) return null; return Math.ceil((new Date(`${date}T00:00:00Z`).getTime() - new Date(`${new Date().toISOString().slice(0, 10)}T00:00:00Z`).getTime()) / 86400000); }
function statusLabel(s: string) { return s.charAt(0).toUpperCase() + s.slice(1); }
function bizName(b?: { code: string; legal_name: string; trade_name: string | null }) { return b ? (b.trade_name || b.legal_name) : '—'; }

export default function BusinessDocuments({ businesses, types, documents, isSuperAdmin, canDelete }: { businesses: Business[]; types: Type[]; documents: Doc[]; isSuperAdmin: boolean; canDelete: boolean }) {
 const dialog = useDialog();
 const [query, setQuery] = useState(''); const [businessFilter, setBusinessFilter] = useState('all'); const [status, setStatus] = useState('all'); const [showAdd, setShowAdd] = useState(false); const [showType, setShowType] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
 const filtered = useMemo(() => documents.filter(d => { const b = d.business; const hay = `${d.document_name} ${d.document_number ?? ''} ${b?.code ?? ''} ${bizName(b)} ${d.type?.name ?? ''}`.toLowerCase(); return (!query || hay.includes(query.toLowerCase())) && (businessFilter === 'all' || d.business_id === businessFilter) && (status === 'all' || d.status === status); }), [documents, query, businessFilter, status]);
 const expiring = documents.filter(d => { const n = daysUntil(d.expiry_date); return n !== null && n >= 0 && n <= 30 && d.status !== 'archived'; }).length;
 const expired = documents.filter(d => { const n = daysUntil(d.expiry_date); return n !== null && n < 0 && d.status !== 'archived'; }).length;
 // Compliance rollup: required business_document_types with no current verified, unexpired document for a business.
 const complianceGaps = useMemo(() => {
  const requiredTypes = types.filter(t => t.active && t.required);
  const rows: { business: Business; type: Type; state: 'missing' | 'expired' | 'expiring' | 'pending' | 'rejected'; doc?: Doc }[] = [];
  for (const b of businesses.filter(x => x.is_active)) {
   for (const t of requiredTypes) {
    const docsForType = documents.filter(d => d.business_id === b.id && d.document_type_id === t.id && d.status !== 'archived');
    if (docsForType.length === 0) { rows.push({ business: b, type: t, state: 'missing' }); continue; }
    const byRecency = [...docsForType].sort((a, c) => c.created_at.localeCompare(a.created_at));
    const verified = byRecency.find(d => d.status === 'verified');
    const chosen = verified || byRecency[0];
    const n = daysUntil(chosen.expiry_date);
    if (chosen.status === 'verified') { if (n !== null && n < 0) rows.push({ business: b, type: t, state: 'expired', doc: chosen }); else if (n !== null && n <= 30) rows.push({ business: b, type: t, state: 'expiring', doc: chosen }); }
    else if (chosen.status === 'rejected') rows.push({ business: b, type: t, state: 'rejected', doc: chosen });
    else rows.push({ business: b, type: t, state: 'pending', doc: chosen });
   }
  }
  return rows;
 }, [businesses, types, documents]);
 const complianceLabel: Record<string, string> = { missing: 'Missing', expired: 'Expired', expiring: 'Expiring soon', pending: 'Pending verification', rejected: 'Rejected' };
 const complianceColor: Record<string, string> = { missing: 'bg-red-100 text-red-800', expired: 'bg-red-100 text-red-800', expiring: 'bg-amber-100 text-amber-800', pending: 'bg-slate-100 text-slate-700', rejected: 'bg-amber-100 text-amber-800' };
 const [view, setView] = useState<'documents' | 'compliance'>('documents');
 async function run(fn: () => Promise<any>) { setBusy(true); setError(''); try { await fn(); location.reload(); } catch (e) { setError(e instanceof Error ? errorText(e) : 'Operation failed.'); } finally { setBusy(false); } }
 async function download(id: string) { setBusy(true); setError(''); try { const r = await getBusinessDocumentDownloadUrlAction(id); window.open(r.url, '_blank', 'noopener,noreferrer'); } catch (e) { setError(e instanceof Error ? errorText(e) : 'Unable to download document.'); } finally { setBusy(false); } }
 return <div className="space-y-6">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Business Documents & Compliance</h2><p className="text-sm text-slate-500">Permits, licenses and business-level compliance records — one set per business, never mixed with employee documents.</p></div><div className="flex gap-2">{isSuperAdmin && <button onClick={() => setShowType(true)} className="rounded border px-4 py-2 text-sm">Document types</button>}<button onClick={() => setShowAdd(true)} className="rounded bg-slate-900 px-4 py-2 text-sm font-medium text-white">+ Add document</button></div></div>
  {error && <div className="rounded border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  <div className="grid gap-3 sm:grid-cols-4"><Stat label="Documents" value={documents.length} /><Stat label="Expiring within 30 days" value={expiring} /><Stat label="Expired" value={expired} /><Stat label="Compliance gaps" value={complianceGaps.length} /></div>
  <div className="flex gap-2 border-b pb-2">{(['documents', 'compliance'] as const).map(v => <button key={v} onClick={() => setView(v)} className={`rounded px-3 py-2 text-sm ${view === v ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-700'}`}>{v === 'documents' ? 'Documents' : `Compliance (${complianceGaps.length})`}</button>)}</div>
  {view === 'documents' && <>
  <div className="flex flex-col gap-3 rounded-lg border bg-white p-4 lg:flex-row"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search business, document, number..." className="flex-1 rounded border px-3 py-2 text-sm" />{isSuperAdmin && <select value={businessFilter} onChange={e => setBusinessFilter(e.target.value)} className="rounded border px-3 py-2 text-sm"><option value="all">All businesses</option>{businesses.map(b => <option key={b.id} value={b.id}>{bizName(b)}</option>)}</select>}<select value={status} onChange={e => setStatus(e.target.value)} className="rounded border px-3 py-2 text-sm"><option value="all">All statuses</option>{statuses.map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select></div>
  <div className="overflow-x-auto rounded-lg border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr>{isSuperAdmin && <th className="px-4 py-3">Business</th>}<th className="px-4 py-3">Document</th><th className="px-4 py-3">Issued / Expiry</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">File</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{filtered.map(d => { const n = daysUntil(d.expiry_date); return <tr key={d.id} className="border-t align-top">{isSuperAdmin && <td className="px-4 py-3"><div className="font-medium">{bizName(d.business)}</div><div className="text-xs text-slate-500">{d.business?.code}</div></td>}<td className="px-4 py-3"><div className="font-medium">{d.document_name}</div><div className="text-xs text-slate-500">{d.type?.name}{d.document_number ? ` · ${d.document_number}` : ''}</div></td><td className="px-4 py-3">{d.issued_date || '—'}<div className={`${n !== null && n < 0 ? 'text-red-600' : n !== null && n <= 30 ? 'text-amber-600' : 'text-slate-500'} text-xs`}>Expiry: {d.expiry_date || 'No expiry'}{n !== null ? ` · ${n < 0 ? `${Math.abs(n)}d overdue` : `${n}d`}` : ''}</div></td><td className="px-4 py-3"><select disabled={busy} value={d.status} onChange={e => run(() => { const f = new FormData(); f.set('document_id', d.id); f.set('status', e.target.value); if (e.target.value === 'rejected') f.set('rejection_reason', 'Rejected by Admin'); return updateBusinessDocumentStatusAction(f); })} className="rounded border px-2 py-1 text-xs">{statuses.map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select></td><td className="px-4 py-3">{d.original_file_name ? <button disabled={busy} onClick={() => download(d.id)} className="text-blue-700 hover:underline">Open file</button> : <span className="text-slate-400">No file</span>}</td><td className="px-4 py-3 whitespace-nowrap"><button disabled={busy} onClick={() => run(() => { const f = new FormData(); f.set('document_id', d.id); f.set('status', 'verified'); return updateBusinessDocumentStatusAction(f); })} className="mr-2 text-green-700 hover:underline">Verify</button><button disabled={busy} onClick={() => run(() => { const f = new FormData(); f.set('document_id', d.id); f.set('status', 'rejected'); f.set('rejection_reason', 'Rejected by Admin'); return updateBusinessDocumentStatusAction(f); })} className="mr-2 text-amber-700 hover:underline">Reject</button>{canDelete && <button disabled={busy} onClick={() => dialog.confirm('Delete this document and its stored file?', { tone: 'danger' }).then(ok => { if (ok) run(() => { const f = new FormData(); f.set('document_id', d.id); return deleteBusinessDocumentAction(f); }); })} className="text-red-700 hover:underline">Delete</button>}</td></tr>; })}{filtered.length === 0 && <tr><td colSpan={isSuperAdmin ? 6 : 5} className="px-4 py-10 text-center text-slate-500">No business documents found.</td></tr>}</tbody></table></div>
  </>}
  {view === 'compliance' && <div className="overflow-x-auto rounded-lg border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-4 py-3">Business</th><th className="px-4 py-3">Required document</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Detail</th></tr></thead><tbody>{complianceGaps.map((r, i) => <tr key={i} className="border-t"><td className="px-4 py-3">{bizName(r.business)}</td><td className="px-4 py-3">{r.type.name}</td><td className="px-4 py-3"><span className={`rounded px-2 py-0.5 text-xs font-medium ${complianceColor[r.state]}`}>{complianceLabel[r.state]}</span></td><td className="px-4 py-3 text-xs text-slate-500">{r.doc?.expiry_date ? `Expiry: ${r.doc.expiry_date}` : r.state === 'missing' ? 'No document on file' : '—'}</td></tr>)}{complianceGaps.length === 0 && <tr><td colSpan={4} className="px-4 py-10 text-center text-slate-500">No compliance gaps — every active business has every required document on file, verified and current.</td></tr>}</tbody></table></div>}
  {showAdd && <DocumentForm businesses={businesses} types={types} isSuperAdmin={isSuperAdmin} busy={busy} onClose={() => setShowAdd(false)} onSubmit={fd => run(() => createBusinessDocumentAction(fd))} />} {showType && <TypeForm busy={busy} onClose={() => setShowType(false)} onSubmit={fd => run(() => createBusinessDocumentTypeAction(fd))} />}
 </div>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-lg border bg-white p-4"><div className="text-xs uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>; }
function DocumentForm({ businesses, types, isSuperAdmin, busy, onClose, onSubmit }: { businesses: Business[]; types: Type[]; isSuperAdmin: boolean; busy: boolean; onClose: () => void; onSubmit: (f: FormData) => void }) {
 return <Modal title="Add business document" onClose={onClose}><form onSubmit={e => { e.preventDefault(); onSubmit(new FormData(e.currentTarget)); }} className="grid gap-4 sm:grid-cols-2">
  {isSuperAdmin && <label className="text-sm sm:col-span-2">Business<select name="business_id" required className="mt-1 w-full rounded border px-3 py-2">{businesses.filter(b => b.is_active).map(b => <option key={b.id} value={b.id}>{bizName(b)}</option>)}</select></label>}
  <label className="text-sm sm:col-span-2">Document type<select name="document_type_id" required className="mt-1 w-full rounded border px-3 py-2">{types.filter(t => t.active).map(t => <option key={t.id} value={t.id}>{t.name}{t.requires_expiry ? ' · expiry required' : ''}</option>)}</select></label>
  <Field name="document_name" label="Document name" required /><Field name="document_number" label="Document number" /><Field name="issued_date" label="Issued date" type="date" /><Field name="expiry_date" label="Expiry date" type="date" />
  <label className="text-sm sm:col-span-2">File (PDF/JPG/PNG/WEBP, max 10 MB)<input name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="mt-1 w-full rounded border px-3 py-2" /></label>
  <label className="text-sm sm:col-span-2">Notes<textarea name="notes" rows={3} className="mt-1 w-full rounded border px-3 py-2" /></label>
  <Actions busy={busy} onClose={onClose} /></form></Modal>;
}
function TypeForm({ busy, onClose, onSubmit }: { busy: boolean; onClose: () => void; onSubmit: (f: FormData) => void }) { return <Modal title="Add business document type" onClose={onClose}><form onSubmit={e => { e.preventDefault(); onSubmit(new FormData(e.currentTarget)); }} className="grid gap-4"><Field name="code" label="Code" required /><Field name="name" label="Name" required /><Field name="default_validity_days" label="Default validity (days)" type="number" /><label className="text-sm">Description<textarea name="description" rows={3} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="flex items-center gap-2 text-sm"><input name="required" type="checkbox" /> Required for every active business</label><label className="flex items-center gap-2 text-sm"><input name="requires_expiry" type="checkbox" /> Requires expiry date</label><Actions busy={busy} onClose={onClose} /></form></Modal>; }
function Actions({ busy, onClose }: { busy: boolean; onClose: () => void }) { return <div className="flex justify-end gap-2 border-t pt-4 sm:col-span-2"><button type="button" onClick={onClose} className="rounded border px-4 py-2 text-sm">Cancel</button><button disabled={busy} className="rounded bg-slate-900 px-4 py-2 text-sm font-medium text-white">{busy ? 'Saving...' : 'Save'}</button></div>; }
function Field({ name, label, type = 'text', required = false }: { name: string; label: string; type?: string; required?: boolean }) { return <label className="text-sm">{label}{required ? ' *' : ''}<input name={name} type={type} required={required} className="mt-1 w-full rounded border px-3 py-2" /></label>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/40 p-4"><div className="w-full max-w-2xl rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b px-6 py-4"><h3 className="font-semibold">{title}</h3><button onClick={onClose} className="text-slate-500">✕</button></div><div className="p-6">{children}</div></div></div>; }
