'use server';
import { appError } from '@/core/errors/appError';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';
function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
function req(fd: FormData, key: string) { const v=String(fd.get(key)??'').trim(); if(!v) throw appError(`${key.replaceAll('_',' ')} is required.`); return v; }
function opt(fd: FormData,key:string){const v=String(fd.get(key)??'').trim();return v||null;}
async function admin(){const p=await getSessionProfile();if(!p||!p.user.is_active)throw appError('Authentication required.');if(!isAdminTier(p)&&p.user.section_code!=='admin'&&!p.access.some(a=>a.section_code==='admin'))throw appError('Admin access required.');return p;}
async function sectionId(db:any){const {data,error}=await db.from('sections').select('id').eq('code','admin').single();if(error||!data)throw appError('Admin section is not configured.');return data.id;}
async function audit(actor:string,id:string,action:string,detail:Record<string,unknown>){const {error}=await createClient().from('audit_log').insert({actor_id:actor,entity_table:'expenses',entity_id:id,action,detail});if(error)throw appError(error.message);}
export async function createAdminExpenseCategoryAction(fd:FormData){const p=await admin(),db=createClient();const code=req(fd,'code').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');const name=req(fd,'name');const {data,error}=await db.from('admin_expense_categories').insert({code,name,description:opt(fd,'description'),created_by:p.user.id}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create expense category.');await audit(p.user.id,data.id,'admin_expense_category_created',{code,name});revalidatePath('/admin/expenses');return {ok:true};}
export async function createAdminExpenseAction(fd:FormData){const p=await admin(),db=createClient(),sid=await sectionId(db);const amount=Number(req(fd,'amount'));if(!Number.isFinite(amount)||amount<=0)throw appError('Amount must be greater than zero.');const {data,error}=await db.from('expenses').insert({...biz(p),section_id:sid,month_id:req(fd,'month_id'),description:req(fd,'description'),amount,status:'draft',prepared_by:p.user.id,expense_date:req(fd,'expense_date'),category_id:opt(fd,'category_id'),cost_center_id:opt(fd,'cost_center_id'),vendor:opt(fd,'vendor'),supplier_id:opt(fd,'supplier_id'),payment_method:opt(fd,'payment_method'),reference_no:opt(fd,'reference_no'),receipt_reference:opt(fd,'receipt_reference'),asset_id:opt(fd,'asset_id'),fleet_vehicle_id:opt(fd,'fleet_vehicle_id'),supply_request_id:opt(fd,'supply_request_id'),notes:opt(fd,'notes')}).select('id').single();if(error||!data)throw appError(error?.message||'Unable to create admin expense.');await audit(p.user.id,data.id,'admin_expense_created',{amount,description:String(fd.get('description')??'')});revalidatePath('/admin/expenses');return {ok:true};}
export async function updateAdminExpenseAction(fd:FormData){const p=await admin(),db=createClient(),id=req(fd,'expense_id');const {data:current}=await db.from('expenses').select('status,prepared_by,section_id').eq('id',id).single();if(!current)throw appError('Expense not found.');if(current.status!=='draft')throw appError('Only draft expenses can be edited.');const sid=await sectionId(db);if(current.section_id!==sid)throw appError('Invalid admin expense.');const amount=Number(req(fd,'amount'));if(!Number.isFinite(amount)||amount<=0)throw appError('Amount must be greater than zero.');const {error}=await db.from('expenses').update({description:req(fd,'description'),amount,expense_date:req(fd,'expense_date'),category_id:opt(fd,'category_id'),cost_center_id:opt(fd,'cost_center_id'),vendor:opt(fd,'vendor'),supplier_id:opt(fd,'supplier_id'),payment_method:opt(fd,'payment_method'),reference_no:opt(fd,'reference_no'),receipt_reference:opt(fd,'receipt_reference'),notes:opt(fd,'notes')}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'admin_expense_edited',{amount});revalidatePath('/admin/expenses');return {ok:true};}
export async function deleteAdminExpenseAction(id:string){const p=await admin(),db=createClient();const {data:row}=await db.from('expenses').select('status,prepared_by').eq('id',id).single();if(!row)throw appError('Expense not found.');if(row.status!=='draft')throw appError('Only draft expenses can be cleared.');const {error}=await db.from('expenses').delete().eq('id',id).eq('status','draft');if(error)throw appError(error.message);await audit(p.user.id,id,'admin_expense_draft_cleared',{});revalidatePath('/admin/expenses');return {ok:true};}
export async function rejectAdminExpenseAction(fd:FormData){const p=await admin(),db=createClient(),id=req(fd,'expense_id'),reason=req(fd,'rejection_reason');const {data:row}=await db.from('expenses').select('status,section_id').eq('id',id).single();if(!row)throw appError('Expense not found.');const sid=await sectionId(db);if(row.section_id!==sid||!['prepared','reviewed'].includes(row.status))throw appError('Expense is not awaiting return action.');const {error}=await db.from('expenses').update({status:'draft',rejection_reason:reason}).eq('id',id);if(error)throw appError(error.message);await audit(p.user.id,id,'admin_expense_returned',{reason});revalidatePath('/admin/expenses');revalidatePath('/approvals');return {ok:true};}
