'use client';
import { errorText } from '@/core/errors/appError';
import { useRef, useState, useTransition } from 'react';
import type { ReactNode } from 'react';
import { useDialog } from '@/core/ui/Dialog';
import { ActionBar, PopupAction } from '@/core/ui/PopupAction';
import type { SessionProfile } from '@/core/auth/types';
import { hasWorkflowRole } from '@/core/auth/types';
import { StatusBadge } from '@/core/utils/statusBadge';
import { createAdminExpenseAction, createAdminExpenseCategoryAction, rejectAdminExpenseAction, updateAdminExpenseAction, deleteAdminExpenseAction } from './actions';
import { submitForReviewAction, markReviewedAction, markApprovedAction } from '@/shared/expenses/actions';
export function AdminExpenses({profile,monthId,rows,categories,assets,vehicles,costCenters=[],suppliers=[],descriptionSuggestions=[]}:{profile:SessionProfile;monthId:string;rows:any[];categories:any[];assets:any[];vehicles:any[];costCenters?:any[];suppliers?:any[];descriptionSuggestions?:string[]}){
 const dialog=useDialog();
 const [pending,start]=useTransition();const [editing,setEditing]=useState<any|null>(null);const [message,setMessage]=useState('');const formRef=useRef<HTMLFormElement>(null);
 const run=(fn:()=>Promise<any>)=>start(async()=>{setMessage('');try{await fn();setMessage('Saved.')}catch(e:any){setMessage(errorText(e)||'Action failed.')}});
 const submit=(fd:FormData,close?:()=>void)=>run(async()=>{await createAdminExpenseAction(fd);formRef.current?.reset();close?.()});
 const returned=(r:any)=>{dialog.prompt('Reason for returning this expense to draft?',{required:true}).then(reason=>{if(!reason)return;const fd=new FormData();fd.set('expense_id',r.id);fd.set('rejection_reason',reason);run(()=>rejectAdminExpenseAction(fd));})};
 return <div className="space-y-6"><div><h2 className="text-xl font-semibold">Admin Expenses</h2><p className="text-sm text-slate-500 mt-1">Administrative operating expenses with workflow, supporting references and links to company resources.</p></div>
  <ActionBar>
  <PopupAction label="+ Add expense" title="Add admin expense" notice={message} wide>
  {(close)=><form ref={formRef} action={fd=>submit(fd,close)} className="grid grid-cols-1 md:grid-cols-4 gap-3"><input type="hidden" name="month_id" value={monthId}/>
 <Field label="Expense date"><input className="input" name="expense_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field>
 <Field label="Category"><select className="input" name="category_id" required><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
 {costCenters.length>0&&<Field label="Cost center"><select className="input" name="cost_center_id"><option value="">Unassigned</option>{costCenters.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></Field>}
 <Field label="Description"><input className="input" name="description" list="admin-expense-description-suggestions" required/><datalist id="admin-expense-description-suggestions">{descriptionSuggestions.map((item)=><option key={item} value={item}/>)}</datalist></Field><Field label="Amount (PHP)"><input className="input" name="amount" type="number" step="0.01" min="0.01" required/></Field>
 <Field label="Vendor / Payee (free text)"><input className="input" name="vendor"/></Field>{suppliers.length>0&&<Field label="Or select a known supplier"><select className="input" name="supplier_id"><option value="">Not a listed supplier</option>{suppliers.map((s:any)=><option key={s.id} value={s.id}>{s.supplier_code} — {s.legal_name}</option>)}</select></Field>}<Field label="Payment method"><select className="input" name="payment_method"><option value="">Select</option><option>Cash</option><option>Bank transfer</option><option>GCash</option><option>Card</option><option>Check</option><option>Other</option></select></Field>
 <Field label="Reference no."><input className="input" name="reference_no"/></Field><Field label="Receipt reference"><input className="input" name="receipt_reference" placeholder="Receipt/file number"/></Field>
 <Field label="Asset link"><select className="input" name="asset_id"><option value="">None</option>{assets.map(a=><option key={a.id} value={a.id}>{a.asset_no} — {a.name}</option>)}</select></Field>
 <Field label="Fleet vehicle"><select className="input" name="fleet_vehicle_id"><option value="">None</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.vehicle_no}{v.plate_no?` — ${v.plate_no}`:''}</option>)}</select></Field>
 <div className="md:col-span-2"><Field label="Notes"><input className="input" name="notes"/></Field></div><div className="md:col-span-4"><button disabled={pending} className="button">{pending?'Saving…':'Save expense draft'}</button></div></form>}
  </PopupAction>
  <PopupAction label="+ Add category" title="Add expense category" variant="secondary" notice={message}>
  {(close)=><form action={(fd)=>run(async()=>{await createAdminExpenseCategoryAction(fd);close()})} className="flex flex-wrap gap-2 items-end"><Field label="New category code"><input className="input" name="code" required/></Field><Field label="Name"><input className="input" name="name" required/></Field><Field label="Description"><input className="input" name="description"/></Field><button disabled={pending} className="button">Add category</button></form>}
  </PopupAction>
  </ActionBar>
 {message&&<div className="rounded-lg bg-slate-100 px-3 py-2 text-sm">{message}</div>}
 <div className="grid grid-cols-1 md:grid-cols-4 gap-3"><Summary title="This month" value={rows.reduce((n,r)=>n+Number(r.amount),0)}/><Summary title="Drafts" value={rows.filter(r=>r.status==='draft').reduce((n,r)=>n+Number(r.amount),0)}/><Summary title="For review" value={rows.filter(r=>r.status==='prepared'||r.status==='reviewed').reduce((n,r)=>n+Number(r.amount),0)}/><Summary title="Approved" value={rows.filter(r=>r.status==='approved').reduce((n,r)=>n+Number(r.amount),0)}/></div>
 <div className="rounded-xl border bg-white overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">Date</th><th className="p-3">Expense</th><th className="p-3">Vendor</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{rows.map(r=>{const canSubmit=hasWorkflowRole(profile,r.section_id,'preparer')&&r.prepared_by===profile.user.id&&r.status==='draft';const canReview=hasWorkflowRole(profile,r.section_id,'reviewer')&&r.status==='prepared';const canApprove=hasWorkflowRole(profile,r.section_id,'approver')&&r.status==='reviewed';return <tr key={r.id} className="border-b last:border-0"><td className="p-3 whitespace-nowrap">{r.expense_date}</td><td className="p-3"><div className="font-medium">{r.description}</div><div className="text-xs text-slate-400">{r.category?.name||'Uncategorised'}{r.reference_no?` · ${r.reference_no}`:''}</div></td><td className="p-3">{suppliers.find((s:any)=>s.id===r.supplier_id)?.legal_name||r.vendor||'—'}</td><td className="p-3 font-medium">₱{Number(r.amount).toLocaleString(undefined,{minimumFractionDigits:2})}</td><td className="p-3"><StatusBadge status={r.status}/>{r.rejection_reason&&<div className="text-xs text-red-600 mt-1">Returned: {r.rejection_reason}</div>}</td><td className="p-3 space-x-2 whitespace-nowrap">{canSubmit&&<button disabled={pending} onClick={()=>run(()=>submitForReviewAction(r.id,'/admin/expenses'))} className="link">Submit</button>}{canReview&&<><button disabled={pending} onClick={()=>run(()=>markReviewedAction(r.id,'/admin/expenses'))} className="link">Review</button><button disabled={pending} onClick={()=>returned(r)} className="link text-red-600">Return</button></>}{canApprove&&<><button disabled={pending} onClick={()=>run(()=>markApprovedAction(r.id,'/admin/expenses'))} className="link text-green-600">Approve</button><button disabled={pending} onClick={()=>returned(r)} className="link text-red-600">Return</button></>}{r.status==='draft'&&<button disabled={pending} onClick={()=>setEditing(r)} className="link">Edit</button>}{r.status==='draft'&&<button disabled={pending} onClick={()=>dialog.confirm('Discard this draft expense? This cannot be undone.',{tone:'danger',confirmLabel:'Discard'}).then(ok=>{if(ok)run(()=>deleteAdminExpenseAction(r.id))})} className="link text-red-600">Clear draft</button>}</td></tr>})}{rows.length===0&&<tr><td colSpan={6} className="p-8 text-center text-slate-400">No admin expenses for this month.</td></tr>}</tbody></table></div>
 {editing&&<div className="fixed inset-0 bg-black/30 flex items-center justify-center p-4"><form action={fd=>run(async()=>{await updateAdminExpenseAction(fd);setEditing(null)})} className="bg-white rounded-xl p-5 w-full max-w-xl space-y-3"><input type="hidden" name="expense_id" value={editing.id}/><h3 className="font-semibold">Edit draft</h3><div className="grid grid-cols-2 gap-3"><Field label="Date"><input className="input" type="date" name="expense_date" defaultValue={editing.expense_date}/></Field><Field label="Amount"><input className="input" type="number" step="0.01" name="amount" defaultValue={editing.amount}/></Field><div className="col-span-2"><Field label="Description"><input className="input" name="description" defaultValue={editing.description}/></Field></div><Field label="Vendor (free text)"><input className="input" name="vendor" defaultValue={editing.vendor||''}/></Field>{suppliers.length>0&&<Field label="Or known supplier"><select className="input" name="supplier_id" defaultValue={editing.supplier_id||''}><option value="">Not a listed supplier</option>{suppliers.map((s:any)=><option key={s.id} value={s.id}>{s.supplier_code} — {s.legal_name}</option>)}</select></Field>}<Field label="Reference"><input className="input" name="reference_no" defaultValue={editing.reference_no||''}/></Field><Field label="Category"><select className="input" name="category_id" defaultValue={editing.category_id||''}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>{costCenters.length>0&&<Field label="Cost center"><select className="input" name="cost_center_id" defaultValue={editing.cost_center_id||''}><option value="">Unassigned</option>{costCenters.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></Field>}<Field label="Payment"><input className="input" name="payment_method" defaultValue={editing.payment_method||''}/></Field></div><div className="flex gap-2"><button className="button" disabled={pending}>Save</button><button type="button" className="button-secondary" onClick={()=>setEditing(null)}>Cancel</button></div></form></div>}</div>
}
function Field({label,children}:{label:string;children:ReactNode}){return <div><label className="label">{label}</label>{children}</div>}
function Summary({title,value}:{title:string;value:number}){return <div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">{title}</div><div className="text-xl font-semibold mt-1">₱{value.toLocaleString(undefined,{minimumFractionDigits:2})}</div></div>}
