'use server';
import { appError } from '@/core/errors/appError';

import { revalidatePath } from 'next/cache';
import { createClient } from '@/core/auth/supabaseServer';
import { getSessionProfile } from '@/core/auth/getSessionProfile';
import { isAdminTier } from '@/core/auth/types';
import { notifyWorkflowRole, notifyUsers } from '@/shared/notifications/service';

function biz(p:{user:{business_id:string|null}}):{business_id?:string}{return p.user.business_id?{business_id:p.user.business_id}:{};}
type RequestStatus = 'prepared'|'reviewed'|'approved'|'rejected'|'cancelled';
const STATUSES: RequestStatus[] = ['prepared','reviewed','approved','rejected','cancelled'];

function required(fd: FormData, key: string) { const v = String(fd.get(key) ?? '').trim(); if (!v) throw appError(`${key.replaceAll('_',' ')} is required.`); return v; }
function optional(fd: FormData, key: string) { const v = String(fd.get(key) ?? '').trim(); return v || null; }
function num(fd: FormData, key: string) { const v = Number(fd.get(key)); if (!Number.isFinite(v)) throw appError(`${key.replaceAll('_',' ')} must be a number.`); return v; }
async function adminOnly() { const p=await getSessionProfile(); if(!p||!p.user.is_active) throw appError('Authentication required.'); if(!isAdminTier(p) && p.user.section_code!=='admin' && !p.access.some(a=>a.section_code==='admin')) throw appError('Admin access required.'); return p; }
async function audit(actorId:string, entityId:string, action:string, detail:Record<string,unknown>){ const db=createClient(); const {error}=await db.from('audit_log').insert({actor_id:actorId,entity_table:'leave_requests',entity_id:entityId,action,detail}); if(error) throw appError(error.message); }
function daysBetweenInclusive(start:string,end:string){ const a=new Date(`${start}T00:00:00Z`), b=new Date(`${end}T00:00:00Z`); return Math.floor((b.getTime()-a.getTime())/86400000)+1; }

export async function createLeaveTypeAction(fd:FormData){ const actor=await adminOnly(); const db=createClient(); const code=required(fd,'code').toLowerCase().replace(/\s+/g,'_'); const name=required(fd,'name'); const payload={code,name,description:optional(fd,'description'),paid:fd.get('paid')==='on',requires_approval:fd.get('requires_approval')!=='off',active:true,default_days_per_year:optional(fd,'default_days_per_year')?Number(fd.get('default_days_per_year')):null}; const {data,error}=await db.from('leave_types').insert(payload).select('id').single(); if(error||!data) throw appError(error?.message||'Unable to create leave type.'); await audit(actor.user.id,data.id,'created',{code,name}); revalidatePath('/admin/leave'); return {ok:true}; }

export async function requestLeaveAction(fd:FormData){ const p=await getSessionProfile(); if(!p||!p.user.is_active) throw appError('Authentication required.'); const db=createClient(); const employeeId=required(fd,'employee_id'); const leaveTypeId=required(fd,'leave_type_id'); const start=required(fd,'start_date'); const end=required(fd,'end_date'); const dayType=required(fd,'day_type'); const reason=required(fd,'reason'); if(!['full_day','first_half','second_half'].includes(dayType)) throw appError('Invalid leave day type.'); if(end<start) throw appError('End date cannot be before start date.'); const {data:employee}=await db.from('employees').select('id,user_id').eq('id',employeeId).maybeSingle(); if(!employee) throw appError('Employee not found.'); const isAdmin=isAdminTier(p)||p.user.section_code==='admin'||p.access.some(a=>a.section_code==='admin'); if(employee.user_id!==p.user.id && !isAdmin) throw appError('You can only request leave for your own employee record.'); const calendarDays=daysBetweenInclusive(start,end); const days=dayType==='full_day'?calendarDays:calendarDays===1?0.5:(calendarDays-1)+0.5; if(days<=0) throw appError('Leave duration must be greater than zero.'); const {data,error}=await db.from('leave_requests').insert({...biz(p),employee_id:employeeId,leave_type_id:leaveTypeId,start_date:start,end_date:end,day_type:dayType,days,reason,status:'prepared',requested_by:p.user.id}).select('id,business_id').single(); if(error||!data) throw appError(error?.message||'Unable to submit leave request.'); await audit(p.user.id,data.id,'submitted',{employee_id:employeeId,leave_type_id:leaveTypeId,start_date:start,end_date:end,days}); await notifyWorkflowRole(data.business_id,'admin','reviewer',{title:'Leave request needs review',message:reason,entity_table:'leave_requests',entity_id:data.id,action_url:'/admin/leave'}); revalidatePath('/admin/leave'); return {ok:true}; }

export async function reviewLeaveAction(fd:FormData){ const actor=await adminOnly(); const id=required(fd,'leave_request_id'); const decision=required(fd,'decision'); const db=createClient(); if(!['reviewed','rejected'].includes(decision)) throw appError('Invalid review decision.'); const patch:any={status:decision,reviewed_by:actor.user.id,reviewed_at:new Date().toISOString()}; if(decision==='rejected') patch.rejection_reason=optional(fd,'rejection_reason')||'Rejected by Admin'; const {data,error}=await db.from('leave_requests').update(patch).eq('id',id).eq('status','prepared').select('id,business_id,requested_by').single(); if(error||!data) throw appError(error?.message||'Leave request is no longer pending.'); await audit(actor.user.id,id,decision,{decision}); if(decision==='reviewed') await notifyWorkflowRole(data.business_id,'admin','approver',{title:'Leave request needs approval',message:'A reviewed leave request is awaiting your approval.',entity_table:'leave_requests',entity_id:id,action_url:'/admin/leave'}); else if(data.requested_by) await notifyUsers([data.requested_by],data.business_id,{title:'Leave request rejected',message:patch.rejection_reason,entity_table:'leave_requests',entity_id:id,action_url:'/admin/leave'}); revalidatePath('/admin/leave'); return {ok:true}; }

export async function approveLeaveAction(fd:FormData){ const actor=await adminOnly(); const id=required(fd,'leave_request_id'); const db=createClient(); const {data:req,error}=await db.from('leave_requests').select('*').eq('id',id).eq('status','reviewed').maybeSingle(); if(error||!req) throw appError(error?.message||'Reviewed leave request not found.');
 const {data:conflicts}=await db.from('leave_requests').select('id,start_date,end_date,status').eq('employee_id',req.employee_id).in('status',['prepared','reviewed','approved']).lte('start_date',req.end_date).gte('end_date',req.start_date).neq('id',id); if(conflicts&&conflicts.length) throw appError('This leave overlaps another pending or approved leave request.');
 const {error:updateError}=await db.from('leave_requests').update({status:'approved',approved_by:actor.user.id,approved_at:new Date().toISOString()}).eq('id',id); if(updateError) throw appError(updateError.message);
 const start=new Date(`${req.start_date}T00:00:00Z`), end=new Date(`${req.end_date}T00:00:00Z`); const dates:string[]=[]; for(let d=new Date(start);d<=end;d.setUTCDate(d.getUTCDate()+1)) dates.push(d.toISOString().slice(0,10));
 for(const date of dates){ const status=req.day_type==='full_day'?'leave':date===req.start_date&&req.day_type==='first_half'?'leave':date===req.end_date&&req.day_type==='second_half'?'leave':'leave'; const {data:existing}=await db.from('attendance_records').select('id,period_id,status').eq('employee_id',req.employee_id).eq('attendance_date',date).maybeSingle(); if(existing?.period_id){ const {data:period}=await db.from('attendance_periods').select('status').eq('id',existing.period_id).maybeSingle(); if(period?.status==='locked') throw appError(`Attendance for ${date} is locked; leave cannot be posted.`); }
   if(existing){ const {error:e}=await db.from('attendance_records').update({status,notes:`Approved leave: ${req.id}`,regular_hours:0,overtime_hours:0,late_minutes:0,undertime_minutes:0,updated_at:new Date().toISOString()}).eq('id',existing.id); if(e) throw appError(e.message); }
   else { const {error:e}=await db.from('attendance_records').insert({...biz(actor),employee_id:req.employee_id,attendance_date:date,status,notes:`Approved leave: ${req.id}`,prepared_by:actor.user.id}); if(e) throw appError(e.message); }
 }
 const year=new Date(`${req.start_date}T00:00:00Z`).getUTCFullYear(); const {data:balance}=await db.from('employee_leave_balances').select('id,used').eq('employee_id',req.employee_id).eq('leave_type_id',req.leave_type_id).eq('leave_year',year).maybeSingle(); if(balance){ const {error:e}=await db.from('employee_leave_balances').update({used:Number(balance.used)+Number(req.days)}).eq('id',balance.id); if(e) throw appError(e.message); }
 else { const {data:type}=await db.from('leave_types').select('default_days_per_year').eq('id',req.leave_type_id).single(); const {error:e}=await db.from('employee_leave_balances').insert({...biz(actor),employee_id:req.employee_id,leave_type_id:req.leave_type_id,leave_year:year,entitlement:Number(type?.default_days_per_year||0),used:Number(req.days),adjustment:0}); if(e) throw appError(e.message); }
 await audit(actor.user.id,id,'approved',{days:req.days,attendance_posted:dates}); if(req.requested_by) await notifyUsers([req.requested_by],req.business_id,{title:'Leave request approved',message:`Your leave request for ${req.start_date} to ${req.end_date} was approved.`,entity_table:'leave_requests',entity_id:id,action_url:'/admin/leave'}); revalidatePath('/admin/leave'); revalidatePath('/admin/timekeeping'); return {ok:true}; }

export async function cancelLeaveAction(fd:FormData){ const p=await getSessionProfile(); if(!p||!p.user.is_active) throw appError('Authentication required.'); const id=required(fd,'leave_request_id'); const db=createClient(); const {data:req}=await db.from('leave_requests').select('id,employee_id,requested_by,status').eq('id',id).maybeSingle(); if(!req) throw appError('Leave request not found.'); const isAdmin=isAdminTier(p)||p.user.section_code==='admin'||p.access.some(a=>a.section_code==='admin'); if(!isAdmin&&req.requested_by!==p.user.id) throw appError('You can only cancel your own request.'); if(!['prepared','reviewed'].includes(req.status)) throw appError('Only pending leave requests can be cancelled.'); const {error}=await db.from('leave_requests').update({status:'cancelled'}).eq('id',id); if(error) throw appError(error.message); await audit(p.user.id,id,'cancelled',{}); revalidatePath('/admin/leave'); return {ok:true}; }
