'use client';
import { errorText } from '@/core/errors/appError';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ActionBar, PopupAction } from '@/core/ui/PopupAction';
import { approveLeaveAction, cancelLeaveAction, createLeaveTypeAction, requestLeaveAction, reviewLeaveAction } from './actions';

type Employee={id:string;employee_no:string;first_name:string;last_name:string;preferred_name:string|null;user_id:string|null;employment_status:string};
type LeaveType={id:string;code:string;name:string;paid:boolean;active:boolean;requires_approval:boolean;default_days_per_year:number|null};
type Request={id:string;employee_id:string;leave_type_id:string;start_date:string;end_date:string;day_type:string;days:number;reason:string;status:string;rejection_reason:string|null;requested_by:string};
type Balance={id:string;employee_id:string;leave_type_id:string;leave_year:number;entitlement:number;used:number;adjustment:number};
const statusLabel:Record<string,string>={prepared:'Prepared',reviewed:'Reviewed',approved:'Approved',rejected:'Rejected',cancelled:'Cancelled'};
export default function LeaveManagement({employees,types,requests,balances}:{employees:Employee[];types:LeaveType[];requests:Request[];balances:Balance[]}){
 const [tab,setTab]=useState('requests'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''); const router=useRouter();
 async function run(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();router.refresh()}catch(e){setError(e instanceof Error?errorText(e):'Operation failed')}finally{setBusy(false)}}
 const filtered=useMemo(()=>requests.filter(r=>{const e=employees.find(x=>x.id===r.employee_id),t=types.find(x=>x.id===r.leave_type_id);const h=[e?.employee_no,e?.first_name,e?.last_name,e?.preferred_name,t?.name,r.start_date,r.end_date,r.status].filter(Boolean).join(' ').toLowerCase();return !query||h.includes(query.toLowerCase())}),[requests,employees,types,query]);
 return <div className="space-y-6">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-semibold">Leave Management</h2><p className="text-sm text-slate-500">Leave requests, balances and approval-driven attendance posting.</p></div></div>
  {error&&<div className="rounded border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-4"><Stat title="Employees" value={String(employees.filter(e=>e.employment_status!=='separated').length)}/><Stat title="Requests" value={String(requests.length)}/><Stat title="Pending review" value={String(requests.filter(r=>r.status==='prepared').length)}/><Stat title="Approved" value={String(requests.filter(r=>r.status==='approved').length)}/></div>
  <div className="flex flex-wrap gap-2 border-b pb-2">{[['requests','Requests'],['balances','Balances'],['types','Leave types']].map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`rounded px-3 py-2 text-sm ${tab===v?'bg-slate-900 text-white':'bg-slate-100 text-slate-700'}`}>{l}</button>)}</div>
  {tab==='requests'&&<section className="space-y-4"><ActionBar><PopupAction label="Request leave" title="Request leave" notice={error}>{(close)=><LeaveForm employees={employees} types={types.filter(t=>t.active)} busy={busy} onClose={close} onSubmit={f=>run(async()=>{await requestLeaveAction(f);close()})}/>}</PopupAction></ActionBar><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee, leave type, date or status..." className="w-full rounded border px-3 py-2 text-sm"/><div className="overflow-x-auto rounded-lg border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Leave</th><th className="px-4 py-3">Dates</th><th className="px-4 py-3">Days</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{filtered.map(r=>{const e=employees.find(x=>x.id===r.employee_id),t=types.find(x=>x.id===r.leave_type_id);return <tr key={r.id} className="border-t"><td className="px-4 py-3">{e?.preferred_name||`${e?.first_name} ${e?.last_name}`}<div className="text-xs text-slate-500">{e?.employee_no}</div></td><td className="px-4 py-3">{t?.name}{t?.paid?'':' · unpaid'}</td><td className="px-4 py-3">{r.start_date} → {r.end_date}<div className="text-xs text-slate-500">{r.day_type}</div></td><td className="px-4 py-3">{r.days}</td><td className="px-4 py-3">{statusLabel[r.status]||r.status}</td><td className="px-4 py-3 whitespace-nowrap">{r.status==='prepared'&&<><button disabled={busy} onClick={()=>run(async()=>{const f=new FormData();f.set('leave_request_id',r.id);f.set('decision','reviewed');await reviewLeaveAction(f)})} className="mr-3 text-blue-700 hover:underline">Review</button><button disabled={busy} onClick={()=>run(async()=>{const f=new FormData();f.set('leave_request_id',r.id);f.set('decision','rejected');f.set('rejection_reason','Rejected by Admin');await reviewLeaveAction(f)})} className="mr-3 text-red-700 hover:underline">Reject</button></>}{r.status==='reviewed'&&<button disabled={busy} onClick={()=>run(async()=>{const f=new FormData();f.set('leave_request_id',r.id);await approveLeaveAction(f)})} className="mr-3 text-emerald-700 hover:underline">Approve</button>}{['prepared','reviewed'].includes(r.status)&&<button disabled={busy} onClick={()=>run(async()=>{const f=new FormData();f.set('leave_request_id',r.id);await cancelLeaveAction(f)})} className="text-slate-600 hover:underline">Cancel</button>}</td></tr>})}{filtered.length===0&&<tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">No leave requests found.</td></tr>}</tbody></table></div></section>}
  {tab==='balances'&&<section className="overflow-x-auto rounded-lg border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Leave type</th><th className="px-4 py-3">Entitlement</th><th className="px-4 py-3">Used</th><th className="px-4 py-3">Adjustment</th><th className="px-4 py-3">Available</th></tr></thead><tbody>{balances.map(b=>{const e=employees.find(x=>x.id===b.employee_id),t=types.find(x=>x.id===b.leave_type_id),available=Number(b.entitlement)+Number(b.adjustment)-Number(b.used);return <tr key={b.id} className="border-t"><td className="px-4 py-3">{e?.preferred_name||`${e?.first_name} ${e?.last_name}`}</td><td className="px-4 py-3">{t?.name}</td><td className="px-4 py-3">{b.entitlement}</td><td className="px-4 py-3">{b.used}</td><td className="px-4 py-3">{b.adjustment}</td><td className="px-4 py-3 font-medium">{available}</td></tr>})}{balances.length===0&&<tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">No leave balances yet. They are created when an approved leave is posted.</td></tr>}</tbody></table></section>}
  {tab==='types'&&<section className="space-y-4"><ActionBar><PopupAction label="+ New leave type" title="New leave type" notice={error}>{(close)=><TypeForm busy={busy} onClose={close} onSubmit={f=>run(async()=>{await createLeaveTypeAction(f);close()})}/>}</PopupAction></ActionBar><div className="grid gap-4 md:grid-cols-2">{types.map(t=><div key={t.id} className="rounded-lg border bg-white p-5"><div className="flex justify-between"><h3 className="font-semibold">{t.name}</h3><span className="text-xs text-slate-500">{t.code}</span></div><p className="mt-2 text-sm text-slate-500">{t.paid?'Paid':'Unpaid'} · {t.requires_approval?'Approval required':'No approval'}</p><p className="mt-1 text-sm text-slate-500">Default entitlement: {t.default_days_per_year??'Not set'} days/year</p></div>)}{types.length===0&&<div className="rounded border bg-white p-8 text-center text-slate-500">No leave types.</div>}</div></section>}
  </div>
}
function Stat({title,value}:{title:string;value:string}){return <div className="rounded-lg border bg-white p-4"><div className="text-xs uppercase tracking-wide text-slate-500">{title}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>}
function LeaveForm({employees,types,busy,onClose,onSubmit}:{employees:Employee[];types:LeaveType[];busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <form action={onSubmit} className="grid gap-3"><select name="employee_id" required className="rounded border px-3 py-2"><option value="">Employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_no} — {e.preferred_name||`${e.first_name} ${e.last_name}`}</option>)}</select><select name="leave_type_id" required className="rounded border px-3 py-2"><option value="">Leave type</option>{types.map(t=><option key={t.id} value={t.id}>{t.name}{t.paid?'':' (unpaid)'}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Start<input name="start_date" type="date" required className="mt-1 w-full rounded border px-3 py-2"/></label><label className="text-sm">End<input name="end_date" type="date" required className="mt-1 w-full rounded border px-3 py-2"/></label></div><select name="day_type" defaultValue="full_day" className="rounded border px-3 py-2"><option value="full_day">Full day</option><option value="first_half">First half</option><option value="second_half">Second half</option></select><textarea name="reason" required placeholder="Reason" className="min-h-24 rounded border px-3 py-2"/><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded border px-3 py-2">Cancel</button><button disabled={busy} className="rounded bg-slate-900 px-3 py-2 text-white">Submit</button></div></form>}
function TypeForm({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(f:FormData)=>void}){return <form action={onSubmit} className="grid gap-3"><input name="code" required placeholder="Code e.g. vacation" className="rounded border px-3 py-2"/><input name="name" required placeholder="Name" className="rounded border px-3 py-2"/><input name="default_days_per_year" type="number" min="0" step="0.5" placeholder="Default days per year" className="rounded border px-3 py-2"/><textarea name="description" placeholder="Description" className="min-h-20 rounded border px-3 py-2"/><label className="text-sm"><input type="checkbox" name="paid" defaultChecked className="mr-2"/>Paid leave</label><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded border px-3 py-2">Cancel</button><button disabled={busy} className="rounded bg-slate-900 px-3 py-2 text-white">Create</button></div></form>}
