'use client';
import { Form } from '@/core/ui/Form';
import { errorText } from '@/core/errors/appError';
import {useState,useTransition} from 'react';
import {useDialog} from '@/core/ui/Dialog';
import { ActionBar, PopupAction } from '@/core/ui/PopupAction';
import type {SessionProfile} from '@/core/auth/types';
import {StatusBadge} from '@/core/utils/statusBadge';
import * as A from '../warehouseDeliveryActions';
import * as F from '../fleetDeliveryActions';

function driverName(d:any){const e=d?.employee;return e?.preferred_name||[e?.first_name,e?.last_name].filter(Boolean).join(' ')||'Driver'}
export function WarehouseDeliveryManagement({profile,locations,items,customers,orders,dispatches,vehicles,drivers}:{profile:SessionProfile;locations:any[];items:any[];customers:any[];orders:any[];dispatches:any[];vehicles:any[];drivers:any[]}){
 const dialog=useDialog();
 const [busy,start]=useTransition(); const [error,setError]=useState(''); const [pod,setPod]=useState<{id:string;recipient:string;reference:string;notes:string}|null>(null);
 const run=(fn:()=>Promise<any>)=>{setError('');start(async()=>{try{await fn()}catch(e:any){setError(errorText(e)||'Action failed')}})};
 const [lines,setLines]=useState([{inventory_item_id:items[0]?.id||'',quantity:1,unit_price:0}]);
 return <div className="space-y-6 p-6">
  <div><h1 className="text-2xl font-bold">Warehouse / Delivery Operations</h1><p className="text-sm text-slate-500">Outbound fulfillment, fleet assignment, dispatch execution, delivery tracking and proof of delivery.</p></div>
  <ActionBar><PopupAction label="+ Create delivery order" title="Create delivery order" notice={error} wide>{(close)=><Form action={(fd)=>{fd.set('lines',JSON.stringify(lines));run(async()=>{await A.createDeliveryOrderAction(fd);close()})}} className="grid grid-cols-1 md:grid-cols-3 gap-3">
   <input name="delivery_number" placeholder="Delivery number" required className="border rounded p-2"/><select name="customer_id" className="border rounded p-2"><option value="">No customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.customer_code} — {c.legal_name}</option>)}</select><select name="source_location_id" required className="border rounded p-2">{locations.map(l=><option key={l.id} value={l.id}>{l.location_code} — {l.location_name}</option>)}</select><input type="date" name="delivery_date" required className="border rounded p-2"/><input type="date" name="requested_delivery_date" className="border rounded p-2"/><input name="delivery_address" placeholder="Delivery address" className="border rounded p-2"/><input name="contact_name" placeholder="Recipient / contact" className="border rounded p-2"/><input name="contact_phone" placeholder="Contact phone" className="border rounded p-2"/><input name="sales_reference" placeholder="Sales / order reference" className="border rounded p-2"/>
   <div className="md:col-span-3 space-y-2">{lines.map((l,i)=><div key={i} className="flex gap-2"><select value={l.inventory_item_id} onChange={e=>setLines(x=>x.map((v,j)=>j===i?{...v,inventory_item_id:e.target.value}:v))} className="border rounded p-2 flex-1">{items.map(it=><option key={it.id} value={it.id}>{it.item_code} — {it.item_name}</option>)}</select><input type="number" min="0.001" step="0.001" value={l.quantity} onChange={e=>setLines(x=>x.map((v,j)=>j===i?{...v,quantity:Number(e.target.value)}:v))} className="border rounded p-2 w-28"/><input type="number" min="0" step="0.01" value={l.unit_price} onChange={e=>setLines(x=>x.map((v,j)=>j===i?{...v,unit_price:Number(e.target.value)}:v))} className="border rounded p-2 w-32"/></div>)}<button type="button" onClick={()=>setLines(x=>[...x,{inventory_item_id:items[0]?.id||'',quantity:1,unit_price:0}])} className="text-sm underline">+ Add line</button></div><textarea name="notes" placeholder="Notes" className="border rounded p-2 md:col-span-3"/><button disabled={busy} className="rounded bg-slate-900 text-white px-4 py-2">Create</button>
  </Form>}</PopupAction><PopupAction label="Plan dispatch" title="Fleet dispatch" variant="secondary" notice={error} wide>{(close)=><Form action={(fd)=>run(async()=>{await A.createDispatchAction(fd);close()})} className="grid grid-cols-1 md:grid-cols-4 gap-3"><input name="dispatch_number" placeholder="Dispatch number" required className="border rounded p-2"/><select name="delivery_order_id" required className="border rounded p-2"><option value="">Approved delivery</option>{orders.filter(o=>o.status==='approved').map(o=><option key={o.id} value={o.id}>{o.delivery_number}</option>)}</select><select name="vehicle_id" required className="border rounded p-2"><option value="">Vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.vehicle_no} — {v.plate_no||'No plate'}</option>)}</select><select name="driver_id" required className="border rounded p-2"><option value="">Driver</option>{drivers.map(d=><option key={d.id} value={d.id}>{driverName(d)}</option>)}</select><input type="date" name="dispatch_date" required className="border rounded p-2"/><input name="recipient_name" placeholder="Recipient" className="border rounded p-2"/><input name="expected_arrival" type="datetime-local" className="border rounded p-2"/><input name="route_notes" placeholder="Route / dispatch notes" className="border rounded p-2"/><button disabled={busy} className="rounded bg-slate-900 text-white px-4 py-2">Plan dispatch</button></Form>}</PopupAction></ActionBar>
  {error&&<div className="rounded bg-red-50 border border-red-200 p-3 text-sm text-red-700">{error}</div>}
  <section className="grid grid-cols-2 md:grid-cols-5 gap-3"><Metric label="Orders" value={orders.length}/><Metric label="Ready to dispatch" value={orders.filter(o=>o.status==='approved').length}/><Metric label="In transit" value={dispatches.filter(d=>d.delivery_status==='in_transit').length}/><Metric label="Delivered" value={dispatches.filter(d=>d.delivery_status==='delivered').length}/><Metric label="Fleet-ready" value={vehicles.length}/></section>
  <section className="rounded border bg-white p-5"><h2 className="font-semibold mb-3">Fulfillment queue</h2><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-2">Number</th><th>Customer</th><th>Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-b"><td className="p-2 font-medium">{o.delivery_number}</td><td>{o.customer?.legal_name||'—'}</td><td>{o.delivery_date}</td><td><StatusBadge status={o.status}/></td><td className="space-x-2">{o.status==='draft'&&<button onClick={()=>run(()=>A.prepareDeliveryOrderAction(o.id))} className="underline">Prepare</button>}{o.status==='prepared'&&<button onClick={()=>run(()=>A.pickDeliveryOrderAction(o.id))} className="underline">Pick</button>}{o.status==='picked'&&<button onClick={()=>run(()=>A.packDeliveryOrderAction(o.id))} className="underline">Pack</button>}{o.status==='packed'&&<button onClick={()=>run(()=>A.reviewDeliveryOrderAction(o.id,true))} className="underline">Review</button>}{o.status==='reviewed'&&<button onClick={()=>run(()=>A.approveDeliveryOrderAction(o.id))} className="underline">Approve</button>}</td></tr>)}</tbody></table></div></section>
  <section className="rounded border bg-white p-5"><h2 className="font-semibold mb-3">Fleet dispatch</h2>

   <div className="mt-5 overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-2">Dispatch</th><th>Delivery</th><th>Fleet</th><th>Trip</th><th>Status</th><th>Actions</th></tr></thead><tbody>{dispatches.map(d=><tr key={d.id} className="border-b"><td className="p-2">{d.dispatch_number}</td><td>{d.delivery?.delivery_number}</td><td>{d.vehicle?.vehicle_no||'—'} / {driverName(d.driver)}</td><td>{d.trip?.trip_no||'—'}</td><td><StatusBadge status={d.delivery_status}/></td><td>{d.delivery_status==='planned'&&<button onClick={()=>run(()=>F.loadDispatchAction(d.id))} className="underline mr-2">Load</button>}{d.delivery_status==='loaded'&&<button onClick={()=>run(()=>F.startDispatchTripAction(d.id))} className="underline mr-2">Depart</button>}{d.delivery_status==='in_transit'&&<><button onClick={()=>setPod({id:d.id,recipient:d.recipient_name||'',reference:d.proof_of_delivery_reference||'',notes:''})} className="underline mr-2">POD / Deliver</button><button onClick={()=>{dialog.prompt('Reason for failed delivery?').then(r=>{if(r)run(()=>F.failDispatchAction(d.id,r))})}} className="underline text-red-700">Fail</button></>}</td></tr>)}</tbody></table></div>
  </section>
  {pod&&<div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4"><Form onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);run(async()=>{await F.completeDeliveryOperationsAction(pod.id,fd);setPod(null)})}} className="bg-white rounded-lg p-5 w-full max-w-md space-y-3"><h2 className="font-semibold">Proof of Delivery</h2><input name="recipient_name" required value={pod.recipient} onChange={e=>setPod({...pod,recipient:e.target.value})} placeholder="Recipient name" className="border rounded p-2 w-full"/><input name="proof_of_delivery_reference" value={pod.reference} onChange={e=>setPod({...pod,reference:e.target.value})} placeholder="POD / signed document reference" className="border rounded p-2 w-full"/><textarea name="notes" value={pod.notes} onChange={e=>setPod({...pod,notes:e.target.value})} placeholder="Delivery notes" className="border rounded p-2 w-full"/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setPod(null)} className="border rounded px-3 py-2">Cancel</button><button disabled={busy} className="bg-slate-900 text-white rounded px-3 py-2">Complete delivery</button></div></Form></div>}
 </div>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded border bg-white p-4"><div className="text-xs text-slate-500">{label}</div><div className="text-2xl font-bold">{value}</div></div>}
